---
sidebar: sidebar 
permalink: docs/concept_cg_hci_accounts.html 
summary: 클라우드 서비스가 지원되는 각 NetApp HCI 시스템은 NetApp Cloud Central 계정에 연결됩니다. 
keywords: netapp, hci, on premise, administrator, user account, cloud services, cluster 
---
= 사용자 계정
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
시스템의 스토리지 리소스에 액세스하려면 사용자 계정을 설정해야 합니다.



== 사용자 계정 관리

사용자 계정은 NetApp Element 소프트웨어 기반 네트워크에서 스토리지 리소스에 대한 액세스를 제어하는 데 사용됩니다. 볼륨을 생성하기 전에 최소 하나의 사용자 계정이 필요합니다.

볼륨을 생성하면 계정에 할당됩니다. 가상 볼륨을 생성한 경우 해당 계정은 스토리지 컨테이너입니다.

다음은 몇 가지 추가 고려 사항입니다.

* 이 계정에는 할당된 볼륨에 액세스하는 데 필요한 CHAP 인증이 포함되어 있습니다.
* 계정에는 최대 2000개의 볼륨이 할당될 수 있지만 볼륨은 하나의 계정에만 속할 수 있습니다.
* 사용자 계정은 NetApp Element 관리 확장 지점에서 관리할 수 있습니다.


NetApp 하이브리드 클라우드 제어를 사용하면 다음과 같은 유형의 고객을 생성하고 관리할 수 있습니다.

* 스토리지 클러스터에 대한 관리자 사용자 계정입니다
* 권한 있는 사용자 계정
* 생성된 스토리지 클러스터에만 해당하는 볼륨 계정입니다.




== 스토리지 클러스터 관리자 계정

NetApp Element 소프트웨어를 실행하는 스토리지 클러스터에 있을 수 있는 관리자 계정에는 두 가지 유형이 있습니다.

* * 기본 클러스터 관리자 계정 *: 이 관리자 계정은 클러스터를 생성할 때 생성됩니다. 이 계정은 클러스터에 대한 최고 수준의 액세스 권한을 가진 기본 관리 계정입니다. 이 계정은 Linux 시스템의 루트 사용자와 유사합니다. 이 관리자 계정의 암호를 변경할 수 있습니다.
* * 클러스터 관리자 계정 *: 클러스터 관리자 계정에 제한된 범위의 관리 액세스 권한을 부여하여 클러스터 내에서 특정 작업을 수행할 수 있습니다. 각 클러스터 관리자 계정에 할당된 자격 증명은 스토리지 시스템 내에서 API 및 Element UI 요청을 인증하는 데 사용됩니다.



NOTE: 노드별 UI를 통해 클러스터의 활성 노드에 액세스하려면 로컬(LDAP가 아닌) 클러스터 관리자 계정이 필요합니다. 아직 클러스터에 속하지 않은 노드에 액세스하려면 계정 자격 증명이 필요하지 않습니다.

클러스터 관리자 계정을 생성, 삭제 및 편집하고, 클러스터 관리자 암호를 변경하고, 사용자에 대한 시스템 액세스를 관리하도록 LDAP 설정을 구성하여 클러스터 관리자 계정을 관리할 수 있습니다.



== 권한 있는 사용자 계정

권한 있는 사용자 계정은 노드 및 클러스터의 NetApp 하이브리드 클라우드 제어 인스턴스와 연결된 스토리지 자산에 대해 인증할 수 있습니다. 이 계정을 사용하면 모든 클러스터에서 볼륨, 계정, 액세스 그룹 등을 관리할 수 있습니다.

권한 있는 사용자 계정은 NetApp 하이브리드 클라우드 제어의 오른쪽 상단 메뉴 사용자 관리 옵션에서 관리합니다.

를 클릭합니다 link:concept_hci_clusters.html#authoritative-storage-clusters["권한 있는 스토리지 클러스터"] NetApp Hybrid Cloud Control에서 사용자를 인증하는 데 사용하는 스토리지 클러스터입니다.

신뢰할 수 있는 스토리지 클러스터에서 생성된 모든 사용자는 NetApp 하이브리드 클라우드 제어에 로그인할 수 있습니다. 다른 스토리지 클러스터에서 생성한 사용자는 하이브리드 클라우드 제어에 _cannot_logon 할 수 없습니다.

* 관리 노드에 스토리지 클러스터가 하나만 있는 경우 신뢰할 수 있는 클러스터입니다.
* 관리 노드에 둘 이상의 스토리지 클러스터가 있는 경우 이러한 클러스터 중 하나가 권한 있는 클러스터로 할당되고 해당 클러스터의 사용자만 NetApp 하이브리드 클라우드 제어에 로그인할 수 있습니다.


많은 NetApp 하이브리드 클라우드 제어 기능이 여러 스토리지 클러스터에서 작동되지만, 인증과 권한 부여는 필수 제한 사항이 됩니다. 인증 및 권한 부여에 대한 제한 사항은 권한 있는 클러스터의 사용자가 다른 스토리지 클러스터에 있는 사용자가 아니더라도 NetApp 하이브리드 클라우드 제어에 연결된 다른 클러스터에 대해 작업을 실행할 수 있다는 것입니다. 여러 스토리지 클러스터를 관리하기 전에 권한 있는 클러스터에 정의된 사용자가 동일한 권한을 가진 다른 모든 스토리지 클러스터에 정의되어 있는지 확인해야 합니다. NetApp 하이브리드 클라우드 제어에서 사용자를 관리할 수 있습니다.



== 볼륨 계정

볼륨별 계정은 생성된 스토리지 클러스터에만 적용됩니다. 이러한 계정을 사용하면 네트워크 전체의 특정 볼륨에 대한 사용 권한을 설정할 수 있지만 이러한 볼륨 외부에는 영향을 미치지 않습니다.

볼륨 계정은 NetApp Hybrid Cloud Control Volumes 표 내에서 관리됩니다.



== 자세한 내용을 확인하십시오

* link:task_hcc_manage_accounts.html["사용자 계정을 관리합니다"]
* link:concept_hci_clusters.html["클러스터에 대해 알아보십시오"]
* https://docs.netapp.com/us-en/vcp/index.html["vCenter Server용 NetApp Element 플러그인"^]

