---
sidebar: sidebar 
permalink: docs/concept_hci_volumes.html 
summary: 볼륨입니다 
keywords: netapp, hci, storage volume, solidfire volume, element volume, persistent volume 
---
= 볼륨
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
스토리지는 NetApp Element 시스템에서 볼륨으로 프로비저닝됩니다. 볼륨은 iSCSI 또는 Fibre Channel 클라이언트를 사용하여 네트워크를 통해 액세스하는 블록 디바이스입니다.

vCenter Server용 NetApp Element 플러그인을 사용하면 사용자 계정의 볼륨을 백업 또는 복원합니다. 또한 클러스터의 각 볼륨을 관리하고 볼륨 액세스 그룹에서 볼륨을 추가 또는 제거할 수 있습니다.



== 영구 볼륨

영구 볼륨을 사용하면 관리 노드 구성 데이터를 VM이 로컬로 저장되지 않고 지정된 스토리지 클러스터에 저장할 수 있으므로 관리 노드가 손실되거나 제거된 경우에도 데이터를 보존할 수 있습니다. 영구 볼륨은 선택 사항이지만 권장되는 관리 노드 구성입니다.

NetApp 배포 엔진을 사용하여 NetApp HCI용 관리 노드를 구축하는 경우 영구 볼륨이 자동으로 설정 및 구성됩니다.

새 관리 노드를 구축할 때 설치 및 업그레이드 스크립트에는 영구 볼륨을 사용하도록 설정하는 옵션이 포함되어 있습니다. 영구 볼륨은 VM 수명 기간 이후에도 지속된 호스트 관리 노드 VM에 대한 관리 노드 구성 정보가 포함된 Element 소프트웨어 기반 스토리지 클러스터의 볼륨입니다. 관리 노드가 손실된 경우 대체 관리 노드 VM이 손실된 VM에 다시 연결하여 구성 데이터를 복구할 수 있습니다.

설치 또는 업그레이드 중에 활성화된 영구 볼륨 기능은 할당된 클러스터의 이름에 NetApp-HCI 사전 할당 기능을 사용하여 여러 볼륨을 자동으로 생성합니다. 이러한 볼륨은 Element 소프트웨어 기반 볼륨과 마찬가지로 기본 설정 및 설치에 따라 Element 소프트웨어 웹 UI, vCenter Server용 NetApp Element 플러그인 또는 API를 사용하여 볼 수 있습니다. 복구에 사용할 수 있는 현재 구성 데이터를 유지하려면 관리 노드에 대한 iSCSI 연결을 통해 영구 볼륨이 가동되어 실행 중이어야 합니다.


NOTE: 설치 또는 업그레이드 중에 관리 서비스와 연결된 영구 볼륨이 생성되고 새 계정에 할당됩니다. 영구 볼륨을 사용하는 경우 볼륨이나 연결된 계정을 수정하거나 삭제하지 마십시오



== 자세한 내용을 확인하십시오

* link:task_hcc_manage_vol_management.html["볼륨 관리"]
* https://docs.netapp.com/us-en/vcp/index.html["vCenter Server용 NetApp Element 플러그인"^]
* http://docs.netapp.com/sfe-122/index.jsp["SolidFire 및 Element 소프트웨어 설명서 센터"^]

