---
sidebar: sidebar 
permalink: docs/concept_hcc_expandoverview.html 
summary: NetApp 하이브리드 클라우드 제어를 사용하여 NetApp HCI 시스템을 확장할 수 있습니다. 
keywords: NetApp, HCI, on premise, expand, hcc, hybrid cloud control 
---
= 확장 개요
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/
:keywords: hci, cloud, onprem, documentation, help


[role="lead"]
NetApp 하이브리드 클라우드 제어를 사용하여 NetApp HCI 시스템을 확장할 수 있습니다. 스토리지 또는 컴퓨팅 리소스를 별도로 확장하거나 동시에 확장할 수 있습니다.


NOTE: 신규 및 예비 H610S 스토리지 노드의 경우 스토리지 클러스터의 기존 Element 소프트웨어 버전을 기반으로 추가 설치 요구 사항이 있을 수 있습니다. 자세한 내용은 NetApp Support에 문의하십시오.

NetApp HCI 섀시에 노드를 설치한 후 NetApp 하이브리드 클라우드 제어를 사용하여 새 리소스를 사용하도록 NetApp HCI를 구성합니다. NetApp HCI는 기존 네트워크 구성을 감지하고 기존 네트워크 및 VLAN 내에서 구성 옵션을 제공합니다(있는 경우).


NOTE: 최근에 설치를 확장했으며 새 자산이 구성에 자동으로 추가되지 않은 경우 자산을 수동으로 추가해야 할 수 있습니다. 을 참조하십시오 link:task_mnode_work_overview.html["관리 노드 개요"].

NetApp HCI는 VMware EVC(Enhanced vMotion Compatibility)를 사용하여 vSphere 클러스터에 CPU 세대가 서로 다른 컴퓨팅 노드가 있을 때 vMotion 기능을 보장합니다. 확장에 EVC가 필요한 경우 NetApp HCI는 가능할 때마다 자동으로 이를 활성화합니다.

다음 상황에서는 확장을 완료하기 위해 vSphere 클라이언트에서 EVC 설정을 수동으로 변경해야 할 수 있습니다.

* 기존 컴퓨팅 노드의 CPU 생성이 추가하려는 컴퓨팅 노드보다 더 최신입니다.
* 제어 vCenter 인스턴스는 필요한 EVC 수준을 지원하지 않습니다.
* 추가하려는 컴퓨팅 노드에 제어 vCenter 인스턴스의 EVC 설정보다 오래된 CPU 생성이 있습니다.



NOTE: NetApp 구축 엔진에서 NetApp HCI 컴퓨팅 또는 스토리지 리소스를 확장하는 경우 기존 NetApp HCI 컴퓨팅 노드를 관리하는 vCenter 인스턴스에 연결해야 합니다.

[discrete]
== 자세한 내용을 확인하십시오

* link:task_hcc_expand_compute.html["NetApp HCI 컴퓨팅 리소스를 확장합니다"]
* link:task_hcc_expand_storage.html["NetApp HCI 스토리지 리소스를 확장합니다"]
* link:task_hcc_expand_compute_and_storage.html["NetApp HCI 스토리지 및 컴퓨팅 리소스를 동시에 확장합니다"]
* https://www.netapp.com/hybrid-cloud/hci-documentation/["NetApp HCI 리소스 페이지를 참조하십시오"^]
* https://docs.netapp.com/us-en/vcp/index.html["vCenter Server용 NetApp Element 플러그인"^]

