---
sidebar: sidebar 
permalink: docs/concept_hci_dataprotection.html 
summary: 데이터 보호 용어에는 다양한 유형의 원격 복제, 볼륨 스냅샷, 볼륨, 클론 복제, 보호 도메인, 이중 Helix 기술로 고가용성을 보장합니다. 
keywords: netapp, hci, data protection, ha, snapshots, replication, cloning, helix 
---
= 데이터 보호
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
NetApp HCI 데이터 보호 용어에는 다양한 유형의 원격 복제, 볼륨 스냅샷, 볼륨 클론 복제, 보호 도메인, 이중 Helix 기술을 통한 고가용성 등이 포함됩니다.

NetApp HCI 데이터 보호에는 다음과 같은 개념이 포함되어 있습니다.

* <<Remote replication types>>
* <<Volume snapshots for data protection>>
* <<Volume clones>>
* <<Backup and restore process overview for SolidFire storage>>
* <<Protection domains>>
* <<Double Helix high availability>>




== 원격 복제 유형입니다

데이터의 원격 복제에는 다음과 같은 형태가 있습니다.

* <<Synchronous and asynchronous replication between clusters>>
* <<Snapshot-only replication>>
* <<Replication between Element and ONTAP clusters using SnapMirror>>


을 참조하십시오 https://www.netapp.com/us/media/tr-4741.pdf["TR-4741: NetApp Element 소프트웨어 원격 복제"^].



=== 클러스터 간 동기식 및 비동기식 복제

NetApp Element 소프트웨어를 실행하는 클러스터의 경우 실시간 복제를 통해 볼륨 데이터의 원격 복사본을 신속하게 생성할 수 있습니다.

스토리지 클러스터를 최대 4개의 다른 스토리지 클러스터와 페어링할 수 있습니다. 장애 조치 및 장애 복구 시나리오를 위해 클러스터 쌍의 클러스터 중 하나에서 볼륨 데이터를 동기 또는 비동기식으로 복제할 수 있습니다.



==== 동기식 복제

동기식 복제는 소스 클러스터에서 타겟 클러스터로 지속적으로 데이터를 복제하며 지연 시간, 패킷 손실, 지터 및 대역폭에 의해 영향을 받습니다.

동기식 복제는 다음과 같은 상황에 적합합니다.

* 짧은 거리에서 여러 시스템을 복제합니다
* 소스에 지리적으로 로컬 재해 복구 사이트입니다
* 시간에 민감한 애플리케이션 및 데이터베이스 보호
* 운영 사이트가 다운된 경우 2차 사이트가 운영 사이트 역할을 해야 하는 비즈니스 연속성 애플리케이션




==== 비동기식 복제

비동기식 복제는 타겟 클러스터의 승인을 기다리지 않고 소스 클러스터에서 타겟 클러스터로 지속적으로 데이터를 복제합니다. 비동기식 복제 중에는 소스 클러스터에서 커밋된 후 클라이언트(애플리케이션)에 쓰기가 확인됩니다.

비동기식 복제는 다음과 같은 상황에 적합합니다.

* 재해 복구 사이트가 소스에서 멀리 떨어져 있고 애플리케이션이 네트워크에 의해 발생하는 지연 시간을 허용하지 않습니다.
* 소스 및 타겟 클러스터를 연결하는 네트워크에는 대역폭 제한이 있습니다.




=== 스냅샷 전용 복제

스냅샷 전용 데이터 보호는 특정 시점의 변경된 데이터를 원격 클러스터로 복제합니다. 소스 클러스터에서 생성된 스냅샷만 복제됩니다. 소스 볼륨의 활성 쓰기는 그렇지 않습니다.

스냅샷 복제 빈도를 설정할 수 있습니다.

스냅샷 복제는 비동기식 또는 동기식 복제에 영향을 주지 않습니다.



=== SnapMirror를 사용하여 Element와 ONTAP 클러스터 간 복제

NetApp SnapMirror 기술을 사용하면 NetApp Element 소프트웨어를 사용하여 촬영한 스냅샷을 재해 복구를 위해 ONTAP로 복제할 수 있습니다. SnapMirror 관계에서 Element는 하나의 엔드포인트이고 ONTAP는 다른 엔드포인트입니다.

SnapMirror는 지리적으로 원격 사이트의 운영 스토리지에서 2차 스토리지로 페일오버할 수 있도록 설계된 재해 복구를 촉진하는 NetApp Snapshot ™ 복제 기술입니다. SnapMirror 기술은 1차 사이트에서 장애가 발생하더라도 데이터를 계속 제공할 수 있는 2차 스토리지에서 작업 데이터의 복제본 또는 미러를 생성합니다. 데이터가 볼륨 레벨에서 미러링됩니다.

운영 스토리지의 소스 볼륨과 2차 스토리지의 타겟 볼륨 간의 관계를 데이터 보호 관계라고 합니다. 클러스터는 볼륨이 상주하는 엔드포인트라고 하며 복제된 데이터가 포함된 볼륨을 살펴봐야 합니다. 피어 관계를 사용하면 클러스터와 볼륨이 데이터를 안전하게 교환할 수 있습니다.

SnapMirror는 기본적으로 NetApp ONTAP 컨트롤러에서 실행되며 NetApp HCI 및 SolidFire 클러스터에서 실행되는 Element에 통합되어 있습니다. SnapMirror를 제어하는 로직은 ONTAP 소프트웨어에 상주하므로, 모든 SnapMirror 관계는 조정 작업을 수행하기 위해 적어도 하나의 ONTAP 시스템을 포함해야 합니다. 사용자는 기본적으로 Element UI를 통해 Element와 ONTAP 클러스터 간의 관계를 관리합니다. 그러나 일부 관리 작업은 NetApp ONTAP System Manager에 상주합니다. 사용자는 ONTAP와 Element에서 모두 사용할 수 있는 CLI 및 API를 통해 SnapMirror를 관리할 수도 있습니다.

을 참조하십시오 https://fieldportal.netapp.com/content/616239["TR-4651: NetApp SolidFire SnapMirror 아키텍처 및 구성"^] (로그인 필요).

Element 소프트웨어를 사용하여 클러스터 레벨에서 SnapMirror 기능을 수동으로 활성화해야 합니다. SnapMirror 기능은 기본적으로 비활성화되어 있으며, 새로운 설치 또는 업그레이드의 일부로 자동 활성화되지 않습니다.

SnapMirror를 사용하도록 설정한 후 Element 소프트웨어의 데이터 보호 탭에서 SnapMirror 관계를 생성할 수 있습니다.



== 데이터 보호를 위한 볼륨 스냅샷입니다

볼륨 스냅샷은 나중에 볼륨을 특정 시간으로 복원하는 데 사용할 수 있는 볼륨의 시점 복제본입니다.

스냅숏은 볼륨 클론과 비슷하지만 스냅숏은 볼륨 메타데이터의 복제본이므로 마운트하거나 쓸 수 없습니다. 볼륨 스냅샷을 생성하면 시스템 리소스 및 공간도 소량만 차지하기 때문에 클론 생성보다 스냅샷 생성 속도가 빨라집니다.

스냅샷을 원격 클러스터에 복제하고 이를 볼륨의 백업 복사본으로 사용할 수 있습니다. 이렇게 하면 복제된 스냅샷을 사용하여 볼륨을 특정 시점으로 롤백할 수 있으며 복제된 스냅샷으로부터 볼륨의 클론을 생성할 수도 있습니다.

SolidFire 클러스터에서 외부 오브젝트 저장소 또는 다른 SolidFire 클러스터로 스냅샷을 백업할 수 있습니다. 외부 개체 저장소에 스냅샷을 백업할 때 읽기/쓰기 작업을 허용하는 개체 저장소에 대한 연결이 있어야 합니다.

데이터 보호를 위해 개별 볼륨의 스냅샷 또는 여러 개의 스냅샷을 생성할 수 있습니다.



== 볼륨 클론

단일 볼륨 또는 여러 볼륨의 클론은 데이터의 시점 복사본입니다. 볼륨을 클론하면 시스템에서 볼륨의 스냅샷을 생성한 다음 스냅샷이 참조하는 데이터의 복제본을 생성합니다.

비동기식 프로세스이며, 프로세스에 필요한 시간은 클론 생성 중인 볼륨의 크기와 현재 클러스터 로드에 따라 다릅니다.

클러스터는 한 번에 볼륨당 최대 2개의 클론 요청을 실행하고 한 번에 최대 8개의 활성 볼륨 클론 작업을 지원합니다. 이러한 제한을 초과하는 요청은 나중에 처리할 수 있도록 대기열에 추가됩니다.



== SolidFire 스토리지에 대한 백업 및 복원 프로세스 개요

Amazon S3 또는 OpenStack Swift와 호환되는 2차 오브젝트 저장소뿐만 아니라 다른 SolidFire 스토리지에 볼륨을 백업 및 복원할 수 있습니다.

볼륨을 다음 항목에 백업할 수 있습니다.

* SolidFire 스토리지 클러스터입니다
* Amazon S3 오브젝트 저장소
* OpenStack Swift 오브젝트 저장소


OpenStack Swift 또는 Amazon S3에서 볼륨을 복원할 때 원래 백업 프로세스에서 매니페스트 정보가 필요합니다. SolidFire 스토리지 시스템에서 백업한 볼륨을 복원하는 경우 매니페스트 정보가 필요하지 않습니다.



== 보호 도메인

보호 도메인은 데이터 가용성을 유지하면서 일부 또는 전부에 장애가 발생할 수 있도록 그룹화된 노드 또는 노드 세트입니다. 보호 도메인을 사용하면 스토리지 클러스터가 섀시(섀시 선호도) 또는 전체 도메인(섀시 그룹)의 손실로부터 자동으로 치유됩니다.

보호 도메인 레이아웃은 각 노드를 특정 보호 도메인에 할당합니다.

보호 도메인 수준이라는 두 가지 보호 도메인 레이아웃이 지원됩니다.

* 노드 레벨에서 각 노드는 고유한 보호 도메인에 있습니다.
* 섀시 레벨에서는 섀시를 공유하는 노드만 동일한 보호 도메인에 있습니다.
+
** 섀시 레벨 레이아웃은 노드가 클러스터에 추가될 때 하드웨어에서 자동으로 결정됩니다.
** 각 노드가 별도의 섀시에 있는 클러스터에서는 이 두 레벨이 기능적으로 동일합니다.




수동으로 할 수 있습니다 https://docs.netapp.com/us-en/vcp/vcp_task_clusters_manage.html#set-protection-domain-monitoring["보호 도메인 모니터링을 활성화합니다"] vCenter Server용 NetApp Element 플러그인 사용 노드 또는 섀시 도메인에 따라 보호 도메인 임계값을 선택할 수 있습니다.

새 클러스터를 생성할 때 공유 섀시에 있는 스토리지 노드를 사용하는 경우 보호 도메인 기능을 사용하여 섀시 레벨 장애 보호를 설계할 수 있습니다.

각 노드가 1개 및 1개의 사용자 지정 보호 도메인과 연결되는 사용자 지정 보호 도메인 레이아웃을 정의할 수 있습니다. 기본적으로 각 노드는 동일한 기본 사용자 지정 보호 도메인에 할당됩니다.



== 이중 Helix 고가용성

이중 Helix 데이터 보호는 시스템 내 모든 드라이브에 두 개 이상의 중복 데이터 복사본을 배포하는 복제 방법입니다. “RAID-less” 접근 방식을 통해 시스템은 스토리지 시스템의 모든 레벨에서 동시에 여러 건의 장애를 흡수하고 신속하게 복구할 수 있습니다.

[discrete]
== 자세한 내용을 확인하십시오

* https://www.netapp.com/hybrid-cloud/hci-documentation/["NetApp HCI 리소스 페이지를 참조하십시오"^]
* https://docs.netapp.com/us-en/vcp/index.html["vCenter Server용 NetApp Element 플러그인"^]

