---
sidebar: sidebar 
permalink: docs/concept_hci_clusters.html 
summary: 클러스터는 스토리지 노드의 모음으로 구성됩니다. NetApp HCI 스토리지 클러스터에는 최소 2개의 스토리지 노드가 있어야 합니다. 클러스터는 네트워크에 단일 논리 그룹으로 표시되며, 블록 스토리지로 액세스할 수 있습니다. 
keywords: netapp, hci, storage nodes, clusters, two-node cluster, three-node cluster, 2-node cluster, 3-node cluster 
---
= 클러스터
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
클러스터는 집합적인 방식으로 작동하는 노드 그룹으로, 스토리지 또는 컴퓨팅 리소스를 제공합니다. NetApp HCI 1.8부터는 스토리지 클러스터에 두 개의 노드를 포함할 수 있습니다. 스토리지 클러스터는 네트워크에 단일 논리 그룹으로 표시되며, 그런 다음 블록 스토리지로 액세스할 수 있습니다.

NetApp HCI의 스토리지 계층은 NetApp Element 소프트웨어에 의해 제공되며 관리 계층은 vCenter Server용 NetApp Element 플러그인에서 제공됩니다. 스토리지 노드는 Bond10G 네트워크 인터페이스를 통해 서로 통신하는 드라이브 모음이 포함된 서버입니다. 각 스토리지 노드는 2개의 네트워크, 즉 스토리지와 관리에 연결되며 각 네트워크에는 중복성과 성능을 위한 2개의 독립적인 링크가 있습니다. 각 노드에는 각 네트워크의 IP 주소가 필요합니다. 새 스토리지 노드로 클러스터를 생성하거나 기존 클러스터에 스토리지 노드를 추가하여 스토리지 용량과 성능을 높일 수 있습니다.



== 권한 있는 스토리지 클러스터

신뢰할 수 있는 스토리지 클러스터는 NetApp 하이브리드 클라우드 제어에서 사용자를 인증하는 데 사용하는 스토리지 클러스터입니다.

관리 노드에 스토리지 클러스터가 하나만 있는 경우 신뢰할 수 있는 클러스터입니다. 관리 노드에 둘 이상의 스토리지 클러스터가 있는 경우 이러한 클러스터 중 하나가 권한 있는 클러스터로 할당되고 해당 클러스터의 사용자만 NetApp 하이브리드 클라우드 제어에 로그인할 수 있습니다. 어느 클러스터가 권위 있는 클러스터인지 확인하려면 Get/mnode/about API를 사용할 수 있습니다. 이에 대한 응답으로 token_url 필드의 IP 주소는 권한 있는 스토리지 클러스터의 관리 가상 IP 주소(MVIP)입니다. NetApp 하이브리드 클라우드 제어에 권한 있는 클러스터에 없는 사용자로 로그인하려고 하면 로그인 시도가 실패합니다.

많은 NetApp 하이브리드 클라우드 제어 기능은 여러 스토리지 클러스터에서 작동하도록 설계되었지만 인증과 권한 부여에는 제한이 있습니다. 인증 및 권한 부여에 대한 제한 사항은 권한 있는 클러스터의 사용자가 다른 스토리지 클러스터의 사용자가 아니더라도 NetApp 하이브리드 클라우드 제어에 연결된 다른 클러스터에 대한 작업을 실행할 수 있다는 것입니다. 여러 스토리지 클러스터를 관리하기 전에 권한 있는 클러스터에 정의된 사용자가 동일한 권한을 가진 다른 모든 스토리지 클러스터에 정의되어 있는지 확인해야 합니다.

NetApp 하이브리드 클라우드 제어로 사용자를 관리할 수 있습니다.

여러 스토리지 클러스터를 관리하기 전에 권한 있는 클러스터에 정의된 사용자가 동일한 권한을 가진 다른 모든 스토리지 클러스터에 정의되어 있는지 확인해야 합니다. 을 참조하십시오 link:task_mnode_manage_storage_cluster_assets.html["스토리지 클러스터 자산을 생성하고 관리합니다"] 관리 노드 스토리지 클러스터 자산을 사용하는 방법에 대한 자세한 내용은 섹션을 참조하십시오.



== 고립된 용량

새로 추가된 노드가 전체 클러스터 용량의 50% 이상을 차지하는 경우 이 노드의 일부 용량을 사용할 수 없게 되어 용량 규칙을 준수합니다("고립됨"). 이는 스토리지 용량이 더 추가될 때까지 유지됩니다. 용량 규칙에 불복종하는 매우 큰 노드가 추가되면 이전에 고립된 노드는 더 이상 고립되지 않고 새로 추가된 노드는 고립됩니다. 이러한 상황이 발생하지 않도록 용량을 항상 쌍으로 추가해야 합니다. 노드가 고립되면 적절한 클러스터 장애가 throw됩니다.



== 2노드 스토리지 클러스터

NetApp HCI 1.8부터 스토리지 노드 2개로 스토리지 클러스터를 설정할 수 있습니다.

* 특정 유형의 노드를 사용하여 2노드 스토리지 클러스터를 구성할 수 있습니다. 을 참조하십시오 https://library.netapp.com/ecm/ecm_download_file/ECMLP2865021["NetApp HCI 1.8 릴리스 정보"^].
+

NOTE: 2노드 클러스터의 스토리지 노드는 480GB 및 960GB 드라이브가 있는 노드로 제한되며 노드는 동일한 모델 유형이어야 합니다.

* 2노드 스토리지 클러스터는 대용량 및 고성능 요구사항에 종속되지 않는 워크로드를 가진 소규모 구축에 적합합니다.
* 2개의 스토리지 노드 외에도 2노드 스토리지 클러스터에는 2개의 NetApp HCI Witness Node * 가 포함됩니다.
+

NOTE: 에 대해 자세히 알아보십시오 link:concept_hci_nodes.html["증명선 노드."]

* 2노드 스토리지 클러스터를 3노드 스토리지 클러스터로 확장할 수 있습니다. 3노드 클러스터는 스토리지 노드 장애를 자동으로 복구할 수 있는 기능을 제공하여 복원력을 향상합니다.
* 2노드 스토리지 클러스터는 기존의 4노드 스토리지 클러스터와 동일한 보안 기능을 제공합니다.
* 2노드 스토리지 클러스터는 4노드 스토리지 클러스터와 동일한 네트워크를 사용합니다. NetApp HCI 구축 중에 NetApp 구축 엔진 마법사를 사용하여 네트워크를 설정합니다.




=== 스토리지 클러스터 쿼럼입니다

Element 소프트웨어는 선택한 노드에서 스토리지 클러스터를 생성하며, 이 노드는 클러스터 구성의 복제된 데이터베이스를 유지 관리합니다. 클러스터 복원력을 위해 쿼럼을 유지하려면 클러스터 앙상블에 최소한 3개의 노드가 필요합니다. 2노드 클러스터의 감시 노드는 유효한 앙상블 쿼럼을 형성하기에 충분한 스토리지 노드가 있는지 확인하는 데 사용됩니다. 앙상블 생성을 위해 스토리지 노드가 Witness Node 보다 선호됩니다. 2노드 스토리지 클러스터를 포함하는 최소 3노드 앙상블의 경우 2개의 스토리지 노드와 1개의 Witness 노드가 사용됩니다.


TIP: 스토리지 노드 2개와 Witness 노드 1개가 있는 3노드 앙상블에서 스토리지 노드 1개가 오프라인이 되면 클러스터는 성능 저하 상태가 됩니다. 두 개의 Witness Node 중 한 개만 앙상블에서 활성화할 수 있습니다. 두 번째 Witness Node는 백업 역할을 수행하기 때문에 앙상블에 추가할 수 없습니다. 오프라인 스토리지 노드가 온라인 상태가 되거나 대체 노드가 클러스터에 연결될 때까지 클러스터는 성능 저하 상태를 유지합니다.

Witness Node에 장애가 발생하면 나머지 Witness Node가 앙상블에 가입하여 3노드 앙상블을 형성합니다. 장애가 발생한 Witness 노드를 교체하기 위해 새 Witness 노드를 구축할 수 있습니다.



=== 2노드 스토리지 클러스터에서 자동 복구 및 장애 처리

기존 클러스터에 속한 노드에서 하드웨어 구성 요소에 장애가 발생하면 클러스터가 클러스터의 다른 사용 가능한 노드로 장애가 발생한 구성 요소에 있던 데이터를 재조정합니다. 2노드 스토리지 클러스터에서는 최소 3개의 물리적 스토리지 노드를 사용하여 자동으로 복구할 수 있어야 하므로 이 자동 복구 기능을 사용할 수 없습니다. 2노드 클러스터의 한 노드에 장애가 발생할 경우 2노드 클러스터에서 두 번째 데이터 복사본을 재생성할 필요가 없습니다. 나머지 활성 스토리지 노드의 블록 데이터에 대해 새 쓰기가 복제됩니다. 장애가 발생한 노드가 교체되고 클러스터에 추가되면 데이터가 두 물리적 스토리지 노드 간에 재조정됩니다.



== 3개 이상의 노드가 있는 스토리지 클러스터

2개의 스토리지 노드에서 3개의 스토리지 노드로 확장하면 노드 및 드라이브 장애가 발생할 경우 자동 복구가 가능하지만 추가 용량은 제공되지 않습니다. 을 사용하여 를 확장할 수 있습니다 link:task_hcc_expand_storage.html["NetApp 하이브리드 클라우드 제어 UI"]. 2노드 클러스터에서 3노드 클러스터로 확장할 경우 용량이 고립될 수 있습니다(참조) <<Stranded capacity>>)를 클릭합니다. UI 마법사는 설치 전에 고립된 용량에 대한 경고를 표시합니다. 스토리지 노드 장애 시 앙상블 쿼럼을 유지할 수 있는 단일 Witness Node를 사용할 수 있으며, 두 번째 Witness Node는 대기 상태로 유지됩니다. 3노드 스토리지 클러스터를 4노드 클러스터로 확장하면 용량과 성능이 향상됩니다. 4노드 클러스터에서는 Witness 노드가 더 이상 클러스터 쿼럼을 형성하지 않아도 됩니다. 최대 64개의 컴퓨팅 노드와 40개의 스토리지 노드로 확장할 수 있습니다.



== 자세한 내용을 확인하십시오

* https://www.netapp.com/us/media/tr-4823.pdf["NetApp HCI 2노드 스토리지 클러스터 | TR-4823"^]
* https://docs.netapp.com/us-en/vcp/index.html["vCenter Server용 NetApp Element 플러그인"^]
* http://docs.netapp.com/sfe-122/index.jsp["SolidFire 및 Element 소프트웨어 설명서 센터"^]

