---
sidebar: sidebar 
permalink: docs/concept_rancher_concepts.html 
summary: NetApp HCI에 Rancher를 설치한 후 수행해야 할 작업에 대해 알아보십시오. 
keywords: netapp, hci, rancher, control plane, catalog, cluster, kubernetes 
---
= Rancher on NetApp HCI 개념
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
NetApp HCI의 Rancher와 관련된 기본 개념을 알아봅니다.

* * Rancher 서버 * 또는 * Control plane *: rancher Control Plane(Rancher Control Plane), _ Rancher Server _ 라고도 함, 개발 및 운영 팀에서 사용하는 Kubernetes 클러스터를 프로비저닝, 관리 및 모니터링합니다.
* * 카탈로그 *: 카탈로그는 GitHub 리포지토리 또는 배포 준비가 완료된 애플리케이션으로 채워진 Helm Chart 리포지토리입니다. Rancher는 Helm 차트 카탈로그를 사용하여 애플리케이션을 반복적으로 쉽게 배포할 수 있는 기능을 제공합니다. Rancher는 두 가지 유형의 카탈로그(기본 제공 글로벌 카탈로그 및 사용자 지정 카탈로그)를 포함합니다. Trident는 카탈로그로 배포됩니다. 을 참조하십시오 https://rancher.com/docs/rancher/v2.x/en/helm-charts/legacy-catalogs/["카탈로그에 대한 Rancher 문서"].
* * 관리 클러스터 *: NetApp HCI의 Rancher는 Rancher 관리 클러스터에 3개의 가상 시스템을 구축하며, Rancher, 하이브리드 클라우드 제어 및 vCenter 플러그인을 사용할 수 있습니다. 관리 클러스터 가상 머신은 Rancher 서버, RKE(Rancher Kubernetes Engine) 및 Linux OS를 호스팅합니다.
* * 사용자 클러스터 *: 이러한 다운스트림 Kubernetes 클러스터는 사용자의 앱 및 서비스를 실행합니다. Kubernetes의 Rancher 설치 시 관리 클러스터는 사용자 클러스터와 별개여야 합니다. Rancher 사용자가 Rancher에서 배포하거나 Rancher로 가져오는 모든 클러스터는 사용자 클러스터로 간주됩니다.
* * Rancher 노드 템플릿 *: 하이브리드 클라우드 제어는 Rancher 노드 템플릿을 사용하여 구축을 더 간단하게 만듭니다.
+
을 참조하십시오  https://rancher.com/docs/rancher/v2.x/en/user-settings/node-templates/["노드 템플릿에 대한 Rancher 문서"].





== Trident 소프트웨어 및 영구 스토리지 개념

Kubernetes 네이티브 애플리케이션인 Trident는 Kubernetes 클러스터 내에서 직접 실행됩니다. Trident를 사용하면 Kubernetes 사용자(예: 개발자, 데이터 과학자, Kubernetes 관리자)가 이미 익숙한 표준 Kubernetes 형식으로 영구 스토리지 볼륨을 생성, 관리 및 상호 작용할 수 있습니다. Trident를 사용하면 NetApp 솔루션을 Kubernetes 클러스터에서 영구 볼륨의 주장을 충족할 수 있습니다.

Rancher를 사용하면 영구 볼륨을 사용할 수 있습니다. 영구 볼륨은 특정 POD와 독립적으로 존재하고 수명이 다할 때까지 유지됩니다. Trident를 사용하여 영구 PVC(Volume Claim)를 관리하면 액세스 중인 스토리지의 하위 수준 구현 세부 사항에서 Pod를 생성하는 개발자를 격리할 수 있습니다.

컨테이너화된 애플리케이션에서 영구 볼륨 클레임(PVC) 요청을 실행할 경우, Trident는 NetApp HCI의 NetApp Element 소프트웨어 스토리지 계층에 대해 요청된 매개 변수에 따라 스토리지를 동적으로 프로비저닝합니다.

Trident 카탈로그는 NetApp HCI의 Rancher에 제공되며 사용자 클러스터에서 실행됩니다. NetApp HCI 구현에서 Rancher의 일부로 Rancher 카탈로그에서 Trident 설치 프로그램을 기본적으로 사용할 수 있습니다. 이 카탈로그를 포함하면 사용자 클러스터에 대한 Trident 구축을 간소화할 수 있습니다.

을 참조하십시오 link:task_rancher_trident.html["NetApp HCI에 Rancher가 있는 Trident를 설치합니다"].

자세한 내용은 를 참조하십시오 https://netapp-trident.readthedocs.io/en/stable-v20.10/introduction.html["Trident 문서"].

[discrete]
== 자세한 내용을 확인하십시오

* https://rancher.com/docs/rancher/v2.x/en/overview/architecture/["아키텍처에 대한 Rancher 문서"^]
* https://rancher.com/docs/rancher/v2.x/en/overview/concepts/["Rancher용 Kubernetes 용어"]
* https://www.netapp.com/us/documentation/hci.aspx["NetApp HCI 리소스 페이지를 참조하십시오"^]

