---
sidebar: sidebar 
permalink: docs/hci_prereqs_overview.html 
summary: NetApp HCI 구축 요구사항에 대해 알아보십시오. 
keywords: netapp, hci, deployment, requirements 
---
= NetApp HCI 구축 개요에 대한 요구 사항
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
NetApp HCI는 데이터 센터의 적절한 운영을 위해 특정한 물리적 및 네트워크 요구 사항을 가지고 있습니다. 배포를 시작하기 전에 다음 요구 사항 및 권장 사항을 구현해야 합니다.

NetApp HCI 하드웨어를 수령하기 전에 NetApp 프로페셔널 서비스의 구축 전 워크북에 나와 있는 체크리스트 항목을 완료하십시오. 이 문서에는 성공적인 NetApp HCI 배포를 위해 네트워크 및 환경을 준비하는 데 필요한 작업의 전체 목록이 포함되어 있습니다.

다음은 요구사항 및 구축 전 작업에 대한 링크입니다.

* link:hci_prereqs_required_network_ports.html["네트워크 포트 요구 사항"]
* link:hci_prereqs_network_switch.html["네트워크 및 스위치 요구 사항"]
* link:hci_prereqs_network_cables.html["네트워크 케이블 요구 사항"]
* link:hci_prereqs_ip_address.html["IP 주소 요구 사항"]
* link:hci_prereqs_network_configuration.html["네트워크 구성"]
* link:hci_prereqs_timekeeping.html["DNS 및 시간 표시 요구 사항"]
* link:hci_prereqs_environmental.html["환경 요구 사항"]
* link:hci_prereqs_protection_domains.html["보호 도메인"]
* link:hci_prereqs_witness_nodes.html["노드 2개 스토리지 클러스터의 노드 리소스 요구 사항"]




== 자세한 내용을 확인하십시오

https://docs.netapp.com/us-en/vcp/index.html["vCenter Server용 NetApp Element 플러그인"^]
