---
sidebar: sidebar 
permalink: docs/hci_prereqs_network_switch.html 
summary: 이 NetApp HCI 버전의 새로운 기능에 대해 알아보십시오. 
keywords: netapp, hci, network, switch, requirements 
---
= 네트워크 및 스위치 요구 사항
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/
:keywords: netapp, hci, network, switch, requirements


[role="lead"]
NetApp HCI에 사용하는 스위치는 성공적인 배포를 위해 특정 구성이 필요합니다. 사용자 환경에 다음 각 요구 사항을 구현하는 방법에 대한 자세한 내용은 스위치 설명서를 참조하십시오.

NetApp HCI 배포에는 다음 트래픽 유형에 대해 하나씩 최소 3개의 네트워크 세그먼트가 필요합니다.

* 관리
* 마이그레이션 했습니다
* 스토리지/데이터


NetApp H 시리즈 컴퓨팅 및 스토리지 노드 모델과 계획된 케이블 연결 구성에 따라 별도의 스위치를 사용하여 이러한 네트워크를 물리적으로 분리하거나 VLAN을 사용하여 네트워크를 논리적으로 분리할 수 있습니다. 그러나 대부분의 구축 환경에서는 VLAN을 사용하여 이러한 네트워크(및 기타 추가 가상 머신 네트워크)를 논리적으로 분리해야 합니다.

컴퓨팅 및 스토리지 노드는 구축 전, 구축 도중, 이후에 통신할 수 있어야 합니다. 스토리지 및 컴퓨팅 노드에 대해 별도의 관리 네트워크를 구축하는 경우 이러한 관리 네트워크가 이러한 네트워크 간 경로를 가지고 있는지 확인하십시오. 이러한 네트워크에는 게이트웨이가 할당되어 있어야 하며 게이트웨이 사이에 경로가 있어야 합니다. 각 새 노드에 노드와 관리 네트워크 간의 통신을 용이하게 하기 위한 게이트웨이가 할당되어 있는지 확인합니다.

NetApp HCI에는 다음과 같은 스위치 요구 사항이 있습니다.

* NetApp HCI 노드에 연결된 모든 스위치 포트는 스패닝 트리 에지 포트로 구성되어야 합니다.
+
** Cisco 스위치에서 스위치 모델, 소프트웨어 버전 및 포트 유형에 따라 다음 명령 중 하나를 사용하여 이 작업을 수행할 수 있습니다.
+
*** 패닝 트리 포트형 모서리
*** 패닝 트리 포트형 에지 트렁크
*** 패닝 트리 portfast
*** 패닝 트리 portfast 트렁크


** Mellanox 스위치에서 '패닝 트리 포트 유형 에지' 명령을 사용하여 이 작업을 수행할 수 있습니다.


* NetApp HCI 노드에는 대역외 관리를 제외한 모든 네트워크 기능을 위한 중복 포트가 있습니다. 최상의 복원력을 위해 이러한 포트를 두 스위치 간에 분할하여 기존 계층 아키텍처 또는 계층 2 스파인/리프 아키텍처로 중복 업링크를 지원합니다.
* 스토리지, 가상 머신 및 vMotion 트래픽을 처리하는 스위치는 포트당 10GbE 이상의 속도를 지원해야 합니다(포트당 최대 25GbE 지원).
* 관리 트래픽을 처리하는 스위치는 포트당 1GbE 이상의 속도를 지원해야 합니다.
* 스토리지 및 vMotion 트래픽을 처리하는 스위치 포트에서 점보 프레임을 구성해야 합니다. 호스트가 성공적인 설치를 위해 9000바이트 패킷을 엔드투엔드로 보낼 수 있어야 합니다.
* 각 호스트의 관리 NIC 포트가 구성된 MTU 크기를 허용하도록 관리 네트워크 스위치 포트를 구성해야 합니다. 예를 들어, 호스트 관리 네트워크 포트에서 MTU 크기 1750바이트를 사용하는 경우 관리 네트워크 스위치 포트를 최소 1750바이트의 MTU를 허용하도록 구성해야 합니다(관리 네트워크에는 MTU 9000바이트가 필요하지 않음). MTU 설정은 정합성이 보장된 종단 간 설정이어야 합니다
* 모든 스토리지와 컴퓨팅 노드 간의 왕복 네트워크 지연 시간이 2ms를 초과해서는 안 됩니다.


모든 NetApp HCI 노드는 전용 관리 포트를 통해 추가적인 대역외 관리 기능을 제공합니다. NetApp H300S, H300E, H500S, H500E, H700S, H700E 및 H410C 노드도 포트 A를 통한 IPMI 액세스를 허용합니다 모범 사례로서, 사용자 환경의 모든 노드에 대해 대역외 관리를 구성하여 NetApp HCI의 원격 관리를 용이하게 해야 합니다.

[discrete]
== 자세한 내용을 확인하십시오

* https://www.netapp.com/hybrid-cloud/hci-documentation/["NetApp HCI 리소스 페이지를 참조하십시오"^]
* https://docs.netapp.com/us-en/vcp/index.html["vCenter Server용 NetApp Element 플러그인"^]

