---
sidebar: sidebar 
permalink: docs/rancher_prereqs_overview.html 
summary: NetApp HCI 설치 시 성공적으로 목장을 설치하기 위한 요구 사항에 대해 알아보십시오. 
keywords: netapp, hci, Rancher, install, installation, requirements 
---
= NetApp HCI의 Rancher에 대한 요구 사항
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
NetApp HCI에 Rancher를 설치하기 전에 환경 및 NetApp HCI 시스템이 이러한 요구 사항을 충족하는지 확인하십시오.


NOTE: 잘못된 정보(예: 잘못된 Rancher 서버 FQDN)로 NetApp HCI에 Rancher를 실수로 배포하는 경우, Rancher 서버를 제거하고 다시 배포하지 않고도 배포를 수정할 수 없습니다. NetApp HCI 인스턴스에서 Rancher를 제거한 다음 NetApp 하이브리드 클라우드 제어 UI에서 NetApp HCI에 Rancher를 재배포해야 합니다. 을 참조하십시오 link:task_rancher_remove_deployment.html["NetApp HCI에서 목장 설치를 제거합니다"^] 를 참조하십시오.



== 노드 요구 사항

* NetApp HCI 시스템에 컴퓨팅 노드가 3개 이상 있는지 확인합니다. 이 노드는 전체 복원력을 위해 필요합니다. NetApp HCI의 Rancher는 스토리지 전용 구성에서 지원되지 않습니다.
* NetApp HCI 구축 시 Rancher에 사용할 데이터 저장소의 사용 가능한 공간이 60GB 이상인지 확인합니다.
* NetApp HCI 클러스터에서 관리 서비스 버전 2.17 이상이 실행되고 있는지 확인합니다.




=== 노드 세부 정보

NetApp HCI의 Rancher는 3노드 관리 클러스터를 구축합니다.

모든 노드의 특징은 다음과 같습니다.

[cols="15,15, 15"]
|===
| vCPU | RAM(GB) | 디스크(GB) 


| 2 | 8 | 20 
|===


== 네트워크 요구 사항

* NetApp HCI 관리 클러스터에 Rancher를 구축할 네트워크가 관리 노드 관리 네트워크로 연결되는 경로를 가지고 있는지 확인합니다.
* NetApp HCI의 Rancher는 컨트롤 플레인(Rancher 서버) 및 사용자 클러스터에 대해 DHCP 주소를 지원하지만 프로덕션 환경에 정적 IP 주소를 사용하는 것이 좋습니다. 운영 환경에 배포하는 경우 필요한 정적 IP 주소를 할당했는지 확인합니다.
+
** Rancher 서버에는 3개의 정적 IP 주소가 필요합니다.
** 각 사용자 클러스터에는 클러스터의 노드만큼 많은 정적 IP 주소가 필요합니다. 예를 들어, 4개의 노드가 있는 사용자 클러스터에는 4개의 정적 IP 주소가 필요합니다.
** Rancher 컨트롤 플레인 또는 사용자 클러스터에 대해 DHCP 주소 지정을 사용하려는 경우 DHCP 임대 기간이 최소 24시간인지 확인합니다.


* NetApp HCI의 Rancher에 대한 인터넷 액세스를 활성화하기 위해 HTTP 프록시를 사용해야 하는 경우 관리 노드에 대한 사전 배포 변경을 수행해야 합니다. SSH를 사용하여 관리 노드에 로그인하고 에 따릅니다 https://docs.docker.com/config/daemon/systemd/#httphttps-proxy["지침"^] Docker에 대한 프록시 설정을 수동으로 업데이트하려면 Docker 설명서를 참조하십시오.
* 배포 중에 프록시 서버를 활성화하고 구성하는 경우 다음과 같은 IP 주소 범위 및 도메인이 Rancher 서버 nocProxy 설정에 자동으로 추가됩니다.
+
[listing]
----
127.0.0.0/8, 10.0.0.0/8, 172.16.0.0/12, 192.168.0.0/16, .svc, .cluster.local
----
* 관리 노드가 DNS를 사용하여 IP 주소에 대한 호스트 이름 '<Any IP address>.nip.io'를 확인할 수 있는지 확인합니다. 배포 중에 사용되는 DNS 공급자입니다. 관리 노드가 이 URL을 확인할 수 없으면 배포가 실패합니다.
* 필요한 각 정적 IP 주소에 대해 DNS 레코드를 설정했는지 확인합니다.




== VMware vSphere 요구 사항

* 사용 중인 VMware vSphere 인스턴스가 버전 6.5, 6.7 또는 7.0인지 확인합니다.
* vSphere 표준 스위치(VSS) 네트워킹 구성을 사용할 수 있지만, 그렇게 할 경우, Rancher VM에 사용되는 가상 스위치와 물리적 호스트가 일반 VM에 대해 보장하는 것과 동일한 방식으로 동일한 포트 그룹에 모두 액세스할 수 있는지 확인하십시오.




== 구축 고려 사항

다음 고려 사항을 검토할 수 있습니다.

* 구축 유형
+
** 데모 배포
** 운영 구축


* Rancher FQDN



TIP: NetApp HCI의 Rancher는 일부 유형의 네트워크 로드 밸런싱을 구성하지 않는 한 노드 장애에 대한 복원력이 없습니다. 간단한 솔루션으로 Rancher 서버에 예약된 세 개의 정적 IP 주소에 대해 라운드 로빈 DNS 항목을 생성합니다. 이러한 DNS 항목은 구축이 완료되면 Rancher 웹 UI를 제공하는 Rancher 서버 호스트에 액세스하는 데 사용할 Rancher 서버 FQDN으로 확인되어야 합니다.



=== 구축 유형

다음과 같은 방법으로 NetApp HCI에 Rancher를 구축할 수 있습니다.

* * 데모 배포 *: 대상 배포 환경에서 DHCP를 사용할 수 있고 NetApp HCI 기능을 기반으로 Rancher를 시연하려는 경우 DHCP 배포가 가장 적합합니다.
+
이 구축 모델에서는 관리 클러스터의 3개 노드 각각에서 Rancher UI에 액세스할 수 있습니다.

+
조직에서 DHCP를 사용하지 않는 경우에도 배포 전에 할당된 네 개의 고정 IP 주소를 사용하여 이 작업을 수행할 수 있습니다. 이는 프로덕션 배포에 대해 수행할 수 있는 것과 비슷합니다.

* * 프로덕션 배포 *: 대상 배포 환경에서 DHCP를 사용할 수 없거나 프로덕션 배포의 경우 배포 전 작업이 약간 더 필요합니다. 첫 번째 단계는 3개의 연속 IP 주소를 얻는 것입니다. 배포 중에 첫 번째 를 입력합니다.
+
운영 환경에 L4 로드 밸런싱 또는 라운드 로빈 DNS 구성을 사용하는 것이 좋습니다. 이 경우 네 번째 IP 주소와 DNS 구성에 별도의 항목이 필요합니다.

+
** * L4 로드 밸런싱 *: 이 기술은 nginx와 같은 애플리케이션을 호스팅하는 가상 머신 또는 컨테이너가 관리 클러스터의 3개 노드에 요청을 분산하도록 구성된 기술입니다.
** * 라운드 로빈 DNS *: 관리 클러스터를 구성하는 세 호스트 간에 요청을 회전하는 DNS 시스템에서 단일 호스트 이름을 구성하는 기술입니다.






=== Rancher FQDN

설치를 완료하려면 설치 완료 후 Rancher UI가 제공되는 호스트의 FQDN(정규화된 도메인 이름)을 포함하는 Rancher URL을 할당해야 합니다.

모든 경우 브라우저에서 https 프로토콜(포트 443)을 통해 Rancher UI에 액세스할 수 있습니다.

운영 배포에는 관리 클러스터 노드 전체에 걸쳐 로드 밸런싱을 수행하도록 구성된 FQDN이 필요합니다. FQDN 및 로드 밸런싱을 사용하지 않으면 환경의 복원력이 없으며 데모 환경에만 적합합니다.



== 필수 포트

공식 * Rancher Nodes * 섹션의 "RKE의 Rancher Server Node용 포트" 섹션에 있는 포트 목록이 있는지 확인합니다 https://rancher.com/docs/rancher/v2.x/en/installation/requirements/ports/#ports-for-rancher-server-nodes-on-rke["Rancher 문서"^] Rancher 서버를 실행 중인 노드와 방화벽 구성에서 열립니다.



== 필요한 URL입니다

Rancher 컨트롤 플레인이 있는 호스트에서 다음 URL을 액세스할 수 있어야 합니다.

|===
| URL | 설명 


| https://charts.jetstack.io/[] | Kubernetes 통합 


| https://releases.rancher.com/server-charts/stable[] | Rancher 소프트웨어 다운로드 


| https://entropy.ubuntu.com/[] | 난수 생성을 위한 Ubuntu 엔트로피 서비스 


| https://raw.githubusercontent.com/vmware/cloud-init-vmware-guestinfo/v1.3.1/install.sh[] | VMware 게스트 추가 


| https://download.docker.com/linux/ubuntu/gpg[] | Docker Ubuntu GPG 공개 키 


| https://download.docker.com/linux/ubuntu[] | Docker 다운로드 링크 


| https://hub.docker.com/[] | NetApp 하이브리드 클라우드 제어를 위한 Docker Hub 를 참조하십시오 
|===