---
permalink: mnode/reference_change_mnode_default_ssl_certificate.html 
sidebar: sidebar 
keywords: ssl certificate, SSL, private key, self-signed, cluster, nodes, user-defined certificate, API, change default certificate, certificate, Element API, mnode 
summary: NetApp Element API를 사용하여 클러스터에 있는 스토리지 노드의 기본 SSL 인증서 및 개인 키를 변경할 수 있습니다. 
---
= 관리 노드의 기본 SSL 인증서를 변경합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
NetApp Element API를 사용하여 관리 노드의 기본 SSL 인증서 및 개인 키를 변경할 수 있습니다.

관리 노드를 구성하면 고유한 자체 서명된 SSL(Secure Sockets Layer) 인증서와 Element UI, 노드별 UI 또는 API를 통해 모든 HTTPS 통신에 사용되는 개인 키가 생성됩니다. Element 소프트웨어는 자체 서명된 인증서뿐만 아니라 신뢰할 수 있는 CA(인증 기관)에서 발급 및 확인되는 인증서도 지원합니다.

다음 API 메소드를 사용하여 기본 SSL 인증서에 대한 자세한 정보를 얻고 변경할 수 있습니다.

* * GetNodeSSLCertificate *
+
를 사용할 수 있습니다 https://docs.netapp.com/us-en/element-software/api/reference_element_api_getnodesslcertificate.html["GetNodeSSLCertificate 메서드"^] 모든 인증서 세부 정보를 포함하여 현재 설치된 SSL 인증서에 대한 정보를 검색합니다.

* * SetNodeSSLCertificate *
+
를 사용할 수 있습니다 https://docs.netapp.com/us-en/element-software/api/reference_element_api_setnodesslcertificate.html["SetNodeSSLCertificate 메서드"^] 클러스터 및 노드별 SSL 인증서를 사용자가 제공하는 인증서 및 개인 키로 설정합니다. 시스템은 유효하지 않은 인증서가 적용되지 않도록 인증서와 개인 키의 유효성을 검사합니다.

* * RemoveNodeSSLCertificate * 를 선택합니다
+
여기 https://docs.netapp.com/us-en/element-software/api/reference_element_api_removenodesslcertificate.html["RemoveNodeSSLCertificate 메서드"^] 현재 설치된 SSL 인증서 및 개인 키를 제거합니다. 그런 다음 클러스터가 새로운 자체 서명된 인증서와 개인 키를 생성합니다.





== 자세한 내용을 확인하십시오

* https://docs.netapp.com/us-en/element-software/storage/reference_post_deploy_change_default_ssl_certificate.html["Element 소프트웨어 기본 SSL 인증서를 변경합니다"^]
* https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Software/Element_Software/What_are_the_requirements_around_setting_custom_SSL_certificates_in_Element_Software%3F["Element 소프트웨어에서 사용자 정의 SSL 인증서를 설정하는 데 필요한 요구 사항은 무엇입니까?"^]
* https://www.netapp.com/data-storage/solidfire/documentation["SolidFire 및 요소 리소스 페이지입니다"^]
* https://docs.netapp.com/us-en/vcp/index.html["vCenter Server용 NetApp Element 플러그인"^]

