---
sidebar: sidebar 
permalink: docs/reference_hcc_config_maximums.html 
summary: NetApp 하이브리드 클라우드 제어에는 특정 기능이 있으며, 이러한 기능을 바탕으로 운영하도록 권장합니다. 
keywords: netapp, hci, HCC, configuration, capabilities, limits, maximums 
---
= NetApp 하이브리드 클라우드 제어 구성 최대 한도
:allow-uri-read: 


[role="lead"]
NetApp HCI에 포함된 NetApp 하이브리드 클라우드 제어기를 사용하면 컴퓨팅 라이프사이클과 스토리지 관리를 간소화할 수 있습니다. NetApp HCI 및 NetApp SolidFire 스토리지 클러스터의 스토리지 노드에 대한 Element 소프트웨어 업그레이드뿐만 아니라 NetApp HCI의 NetApp HCI 컴퓨팅 노드에 대한 펌웨어 업그레이드를 지원합니다. 이 기능은 NetApp HCI의 관리 노드에서 기본적으로 사용할 수 있습니다.

NetApp 하이브리드 클라우드 제어는 NetApp HCI 설치에서 NetApp이 제공한 하드웨어 및 소프트웨어 구성요소를 커뮤니케이션할 뿐만 아니라 VMware vCenter와 같은 고객 환경에서 타사 구성요소와 상호 작용합니다. NetApp에서는 NetApp 하이브리드 클라우드 컨트롤의 기능과 고객 환경에서 특정 규모까지 이러한 타사 구성 요소와의 상호 작용에 대해 설명합니다. NetApp 하이브리드 클라우드 제어를 최적의 상태로 유지하려면 최대 구성 범위 내에서 유지하는 것이 좋습니다.

이 테스트된 최대값을 초과하면 느린 사용자 인터페이스 및 API 응답 또는 기능을 사용할 수 없는 것과 같은 NetApp 하이브리드 클라우드 제어와 관련된 문제가 발생할 수 있습니다. 구성 최대값을 초과하여 구성된 환경에서 NetApp 하이브리드 클라우드 제어를 통해 제품 지원을 위해 NetApp에 문의할 경우, NetApp Support에서 구성 내용을 최대 문서로 변경할지 묻습니다.

.구성 최대
NetApp 하이브리드 클라우드 제어에서는 최대 500개의 NetApp 컴퓨팅 노드를 통해 VMware vSphere 환경을 지원합니다. 클러스터당 40개의 스토리지 노드로 최대 20개의 NetApp Element 소프트웨어 기반 스토리지 클러스터를 지원합니다.
