---
sidebar: sidebar 
permalink: docs/task_nde_hci_power_off_storage.html 
summary: NetApp HCI 컴퓨팅 노드의 전원을 끄는 방법에 대해 알아보십시오. 
keywords: netapp, hci, netapp deployment engine, deployment, vsphere 
---
= NetApp HCI 시스템의 스토리지 리소스 전원을 끕니다
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/
:keywords: netapp, hci, netapp deployment engine, deployment, vsphere


[role="lead"]
NetApp HCI에 대한 스토리지 리소스의 전원을 끌 경우 스토리지 노드를 제대로 중지하려면 'Shutdown' Element API 메소드를 사용해야 합니다.

.단계
컴퓨팅 리소스의 전원을 끈 후 웹 브라우저를 사용하여 NetApp HCI 스토리지 클러스터의 모든 노드를 종료합니다.

. 스토리지 클러스터에 로그인하여 올바른 MVIP에 연결되어 있는지 확인합니다.
. (선택 사항) 호스트의 모든 입출력 작업이 중지되었는지 확인합니다.
+
.. 사용 중인 하나 이상의 하이퍼바이저에 대해 적절한 명령을 사용하여 호스트 측에서 입출력을 중지합니다.
.. 클러스터 UI에서 * Reporting * > * Overview * 를 선택합니다. "클러스터 입력/출력" 그래프에는 활동이 없어야 합니다.
.. 모든 I/O 작업이 중지된 후 클러스터를 종료하기 전에 20분 동안 기다립니다.


. iSCSI 세션 수가 0인지 확인합니다.
. 클러스터 > 노드 > 액티브 * 로 이동하고 클러스터의 모든 활성 노드에 대한 노드 ID를 기록합니다.
. NetApp HCI 스토리지 클러스터의 전원을 끄려면 웹 브라우저를 열고 다음 URL을 사용하여 전원 끄기 및 중지 절차를 호출합니다(여기서) `{MVIP}` 는 NetApp HCI 스토리지 시스템의 관리 IP 주소이며 `nodes=[]` 어레이에는 4단계에서 기록한 노드 ID가 포함됩니다. 예를 들면 다음과 같습니다.
+
[listing]
----
https://{MVIP}/json-rpc/1.0?method=Shutdown&nodes=[1,2,3,4]&option=halt
----
+

NOTE: 저장된 URL에서 나중에 명령을 실행하지 않도록 익명 창에서 명령을 실행할 수 있습니다.

. 클러스터 관리자 사용자 이름 및 암호를 입력합니다.
. 모든 스토리지 클러스터 노드가 API 결과의 '성공' 섹션에 포함되어 있는지 확인하여 API 호출이 성공적으로 반환되었는지 확인합니다.
+
모든 NetApp HCI 스토리지 노드의 전원을 성공적으로 껐습니다.

. "뒤로" 버튼을 선택하지 않고 API 호출이 반복되지 않도록 브라우저 또는 탭을 닫습니다.


[NOTE]
====
클러스터를 재시작할 때 모든 노드가 온라인 상태인지 확인하려면 특정 단계를 수행해야 합니다.

. 모든 Critical severity 및 를 확인합니다 `volumesOffline` 클러스터 장애가 해결되었습니다.
. 클러스터가 안정될 때까지 10~15분 정도 기다립니다.
. 데이터 액세스를 위해 호스트를 시작합니다.


노드 전원을 켜고 상태가 양호한지 확인하는 데 더 많은 시간을 할애하려면 기술 지원 부서에 문의하여 불필요한 입력 용지함 동기화를 방지하기 위해 데이터 동기화를 지연하는 방법에 대해 문의하십시오.

====


== 자세한 내용을 확인하십시오

* link:firmware_driver_versions.html["NetApp HCI 스토리지 노드의 NetApp HCI 및 펌웨어 버전에 대해 지원되는 펌웨어 및 ESXi 드라이버 버전"]

