---
sidebar: sidebar 
permalink: docs/task_hcc_qos_policies.html 
summary: 스토리지 클러스터의 볼륨에 적용할 QoS 정책을 설정 및 수정할 수 있습니다. 
keywords: netapp, qos policy, quality of service, qos policies, volumes, element 
---
= 볼륨 QoS 정책 생성 및 관리
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
QoS(서비스 품질) 정책을 사용하면 여러 볼륨에 적용할 수 있는 표준화된 서비스 품질 설정을 생성하여 저장할 수 있습니다. QoS 정책을 사용하려면 선택한 클러스터가 Element 10.0 이상이어야 합니다. 그렇지 않으면 QoS 정책 기능을 사용할 수 없습니다.


NOTE: 사용에 대한 자세한 내용은 NetApp HCI 개념 내용 을 참조하십시오 link:concept_hci_performance.html#qos-policies["QoS 정책"] 개별 볼륨 대신 link:concept_hci_performance.html["QoS를 참조하십시오"].

NetApp 하이브리드 클라우드 제어를 사용하면 다음 작업을 완료하여 QoS 정책을 생성하고 관리할 수 있습니다.

* <<Create a QoS policy>>
* <<Apply a QoS policy to a volume>>
* <<Change the QoS policy assignment of a volume>>
* <<Edit a QoS policy>>
* <<Delete a QoS policy>>




== QoS 정책을 생성합니다

QoS 정책을 생성한 후 동일한 성능이 필요한 볼륨에 적용할 수 있습니다.


NOTE: QoS 정책을 사용하는 경우 볼륨에 대해 사용자 지정 QoS를 사용하지 마십시오. 사용자 지정 QoS는 볼륨 QoS 설정에 대한 QoS 정책 값을 재정의하고 조정합니다.

.단계
. NetApp 하이브리드 클라우드 제어에 NetApp HCI 또는 Element 스토리지 클러스터 관리자 자격 증명을 제공하여 로그인하십시오.
. 대시보드에서 스토리지 클러스터의 메뉴를 확장합니다.
. 스토리지 > 볼륨 * 을 선택합니다.
. QoS Policies * 탭을 클릭합니다.
. Create Policy * 를 클릭합니다.
. 정책 이름 * 을 입력합니다.
+

TIP: 이름 지정 모범 사례를 설명합니다. 이 기능은 사용자 환경에서 여러 클러스터 또는 vCenter Server를 사용하는 경우에 특히 중요합니다.

. 최소 IOPS, 최대 IOPS 및 버스트 IOPS 값을 입력합니다.
. QoS 정책 생성 * 을 클릭합니다.
+
정책에 대한 시스템 ID가 생성되고 QoS 정책 페이지에 할당된 QoS 값이 있는 정책이 나타납니다.





== 볼륨에 QoS 정책을 적용합니다

NetApp 하이브리드 클라우드 제어를 사용하여 기존 QoS 정책을 볼륨에 할당할 수 있습니다.

할당하려는 QoS 정책이 입니다 <<Create a QoS policy,작성됨>>.

이 작업에서는 설정을 변경하여 개별 볼륨에 QoS 정책을 할당하는 방법을 설명합니다. NetApp 하이브리드 클라우드 컨트롤의 최신 버전에는 두 개 이상의 볼륨에 대한 대량 할당 옵션이 없습니다. 대량 할당 기능이 향후 릴리즈에서 제공될 때까지 Element 웹 UI 또는 vCenter 플러그인 UI를 사용하여 QoS 정책을 대량으로 할당할 수 있습니다.

.단계
. NetApp 하이브리드 클라우드 제어에 NetApp HCI 또는 Element 스토리지 클러스터 관리자 자격 증명을 제공하여 로그인하십시오.
. 대시보드에서 스토리지 클러스터의 메뉴를 확장합니다.
. 스토리지 > 볼륨 * 을 선택합니다.
. 수정할 볼륨 옆의 * Actions * 메뉴를 클릭합니다.
. 결과 메뉴에서 * Edit * 를 선택합니다.
. 대화 상자에서 * QoS 정책 할당 * 을 활성화하고 드롭다운 목록에서 QoS 정책을 선택하여 선택한 볼륨에 적용합니다.
+

NOTE: QoS를 할당하면 이전에 적용된 모든 개별 볼륨 QoS 값이 재정의됩니다.

. 저장 * 을 클릭합니다.
+
할당된 QoS 정책이 있는 업데이트된 볼륨이 개요 페이지에 나타납니다.





== 볼륨의 QoS 정책 할당을 변경합니다

볼륨에서 QoS 정책 할당을 제거하거나 다른 QoS 정책 또는 사용자 지정 QoS를 선택할 수 있습니다.

수정하려는 볼륨은 입니다 <<Apply a QoS policy to a volume,할당됨>> QoS 정책.

.단계
. NetApp 하이브리드 클라우드 제어에 NetApp HCI 또는 Element 스토리지 클러스터 관리자 자격 증명을 제공하여 로그인하십시오.
. 대시보드에서 스토리지 클러스터의 메뉴를 확장합니다.
. 스토리지 > 볼륨 * 을 선택합니다.
. 수정할 볼륨 옆의 * Actions * 메뉴를 클릭합니다.
. 결과 메뉴에서 * Edit * 를 선택합니다.
. 대화 상자에서 다음 중 하나를 실행합니다.
+
** QoS 정책 * 할당 * 을 비활성화하고 개별 볼륨 QoS에 대한 * 최소 IOPS *, * 최대 IOPS * 및 * 버스트 IOPS * 값을 수정합니다.
+

NOTE: QoS 정책을 사용하지 않도록 설정할 경우 별도의 수정 없이 볼륨에 기본 QoS IOPS 값이 사용됩니다.

** 드롭다운 목록에서 선택한 볼륨에 적용할 다른 QoS 정책을 선택합니다.


. 저장 * 을 클릭합니다.
+
업데이트된 볼륨이 개요 페이지에 나타납니다.





== QoS 정책을 편집합니다

기존 QoS 정책의 이름을 변경하거나 정책과 연결된 값을 편집할 수 있습니다. QoS 정책 성능 값을 변경하면 정책에 연결된 모든 볼륨의 QoS에 영향을 줍니다.

.단계
. NetApp 하이브리드 클라우드 제어에 NetApp HCI 또는 Element 스토리지 클러스터 관리자 자격 증명을 제공하여 로그인하십시오.
. 대시보드에서 스토리지 클러스터의 메뉴를 확장합니다.
. 스토리지 > 볼륨 * 을 선택합니다.
. QoS Policies * 탭을 클릭합니다.
. 수정하려는 QoS 정책 옆의 * Actions * 메뉴를 클릭합니다.
. 편집 * 을 클릭합니다.
. QoS 정책 편집 * 대화 상자에서 다음 중 하나 이상을 변경합니다.
+
** * 이름 *: QoS 정책에 대한 사용자 정의 이름입니다.
** * 최소 IOPS *: 볼륨에 대해 보장된 최소 IOPS 수입니다. 기본값 = 50.
** * 최대 IOPS *: 볼륨에 허용되는 최대 IOPS 수입니다. 기본값 = 15,000.
** * 버스트 IOPS *: 짧은 기간 동안 볼륨에 허용되는 최대 IOPS 수입니다. 기본값 = 15,000.


. 저장 * 을 클릭합니다.
+
업데이트된 QoS 정책이 QoS 정책 페이지에 나타납니다.

+

TIP: 정책에 대해 * Active Volumes * 열의 링크를 클릭하면 해당 정책에 할당된 볼륨의 필터링된 목록이 표시됩니다.





== QoS 정책을 삭제합니다

QoS 정책이 더 이상 필요하지 않은 경우 삭제할 수 있습니다. QoS 정책을 삭제할 경우 정책에 할당된 모든 볼륨은 정책에 의해 이전에 정의된 QoS 값을 유지하고 개별 볼륨 QoS로 유지합니다. 삭제된 QoS 정책과의 연결이 제거됩니다.

.단계
. NetApp 하이브리드 클라우드 제어에 NetApp HCI 또는 Element 스토리지 클러스터 관리자 자격 증명을 제공하여 로그인하십시오.
. 대시보드에서 스토리지 클러스터의 메뉴를 확장합니다.
. 스토리지 > 볼륨 * 을 선택합니다.
. QoS Policies * 탭을 클릭합니다.
. 수정하려는 QoS 정책 옆의 * Actions * 메뉴를 클릭합니다.
. 삭제 * 를 클릭합니다.
. 작업을 확인합니다.


[discrete]
== 자세한 내용을 확인하십시오

* https://docs.netapp.com/us-en/vcp/index.html["vCenter Server용 NetApp Element 플러그인"^]
* https://docs.netapp.com/us-en/element-software/index.html["SolidFire 및 Element 소프트웨어 설명서"^]

