---
sidebar: sidebar 
permalink: docs/task_hcc_activeiq.html 
summary: SolidFire Active IQ를 사용하여 클러스터 상태를 모니터링할 수 있습니다. 
keywords: netapp, hci, on premise, activeiq, active iq, cluster, performance 
---
= SolidFire Active IQ로 성능, 용량, 클러스터 상태를 모니터링합니다
:allow-uri-read: 


[role="lead"]
SolidFire Active IQ를 사용하여 클러스터의 이벤트, 성능 및 용량을 모니터링할 수 있습니다. NetApp 하이브리드 클라우드 제어 대시보드에서 SolidFire Active IQ에 액세스할 수 있습니다.

* 시작하기 전에 *

* 이 서비스를 이용하려면 NetApp Support 계정이 있어야 합니다.
* 관리 노드 REST API를 사용하려면 권한이 있어야 합니다.
* 버전 12.0 이상을 실행하는 관리 노드를 배포했습니다.
* 클러스터 버전이 NetApp Element 소프트웨어 12.0 이상을 실행하고 있습니다.
* 인터넷에 액세스할 수 있습니다. Active IQ Collector 서비스는 어두운 사이트에서 사용할 수 없습니다.


* 이 작업에 대한 정보 * 클러스터 전체 통계의 기록 보기를 지속적으로 업데이트할 수 있습니다. 클러스터에서 지정된 이벤트, 임계값 또는 메트릭에 대한 알림을 설정하여 알림을 빠르게 처리할 수 있습니다.

일반 지원 계약의 일부로서, NetApp Support는 이 데이터를 모니터링하고 잠재적인 시스템 문제를 경고합니다.

* 단계 *

. 웹 브라우저에서 관리 노드의 IP 주소를 엽니다. 예를 들면 다음과 같습니다.
+
[listing]
----
https://<ManagementNodeIP>
----
. NetApp 하이브리드 클라우드 제어에 NetApp HCI 스토리지 클러스터 관리자 자격 증명을 제공하여 로그인하십시오.
. 대시보드 에서 오른쪽 위에 있는 메뉴를 선택합니다.
. Active IQ 보기 * 를 선택합니다.
+
를 클릭합니다 link:https://activeiq.solidfire.com["SolidFire Active IQ 대시보드"^] 나타납니다.

. SolidFire Active IQ에 대한 자세한 내용은 를 참조하십시오 https://docs.netapp.com/us-en/solidfire-active-iq/index.html["SolidFire Active IQ 문서"^].
+
오른쪽 상단의 메뉴 아이콘을 선택하고 * Documentation * 을 선택하여 대시보드에서 SolidFire Active IQ 설명서에 액세스할 수도 있습니다.

. SolidFire Active IQ 인터페이스에서 NetApp HCI 컴퓨팅 및 스토리지 노드가 Active IQ에 원격 측정을 올바르게 보고하는지 확인합니다.
+
.. NetApp HCI를 둘 이상 설치한 경우 * 클러스터 선택 * 을 선택하고 목록에서 클러스터를 선택합니다.
.. 왼쪽 탐색 창에서 * 노드 * 를 선택합니다.


. 목록에 노드가 없는 경우 NetApp Support에 문의하십시오.



TIP: 스토리지 및 컴퓨팅 리소스의 수를 보려면 HCC(하이브리드 클라우드 제어) 대시보드를 확인하십시오. 을 참조하십시오 link:task_hcc_dashboard.html["HCC 대시보드를 사용하여 스토리지 및 컴퓨팅 리소스를 모니터링합니다"].

[discrete]
== 자세한 내용을 확인하십시오

* https://docs.netapp.com/us-en/solidfire-active-iq/index.html["NetApp SolidFire Active IQ 문서"^]
* https://docs.netapp.com/us-en/vcp/index.html["vCenter Server용 NetApp Element 플러그인"^]
* https://www.netapp.com/hybrid-cloud/hci-documentation/["NetApp HCI 리소스 페이지 를 참조하십시오"^]

