---
sidebar: sidebar 
permalink: docs/task_hcc_upgrade_compute_firmware_ansible.html 
summary: H 시리즈 컴퓨팅 노드의 경우 NetApp은 BMC, BIOS, NIC와 같은 하드웨어 구성 요소의 펌웨어 업그레이드 자동화를 지원하는 Ansible 역할을 제공합니다. 
keywords: netapp, hci, on premise, cluster, element, compute node, ansible upgrade, upgrade role 
---
= Ansible을 사용하여 컴퓨팅 노드 펌웨어의 업그레이드 자동화
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
NetApp 하이브리드 클라우드 제어의 워크플로우를 사용하여 NetApp HCI, BIOS, NIC와 같은 구성요소의 펌웨어를 포함하여 컴퓨팅 노드에서 시스템 펌웨어를 업데이트할 수 있습니다. 대규모 컴퓨팅 클러스터를 설치할 경우 Ansible을 사용하여 전체 클러스터의 롤링 업그레이드를 수행하여 워크플로우를 자동화할 수 있습니다.


NOTE: 컴퓨팅 노드 펌웨어 업그레이드를 자동화하는 Ansible 역할은 NetApp에서 사용할 수 있지만, 자동화는 추가 설정과 소프트웨어 구성요소를 실행해야 하는 보조 구성요소입니다. Ansible 자동화는 가장 노력한 바탕으로 수정할 수 있습니다.


NOTE: 업그레이드를 위한 Ansible 역할은 NetApp HCI H-series 컴퓨팅 노드에서만 사용할 수 있습니다. 이 역할을 사용하여 타사 컴퓨팅 노드를 업그레이드할 수는 없습니다.

.필요한 것
* * 펌웨어 업그레이드를 위한 준비 및 사전 요구 사항 *: 의 지침에 따라 NetApp HCI 설치를 펌웨어 업그레이드 준비가 되어 있어야 합니다 link:task_hcc_upgrade_compute_node_firmware.html["펌웨어 업그레이드 수행 중"].
* * Ansible 제어 노드 * 에서 자동화를 실행할 준비: Ansible에서 펌웨어 업데이트 자동화를 실행하는 물리적 서버 또는 가상 서버


.이 작업에 대해
운영 환경에서는 클러스터의 컴퓨팅 노드를 롤링 방식으로 업데이트하고, 한 노드는 한 번에 하나씩 노드 방식으로 NetApp HCI를 설치해야 합니다. NetApp 하이브리드 클라우드 제어의 API는 상태 점검 실행, 컴퓨팅 노드에 ESXi를 유지 관리에 배치, 펌웨어 업그레이드를 적용하기 위해 컴퓨팅 노드를 재부팅하는 등 단일 컴퓨팅 노드에 대한 전체 컴퓨팅 노드 펌웨어 업그레이드 프로세스를 조정합니다. Ansible 역할은 컴퓨팅 노드 그룹 또는 전체 클러스터의 펌웨어 업그레이드를 오케스트레이션할 수 있는 옵션을 제공합니다.

.펌웨어 업그레이드 자동화를 시작하십시오
시작하려면 로 이동합니다 https://github.com/NetApp-Automation/nar_compute_firmware_upgrade["GitHub의 NetApp Ansible 리포지토리"^] 그리고 'NAR_컴퓨팅_노드_펌웨어_업그레이드' 역할 및 문서를 다운로드하십시오.
