---
sidebar: sidebar 
permalink: docs/task_mnode_configure_proxy_server.html 
summary: REST API UI를 사용하여 관리 노드 구성에 컴퓨팅 및 컨트롤러 자산을 추가할 수 있습니다. 
keywords: netapp, hci, mnode, api, management node, add proxy, proxy server 
---
= 프록시 서버를 구성합니다
:allow-uri-read: 


[role="lead"]
클러스터가 프록시 서버 뒤에 있는 경우 공용 네트워크에 연결할 수 있도록 프록시 설정을 구성해야 합니다.

원격 측정 수집기와 역방향 터널 연결에 프록시 서버가 사용됩니다. 설치 또는 업그레이드 중에 프록시 서버를 구성하지 않은 경우 REST API UI를 사용하여 프록시 서버를 활성화하고 구성할 수 있습니다. 기존 프록시 서버 설정을 수정하거나 프록시 서버를 비활성화할 수도 있습니다.

프록시 서버 업데이트를 구성한 다음 관리 노드에 대한 현재 프록시 설정을 반환하는 명령입니다. 프록시 설정은 Active IQ, NetApp 배포 엔진에 의해 구현되는 NetApp HCI 모니터링 서비스 및 NetApp 지원에 대한 역방향 지원 터널을 포함하여 관리 노드에 설치된 기타 Element 소프트웨어 유틸리티에서 사용됩니다.

.시작하기 전에
* 구성 중인 프록시 서버에 대한 호스트 및 자격 증명 정보를 알고 있어야 합니다.
* 클러스터 버전이 NetApp Element 소프트웨어 11.3 이상을 실행하고 있는지 확인합니다.
* 버전 11.3 이상을 실행하는 관리 노드를 배포했는지 확인합니다.
* (관리 노드 12.0 이상) 프록시 서버를 구성하기 전에 NetApp 하이브리드 클라우드 제어를 관리 서비스 버전 2.16으로 업데이트했습니다.


.단계
. 관리 노드의 REST API UI에 접속하려면 관리 노드의 IP 주소와 '/mnode'를 차례로 입력합니다.
+
[listing]
----
https://<ManagementNodeIP>/mnode
----
. authorize * 또는 임의의 잠금 아이콘을 클릭하고 다음을 완료합니다.
+
.. 클러스터 사용자 이름 및 암호를 입력합니다.
.. Client ID를 mnode-client로 입력한다.
.. 세션을 시작하려면 * authorize * 를 클릭합니다.
.. 창을 닫습니다.


. PUT/SETTINGS * 를 클릭합니다.
. 체험하기 * 를 클릭합니다.
. 프록시 서버를 활성화하려면 use_proxy를 true로 설정해야 합니다. IP 또는 호스트 이름 및 프록시 포트 대상을 입력합니다.
+
프록시 사용자 이름, 프록시 암호 및 SSH 포트는 선택 사항이며 사용하지 않는 경우 생략해야 합니다.

+
[listing]
----
{
"proxy_ip_or_hostname": "[IP or name]",
"use_proxy": [true/false],
"proxy_username": "[username]",
"proxy_password": "[password]",
"proxy_port": [port value],
"proxy_ssh_port": [port value: default is 443]
}
----
. Execute * 를 클릭합니다.



NOTE: 환경에 따라 관리 노드를 재부팅해야 할 수도 있습니다.



== 자세한 내용을 확인하십시오

https://docs.netapp.com/us-en/vcp/index.html["vCenter Server용 NetApp Element 플러그인"^]
