---
sidebar: sidebar 
permalink: docs/task_nde_review_deploy.html 
summary: 최종 구성을 검토하고 이러한 설정으로 NetApp HCI를 배포하는 방법에 대해 알아봅니다. 
keywords: netapp, hci, deployment, review, deploy 
---
= 구성을 검토하고 배포합니다
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
배포를 시작하기 전에 제공한 정보를 검토할 수 있습니다. 계속하기 전에 부정확하거나 불완전한 정보를 수정할 수도 있습니다.


NOTE: 구축 과정에서 관리 노드 설치 프로세스에서 Element 스토리지 클러스터에 NetApp-HCI라는 이름의 볼륨이 생성되고 SolidFire 계정에는 테넌트 _ 라는 이름의 볼륨이 생성됩니다. 이러한 볼륨 또는 계정을 삭제하지 마십시오. 삭제하면 관리 기능이 손실됩니다.

.단계
. 선택 사항: * 다운로드 * 아이콘을 선택하여 설치 정보를 CSV 형식으로 다운로드합니다. 이 파일을 저장하고 나중에 구성 정보를 참조할 수 있습니다.
+

NOTE: 나중에 설치할 때 필요한 경우 NDE(NetApp Deployment Engine)의 * 설치 프로필 * 페이지에서 CSV 파일을 설치 프로필로 가져올 수 있습니다.

. 각 섹션을 확장하고 정보를 검토합니다. 모든 섹션을 한 번에 확장하려면 * Expand All * (모두 확장 *)을 선택합니다.
. 선택 사항: 표시된 섹션의 정보를 변경하려면:
+
.. 해당 섹션에서 * Edit * 를 선택합니다.
.. 필요한 사항을 변경합니다.
.. Review * (검토 *) 페이지가 나타날 때까지 * Continue * (계속 *)를 선택합니다. 이전 설정은 각 페이지에 저장됩니다.
.. 2단계와 3단계를 반복하여 필요한 다른 사항을 변경합니다.


. 클러스터 통계 및 지원 정보를 NetApp이 호스팅하는 SolidFire Active IQ 서버로 전송하지 않으려면 마지막 확인란의 선택을 취소합니다.
+
이렇게 하면 NetApp HCI에 대한 실시간 상태 및 진단 모니터링이 비활성화됩니다. 이 기능을 비활성화하면 NetApp이 사전에 NetApp HCI를 지원 및 모니터링하여 운영 환경에 영향을 미치지 않고 문제를 감지하고 해결할 수 있습니다.

. 모든 정보가 올바르면 * 배포 시작 * 을 선택합니다.
+
대화 상자가 나타납니다. 최종 설정 프로세스 중에 네트워크 연결 문제나 전원 손실이 발생하거나 브라우저 세션이 손실된 경우 대화 상자에 표시된 URL을 복사하여 최종 설정 진행 페이지로 이동할 수 있습니다.

. 대화 상자의 정보를 검토하고 * 클립보드로 복사 * 를 선택하여 URL을 클립보드에 복사합니다.
. URL을 컴퓨터의 텍스트 파일에 저장합니다.
. 배포를 진행할 준비가 되면 * OK * 를 선택합니다.
+
배포가 시작되고 진행률 페이지가 표시됩니다. 배포가 완료될 때까지 브라우저 창을 닫거나 진행률 페이지에서 벗어나지 마십시오. 어떤 이유로든 브라우저 세션이 손실되면 이전에 복사한 URL을 찾아(나타나는 보안 경고를 모두 수락함) 최종 설치 진행률 페이지에 다시 액세스할 수 있습니다.

+

NOTE: 배포에 실패하면 오류 메시지 텍스트를 저장하고 NetApp 지원에 문의하십시오.

+
구축이 완료된 후 컴퓨팅 노드가 두 번 이상 재부팅된 후 서비스 준비가 될 수 있습니다.



vSphere * 시작 을 선택하여 NetApp HCI 사용을 시작합니다.

[NOTE]
====
* vSphere 6.7을 사용하는 NetApp HCI 설치의 경우 이 링크를 클릭하면 HTML5 vSphere 웹 인터페이스가 실행됩니다. vSphere 6.5를 사용한 설치의 경우 이 링크를 클릭하면 Adobe Flash vSphere 웹 인터페이스가 실행됩니다.
* NDE는 스토리지 2개 또는 스토리지 노드 3개 구성에서 Witness 노드가 컴퓨팅 노드에서 로컬 데이터 저장소를 사용하도록 구성합니다. 따라서 vSphere Client에 두 개의 * 데이터 저장소 사용량이 disk * 경고에 표시됩니다. 계속하려면 각 경고에서 * 녹색으로 재설정 * 링크를 선택하십시오.


====


== 자세한 내용을 확인하십시오

* https://docs.netapp.com/us-en/vcp/index.html["vCenter Server용 NetApp Element 플러그인"^]
* https://www.netapp.com/us/documentation/hci.aspx["NetApp HCI 리소스 페이지를 참조하십시오"^]
* https://docs.netapp.com/us-en/element-software/index.html["SolidFire 및 Element 소프트웨어 설명서"^]

