---
sidebar: sidebar 
permalink: docs/task_hci_hserieschassisrepl.html 
summary: 섀시에 팬 고장 또는 전원 문제가 있는 경우 가능한 한 빨리 교체해야 합니다. 섀시 교체 절차의 단계는 NetApp HCI 구성 및 클러스터 용량에 따라 달라지며, 신중하게 고려하고 계획해야 합니다. NetApp 지원에 문의하여 안내를 확인하고 교체 섀시를 주문해야 합니다. 
keywords: netapp, hci, chassis replacement,2U chassis replacement, h-series 
---
= 2U H 시리즈 섀시를 교체합니다
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
섀시에 팬 고장 또는 전원 문제가 있는 경우 가능한 한 빨리 교체해야 합니다. 섀시 교체 절차의 단계는 NetApp HCI 구성 및 클러스터 용량에 따라 달라지며, 신중하게 고려하고 계획해야 합니다. NetApp 지원에 문의하여 안내를 확인하고 교체 섀시를 주문해야 합니다.

.이 작업에 대해
섀시를 교체하기 전에 다음 사항을 고려해야 합니다.

* 랙에 새 섀시를 위한 추가 공간이 있습니까?
* 구축의 섀시 중 사용하지 않는 노드 슬롯이 있습니까?
* 랙에 추가 공간이 있는 경우 각 노드를 장애가 발생한 섀시에서 새 섀시로 한 번에 하나씩 이동할 수 있습니까? 이 프로세스에는 시간이 걸릴 수 있음을 염두에 두어야 합니다.
* 장애가 발생한 섀시에 포함된 노드를 제거할 때 스토리지 클러스터가 온라인 상태로 유지될 수 있습니까?
* 장애가 발생한 섀시의 일부인 컴퓨팅 노드를 제거할 때 가상 머신(VM) 및 ESXi 클러스터에서 워크로드를 처리할 수 있습니까?


.대치 옵션
다음 옵션 중 하나를 선택합니다.<<랙에서 사용하지 않은 공간을 추가로 사용할 수 있는 경우 섀시를 교체합니다>>
<<사용하지 않는 추가 공간을 랙에 사용할 수 없는 경우 섀시를 교체합니다>>



== 랙에서 사용하지 않은 공간을 추가로 사용할 수 있는 경우 섀시를 교체합니다

랙에 추가 공간이 있는 경우 새 섀시를 설치하고 노드를 한 번에 하나씩 새 섀시로 이동할 수 있습니다. 설치된 섀시 중 하나에 사용되지 않는 노드 슬롯이 있는 경우 장애가 발생한 섀시에서 사용되지 않는 슬롯으로 노드를 한 번에 하나씩 이동한 다음, 장애가 발생한 섀시를 제거할 수 있습니다. 절차를 수행하기 전에 케이블 길이가 충분한지, 그리고 스위치 포트를 사용할 수 있는지 확인하십시오.


NOTE: 컴퓨팅 노드를 이동하는 단계는 스토리지 노드를 이동하는 단계와 다릅니다. 노드를 이동하기 전에 노드가 올바르게 종료되었는지 확인해야 합니다. 장애가 발생한 섀시에서 모든 노드를 이동한 후에는 섀시에서 섀시를 분리하여 NetApp에 반환해야 합니다.



=== 새 섀시를 설치합니다

사용 가능한 랙 공간에 새 섀시를 설치하고 노드를 해당 랙 공간으로 이동할 수 있습니다.

.필요한 것
* 정전기 방전(ESD) 손목 보호대가 있거나 다른 정전기 방지 보호 장치를 착용하고 있습니다.
* 교체용 섀시가 있습니다.
* 단계를 수행할 리프트가 있거나 두 명 이상이 있어야 합니다.
* 1 십자 드라이버가 있습니다.


.단계
. 정전기 방지 보호 장치를 놓습니다.
. 교체용 섀시의 포장을 풉니다. 오류가 발생한 섀시를 NetApp으로 반환할 때 용 패키지를 유지합니다.
. 섀시와 함께 제공된 레일을 삽입합니다.
. 교체 섀시를 랙에 밀어 넣습니다.
+

TIP: 섀시를 설치하는 동안 항상 충분한 인력 또는 리프트를 사용하십시오.

. 전면 장착 나비 나사를 사용하여 섀시를 랙에 고정하고 드라이버로 나사를 조입니다.




=== 컴퓨팅 노드를 이동합니다

컴퓨팅 노드를 새 섀시 또는 사용되지 않는 슬롯이 추가된 기존 섀시로 이동하기 전에 가상 머신(VM)을 마이그레이션하고, 노드를 올바르게 종료하고, 노드에 삽입된 케이블에 레이블을 지정해야 합니다.


NOTE: 노드를 이동할 때 정전기 방지 보호 기능이 있는지 확인합니다.

.단계
. 노드 뒷면의 스티커에 있는 노드의 일련 번호를 기록합니다.
. VMware vSphere Web Client에서 * Hosts and Clusters * 를 선택하고 노드(호스트)를 선택한 다음 * Monitor > Hardware Status > Sensors * 를 선택합니다.
. 센서 * 섹션에서 노드 뒷면의 스티커에 표시된 일련 번호를 찾습니다.
. 일치하는 일련 번호를 찾은 후 사용 가능한 다른 호스트로 VM을 마이그레이션합니다.
+

NOTE: 마이그레이션 단계는 VMware 설명서를 참조하십시오.

. 노드를 마우스 오른쪽 단추로 클릭하고 * 전원 > 시스템 종료 * 를 선택합니다. 이제 섀시에서 노드를 물리적으로 제거할 준비가 되었습니다.
. 노드 및 노드 후면의 모든 케이블에 레이블을 지정합니다.
. 각 노드의 오른쪽에 있는 캠 핸들을 아래로 당기고 캠 핸들 모두를 사용하여 노드를 밖으로 당겨 섀시에서 노드를 제거합니다.
. 딸깍 소리가 날 때까지 노드를 눌러 새 섀시에 노드를 재설치합니다. 노드를 제거하기 전에 이 노드에 연결한 레이블은 사용자에게 도움이 됩니다. 노드를 올바르게 설치하면 자동으로 전원이 켜집니다.
+

CAUTION: 설치 시 에서 노드를 지원하는지 확인하십시오. 노드를 섀시에 밀어 넣을 때 과도한 힘을 가하지 마십시오.

+

NOTE: 새 섀시에 설치하는 경우, 섀시의 원래 슬롯에 노드를 설치해야 합니다.

. 노드 후면의 동일한 포트에 케이블을 다시 연결합니다. 케이블을 분리할 때 케이블에 부착된 라벨은 도움이 됩니다.
+

CAUTION: 케이블을 포트에 억지로 밀어 넣지 마십시오. 케이블, 포트 또는 둘 다 손상될 수 있습니다.

. VMware vSphere Web Client의 ESXi 클러스터에 컴퓨팅 노드(호스트)가 나열되어 있는지 확인합니다.
. 장애가 발생한 섀시의 모든 컴퓨팅 노드에 대해 다음 단계를 수행합니다.




=== 스토리지 노드를 이동합니다

스토리지 노드를 새 섀시로 이동하기 전에 드라이브를 제거하고 노드를 올바르게 종료하며 모든 구성 요소에 레이블을 지정해야 합니다.

.단계
. 제거할 노드를 다음과 같이 식별합니다.
+
.. 노드 뒷면의 스티커에 있는 노드의 일련 번호를 기록합니다.
.. VMware vSphere 웹 클라이언트에서 * NetApp Element Management * 를 선택하고 MVIP IP 주소를 복사합니다.
.. 웹 브라우저에서 MVIP IP 주소를 사용하여 NetApp 배포 엔진에서 구성한 사용자 이름과 암호를 사용하여 NetApp Element 소프트웨어 UI에 로그인합니다.
.. 클러스터 > 노드 * 를 선택합니다.
.. 아래에 기록한 일련 번호를 나열된 일련 번호(서비스 태그)와 연결하십시오.
.. 노드의 노드 ID를 기록합니다.


. 노드를 식별한 후 ' wget--no-check-certificate -q--user=<user>--password=<pass>- O--post-data' {"method":"MovemariPriesAwayFromNode", "nodeams":{"nodeid":{"NODEID}' API 호출을 사용하여 노드에서 iSCSI 세션을 이동합니다. https://<MVIP>/json-rpc/8.0`[]MVIP는 MVIP IP 주소이고, NODEID는 노드 ID이고, NetApp HCI를 설정할 때 NetApp 배포 엔진에서 구성한 사용자 이름이며, PASS는 NetApp HCI를 설정할 때 NetApp 배포 엔진에서 구성한 암호입니다.
. Cluster > Drives * 를 선택하여 노드와 연결된 드라이브를 제거합니다.
+

NOTE: 노드를 제거하기 전에 제거한 드라이브가 사용 가능한 것으로 표시될 때까지 기다려야 합니다.

. 클러스터 > 노드 > 작업 > 제거 * 를 선택하여 노드를 제거합니다.
. 다음 API 호출을 사용하여 노드를 종료합니다. '<wget--no-check-certificate-q--user=<user>--password=<pass>-O--post-data' {"method":"shutdown", "params":{"halt","nodes":[<NODEID>]}' https://<MVIP>/json-rpc/8.0`[]MVIP는 MVIP IP 주소이고, NODEID는 노드 ID이고, NetApp HCI를 설정할 때 NetApp 배포 엔진에서 구성한 사용자 이름이며, PASS는 NetApp HCI를 설정할 때 NetApp 배포 엔진에서 구성한 암호입니다. 노드가 종료되면 섀시에서 물리적으로 제거할 준비가 된 것입니다.
. 다음과 같이 섀시 노드에서 드라이브를 분리합니다.
+
.. 베젤을 분리합니다.
.. 드라이브에 레이블을 지정합니다.
.. 캠 핸들을 열고 양손으로 조심스럽게 각 드라이브를 밖으로 밀어냅니다.
.. 드라이브를 정전기 방지 표면에 놓습니다.


. 다음과 같이 섀시에서 노드를 분리합니다.
+
.. 연결된 노드 및 케이블에 레이블을 지정합니다.
.. 각 노드의 오른쪽에 있는 캠 핸들을 아래로 당기고 양쪽 캠 핸들을 사용하여 노드를 밖으로 당깁니다.


. 딸깍 소리가 날 때까지 노드를 밀어 넣어 섀시에 노드를 다시 설치합니다. 노드를 제거하기 전에 이 노드에 연결한 레이블은 사용자에게 도움이 됩니다.
+

CAUTION: 설치 시 에서 노드를 지원하는지 확인하십시오. 노드를 섀시에 밀어 넣을 때 과도한 힘을 가하지 마십시오.

+

NOTE: 새 섀시에 설치하는 경우, 섀시의 원래 슬롯에 노드를 설치해야 합니다.

. 딸깍 소리가 날 때까지 각 드라이브의 캠 핸들을 눌러 노드의 각 슬롯에 드라이브를 설치합니다.
. 노드 후면의 동일한 포트에 케이블을 다시 연결합니다. 케이블을 분리할 때 케이블에 부착한 라벨은 도움이 될 것입니다.
+

CAUTION: 케이블을 포트에 억지로 밀어 넣지 마십시오. 케이블, 포트 또는 둘 다 손상될 수 있습니다.

. 노드 전원이 켜진 후 노드를 클러스터에 추가합니다.
+

NOTE: 노드가 추가되고 * 노드 > 활성 * 에 표시되는 데 최대 2분이 걸릴 수 있습니다.

. 드라이브를 추가합니다.
. 섀시의 모든 스토리지 노드에 대해 다음 단계를 수행합니다.




== 사용하지 않는 추가 공간을 랙에 사용할 수 없는 경우 섀시를 교체합니다

랙에 추가 공간이 없고 구축에 사용되지 않는 노드 슬롯이 없는 경우 교체 절차를 수행하기 전에 온라인 상태를 유지할 수 있는 항목을 결정해야 합니다.

.이 작업에 대해
섀시를 교체하기 전에 다음 사항을 고려해야 합니다.

* 장애가 발생한 섀시에 스토리지 노드가 없는 상태에서 스토리지 클러스터를 온라인 상태로 유지할 수 있습니까? 대답이 '아니오'인 경우, NetApp HCI 구축 시 모든 노드(컴퓨팅 및 스토리지)를 종료해야 합니다. 예라고 대답한 경우 오류가 발생한 섀시의 스토리지 노드만 종료할 수 있습니다.
* 장애가 발생한 섀시에 컴퓨팅 노드가 없어도 VM 및 ESXi 클러스터가 온라인 상태를 유지할 수 있습니까? 대답이 '아니오'이면 오류가 발생한 섀시에서 컴퓨팅 노드를 종료할 수 있도록 적절한 VM을 종료하거나 마이그레이션해야 합니다. 예라고 대답한 경우 오류가 발생한 섀시의 컴퓨팅 노드만 종료할 수 있습니다.




=== 컴퓨팅 노드를 종료합니다

컴퓨팅 노드를 새 섀시로 이동하기 전에 VM을 마이그레이션하고 올바르게 종료한 다음 노드에 삽입된 케이블에 레이블을 지정해야 합니다.

.단계
. 노드 뒷면의 스티커에 있는 노드의 일련 번호를 기록합니다.
. VMware vSphere Web Client에서 * Hosts and Clusters * 를 선택하고 노드(호스트)를 선택한 다음 * Monitor > Hardware Status > Sensors * 를 선택합니다.
. 센서 * 섹션에서 노드 뒷면의 스티커에 표시된 일련 번호를 찾습니다.
. 일치하는 일련 번호를 찾은 후 사용 가능한 다른 호스트로 VM을 마이그레이션합니다.
+

NOTE: 마이그레이션 단계는 VMware 설명서를 참조하십시오.

. 노드를 마우스 오른쪽 단추로 클릭하고 * 전원 > 시스템 종료 * 를 선택합니다. 이제 섀시에서 노드를 물리적으로 제거할 준비가 되었습니다.




=== 스토리지 노드를 종료합니다

단계를 참조하십시오 <<move a storage node,여기>>.



=== 노드를 제거합니다

섀시에서 노드를 조심스럽게 분리하고 모든 구성 요소에 레이블을 지정해야 합니다. 물리적으로 노드를 제거하는 단계는 스토리지 노드와 컴퓨팅 노드 모두에서 동일합니다. 스토리지 노드의 경우 노드를 제거하기 전에 드라이브를 제거합니다.

.단계
. 스토리지 노드의 경우 다음과 같이 섀시의 노드에서 드라이브를 제거합니다.
+
.. 베젤을 분리합니다.
.. 드라이브에 레이블을 지정합니다.
.. 캠 핸들을 열고 양손으로 조심스럽게 각 드라이브를 밖으로 밀어냅니다.
.. 드라이브를 정전기 방지 표면에 놓습니다.


. 다음과 같이 섀시에서 노드를 분리합니다.
+
.. 연결된 노드 및 케이블에 레이블을 지정합니다.
.. 각 노드의 오른쪽에 있는 캠 핸들을 아래로 당기고 양쪽 캠 핸들을 사용하여 노드를 밖으로 당깁니다.


. 제거할 모든 노드에 대해 다음 단계를 수행합니다. 이제 장애가 발생한 섀시를 제거할 준비가 되었습니다.




=== 섀시를 교체합니다

랙에 추가 공간이 없는 경우 결함이 있는 섀시를 제거하고 새 섀시로 교체해야 합니다.

.단계
. 정전기 방지 보호 장치를 놓습니다.
. 교체용 섀시의 포장을 풀고 평평한 곳에 보관합니다. 오류가 발생한 장치를 NetApp에 반환할 때 용 의 패키지를 유지합니다.
. 랙에서 결함이 있는 섀시를 분리하여 평평한 표면에 놓습니다.
+

NOTE: 섀시를 이동하는 동안 충분한 인력 또는 리프트를 사용하십시오.

. 레일을 분리합니다.
. 교체용 섀시와 함께 제공된 새 레일을 설치합니다.
. 교체 섀시를 랙에 밀어 넣습니다.
. 전면 장착 나비 나사를 사용하여 섀시를 랙에 고정하고 드라이버로 나사를 조입니다.
. 다음과 같이 새 섀시에 노드를 설치합니다.
+
.. 딸깍 소리가 날 때까지 노드를 밀어 넣어 섀시의 원래 슬롯에 노드를 재장착합니다. 노드를 제거하기 전에 이 노드에 연결한 레이블은 유용합니다.
+

CAUTION: 설치 시 에서 노드를 지원하는지 확인하십시오. 노드를 섀시에 밀어 넣을 때 과도한 힘을 가하지 마십시오.

.. 스토리지 노드의 경우 딸깍 소리가 날 때까지 각 드라이브의 캠 핸들을 눌러 해당 노드의 슬롯에 드라이브를 설치합니다.
.. 노드 후면의 동일한 포트에 케이블을 다시 연결합니다. 케이블을 분리할 때 케이블에 부착된 라벨은 도움이 됩니다.
+

CAUTION: 케이블을 포트에 억지로 밀어 넣지 마십시오. 케이블, 포트 또는 둘 다 손상될 수 있습니다.



. 노드가 다음과 같이 온라인 상태인지 확인합니다.
+
[cols="2*"]
|===
| 옵션을 선택합니다 | 단계 


| NetApp HCI 배포에서 모든 노드(스토리지 및 컴퓨팅 모두)를 재설치한 경우  a| 
.. VMware vSphere Web Client에서 컴퓨팅 노드(호스트)가 ESXi 클러스터에 나열되어 있는지 확인합니다.
.. vCenter Server용 Element 플러그인에서 스토리지 노드가 Active로 나열되는지 확인합니다.




| 오류가 발생한 섀시에 노드만 재설치한 경우  a| 
.. VMware vSphere Web Client에서 컴퓨팅 노드(호스트)가 ESXi 클러스터에 나열되어 있는지 확인합니다.
.. vCenter Server용 Element 플러그인에서 * 클러스터 > 노드 > 보류 * 를 선택합니다.
.. 노드를 선택하고 * 추가 * 를 선택합니다.
+

NOTE: 노드가 추가되고 * 노드 > 활성 * 에 표시되는 데 최대 2분이 걸릴 수 있습니다.

.. 드라이브 * 를 선택합니다.
.. 사용 가능 목록에서 드라이브를 추가합니다.
.. 재설치한 모든 스토리지 노드에 대해 다음 단계를 수행하십시오.


|===
. 볼륨 및 데이터 저장소가 가동되어 있고 액세스할 수 있는지 확인합니다.




== 자세한 내용을 확인하십시오

* https://www.netapp.com/us/documentation/hci.aspx["NetApp HCI 리소스 페이지를 참조하십시오"^]
* http://docs.netapp.com/sfe-122/index.jsp["SolidFire 및 Element 소프트웨어 설명서 센터"^]

