---
sidebar: sidebar 
permalink: docs/task_nde_select_net_topology.html 
summary: NetApp HCI 구축 중에 VMware vSphere를 구성하는 방법을 알아보십시오. 
keywords: netapp, hci, netapp deployment engine, deployment, vsphere 
---
= 네트워크 토폴로지를 선택합니다
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/
:keywords: netapp, hci, netapp deployment engine, deployment, vsphere


[role="lead"]
NetApp HCI 노드에 케이블을 연결할 때 필요에 따라 다른 네트워크 케이블 구성을 사용할 수 있습니다. 각 컴퓨팅 노드에 대해 각 포트 쌍에 할당된 트래픽 유형이 서로 다른 6개의 네트워크 포트를 모두 사용하거나 포트에 할당된 모든 트래픽 유형에 2개의 포트를 사용할 수 있습니다. 스토리지 노드는 표준 4케이블 구성을 사용합니다. 선택 사항은 인벤토리에서 선택할 수 있는 컴퓨팅 노드에 영향을 줍니다.

.필요한 것
컴퓨팅 노드에 대해 2케이블 네트워크 토폴로지를 선택한 경우 다음 요구 사항을 고려하십시오.

* 구축이 완료된 후 VMware vSphere Enterprise Plus 라이센스를 적용할 준비가 되었습니다.
* 네트워크 및 네트워크 스위치 구성이 올바른지 확인했습니다.
* VLAN 태깅은 모든 컴퓨팅 및 스토리지 노드에 대해 스토리지 및 vMotion 네트워크에 필요합니다.


.단계
. 네트워크 토폴로지 * 페이지에서 NetApp HCI용 컴퓨팅 노드를 설치한 방식에 맞는 컴퓨팅 노드 토폴로지를 선택합니다.
+
** * 6 케이블 옵션 *: 6개 케이블 옵션은 각 트래픽 유형(관리, 가상 머신 및 스토리지)에 대한 전용 포트를 제공합니다. 선택적으로 VDS(vSphere Distributed Switch)를 활성화할 수 있습니다. VDS를 활성화하면 분산 스위치가 구성되므로 NetApp HCI 배포가 완료된 후 가상 컴퓨터 네트워크 구성을 중앙에서 간편하게 관리할 수 있습니다. 이 기능을 사용하도록 설정한 경우 구축 후 vSphere Enterprise Plus 라이센스를 적용할 준비가 되어 있어야 합니다.
** * 2 케이블 옵션 *: 2개의 연결된 포트에 관리, 가상 시스템 및 스토리지 트래픽을 결합하는 2개의 케이블 옵션 이 케이블링 옵션은 VDS가 필요하며 자동으로 활성화됩니다. 구축 후 vSphere Enterprise Plus 라이센스를 적용할 준비가 되어 있어야 합니다.


. 일부 케이블 연결 옵션은 여러 유형의 노드 하드웨어에 대한 다중 후면 패널 보기를 표시합니다. 후면 패널 보기를 순환하여 특정 노드 모델 및 케이블 연결 옵션에 대한 네트워크 케이블을 연결하는 방법을 확인합니다.
. 완료되면 * 계속 * 을 클릭합니다.


[discrete]
== 자세한 내용을 확인하십시오

* https://kb.netapp.com/Advice_and_Troubleshooting/Hybrid_Cloud_Infrastructure/NetApp_HCI/Firmware_and_driver_versions_in_NetApp_HCI_and_NetApp_Element_software["NetApp HCI 및 NetApp Element 소프트웨어의 펌웨어 및 드라이버 버전"^]

