---
sidebar: sidebar 
permalink: docs/task_hcc_upgrade_management_node.html 
summary: NetApp HCI 시스템 업그레이드의 일부로 관리 노드를 업그레이드합니다. 
keywords: netapp, hci, on premise, cluster, management node, mNode, upgrade, 10, 11.0, 11.1, 11.3, 11.5, 11.7, 12.0, 12.2, 12.3, 12.3.1, 12.3.2, 12.3.x 
---
= 관리 노드를 업그레이드합니다
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
관리 노드를 버전 11.0 이상에서 관리 노드 버전 12.3.x로 업그레이드할 수 있습니다.

스토리지 클러스터에서 Element 소프트웨어를 업그레이드하는 데 관리 노드 운영 체제를 더 이상 업그레이드할 필요가 없습니다. 관리 노드가 버전 11.3 이상인 경우 NetApp 하이브리드 클라우드 제어를 사용하여 관리 서비스를 최신 버전으로 업그레이드하여 Element 업그레이드를 수행할 수 있습니다. 보안 문제 해결과 같은 다른 이유로 관리 노드 운영 체제를 업그레이드하려면 시나리오에 따라 관리 노드 업그레이드 절차를 따르십시오.


NOTE: vCenter Plug-in 4.4 이상에서는 모듈식 아키텍처를 사용하여 생성되고 개별 서비스를 제공하는 관리 노드 11.3 이상이 필요합니다.

다음 관리 노드 업그레이드 옵션 중 하나를 선택합니다.

[NOTE]
====
* 관리 노드 12.3.2에는 가상 볼륨(VVol) 기능이 활성화된 스토리지 클러스터에 대한 보안 완화 기능이 포함되어 있습니다. 스토리지 클러스터가 이미 Element 12.3에 있고 VVOL 기능이 활성화된 경우 12.3.2로 업그레이드하는 것이 좋습니다.
* 관리 노드 12.3.1에는 추가 기능 변경 또는 버그 수정이 없습니다. 이미 관리 노드 12.3을 실행 중인 경우에는 12.3.1로 업그레이드할 필요가 없습니다.


====
* 관리 노드 12.3에서 업그레이드하는 경우 관리 노드 12.3.1에는 추가 기능 변경 또는 버그 수정이 없습니다. 이미 관리 노드 12.3을 실행 중인 경우에는 12.3.1로 업그레이드할 필요가 없습니다.



NOTE: NDE를 사용하여 배포된 관리 노드 12.3에서 업그레이드를 진행하도록 선택하면 12.3.x로 업그레이드가 완료됩니다. 그러나 다시 시작하는 동안 업그레이드에 오류가 발생할 수 있습니다. 이 경우 관리 노드를 재부팅하여 12.3.x가 올바르게 표시되도록 합니다

* 관리 노드 12.2에서 업그레이드하는 경우:<<Upgrade a management node to version 12.3.x from 12.2>>
* 관리 노드 12.0에서 업그레이드하는 경우:<<Upgrade a management node to version 12.3.x from 12.0>>
* 관리 노드 11.3, 11.5, 11.7 또는 11.8에서 업그레이드하는 경우:<<Upgrade a management node to version 12.3.x from 11.3 through 11.8>>
* 관리 노드 11.0 또는 11.1에서 업그레이드하는 경우:<<Upgrade a management node to version 12.3.x from 11.1 or 11.0>>
* 관리 노드 버전 10.x에서 업그레이드하는 경우:<<Migrating from management node version 10.x to 11.x>>


관리 서비스 버전(1) 및 (2) 요소 스토리지 버전을 * 순차적으로 * 업데이트하고 * 기존 관리 노드를 * 유지하려면 다음 옵션을 선택합니다.


NOTE: 관리 서비스를 Element 스토리지 뒤에 순차적으로 업데이트하지 않으면 이 절차를 사용하여 재인증을 재구성할 수 없습니다. 대신 적절한 업그레이드 절차를 따르십시오.

* 기존 관리 노드를 유지하는 경우:<<Reconfigure authentication using the management node REST API>>




== 관리 노드를 12.2에서 12.3.x 버전으로 업그레이드합니다

새 관리 노드 가상 시스템을 프로비저닝하지 않고도 관리 노드를 버전 12.2에서 버전 12.3.x로 데이터 이동 없이 업그레이드할 수 있습니다.


NOTE: Element 12.3.x 관리 노드는 선택적 업그레이드입니다. 기존 배포에는 필요하지 않습니다.

.무엇을 &#8217;필요로 할거야
* 관리 노드 VM의 RAM은 24GB입니다.
* 업그레이드하려는 관리 노드는 버전 12.0이며 IPv4 네트워킹을 사용합니다. 관리 노드 버전 12.3.x는 IPv6을 지원하지 않습니다.
+

TIP: 관리 노드의 버전을 확인하려면 관리 노드에 로그인하고 로그인 배너에서 Element 버전 번호를 확인합니다.

* NetApp 하이브리드 클라우드 제어(HCC)를 사용하여 관리 서비스 번들을 최신 버전으로 업데이트했습니다. 다음 IP에서 HCC에 액세스할 수 있습니다. 'https://<ManagementNodeIP>`
* 관리 노드를 버전 12.3.x로 업데이트하는 경우 계속하려면 관리 서비스 2.14.60 이상이 필요합니다.
* 에 대한 지침을 사용하여 추가 네트워크 어댑터를 구성했습니다(필요한 경우) link:task_mnode_install_add_storage_NIC.html["추가 스토리지 NIC 구성"].
+

NOTE: eth0을 SVIP로 라우팅할 수 없는 경우 영구 볼륨에는 추가 네트워크 어댑터가 필요할 수 있습니다. 영구 볼륨의 구성을 허용하도록 iSCSI 스토리지 네트워크에서 새 네트워크 어댑터를 구성합니다.

* 스토리지 노드가 Element 11.3 이상을 실행하고 있습니다.


.단계
. SSH 또는 콘솔 액세스를 사용하여 관리 노드 가상 머신에 로그인합니다.
. 를 다운로드합니다 https://mysupport.netapp.com/site/products/all/details/netapp-hci/downloads-tab["관리 노드 ISO"^] NetApp HCI의 경우 NetApp Support 사이트에서 관리 노드 가상 시스템으로.
+

NOTE: ISO의 이름은 'olidfire-fdva-<Element release>-patchX-XX.X.XXXX.iso'와 비슷합니다

. 다운로드한 파일에 md5sum을 실행하여 다운로드의 무결성을 확인하고 다음 예제와 같이 NetApp HCI 또는 Element 소프트웨어에 대해 NetApp Support 사이트에서 제공되는 것과 출력을 비교합니다.
+
'SUDO md5sum -b <ISO>/solidfire-fdva-<Element release>-patchX-XX.X.XXXX.iso'

. 다음 명령을 사용하여 관리 노드 ISO 이미지를 마운트하고 파일 시스템에 내용을 복사합니다.
+
[listing]
----
sudo mkdir -p /upgrade
----
+
[listing]
----
sudo mount <solidfire-fdva-<Element release>-patchX-XX.X.X.XXXX.iso> /mnt
----
+
[listing]
----
sudo cp -r /mnt/* /upgrade
----
. 홈 디렉토리로 변경하고 '/mnt'에서 ISO 파일을 마운트 해제합니다.
+
[listing]
----
sudo umount /mnt
----
. 관리 노드의 공간을 절약하려면 ISO를 삭제합니다.
+
[listing]
----
sudo rm <path to iso>/solidfire-fdva-<Element release>-patchX-XX.X.X.XXXX.iso
----
. 업그레이드하는 관리 노드에서 다음 명령을 실행하여 관리 노드 OS 버전을 업그레이드합니다. 업그레이드 후 Active IQ Collector 및 프록시 설정과 같은 필요한 모든 구성 파일이 스크립트에 유지됩니다.
+
[listing]
----
sudo /sf/rtfi/bin/sfrtfi_inplace file:///upgrade/casper/filesystem.squashfs sf_upgrade=1
----
+
업그레이드 프로세스가 완료된 후 관리 노드가 새 OS로 재부팅됩니다.

+

NOTE: 이 단계에서 설명한 sudo 명령을 실행하면 SSH 세션이 종료됩니다. 지속적인 모니터링을 위해서는 콘솔 액세스가 필요합니다. 업그레이드를 수행할 때 콘솔 액세스가 없는 경우 SSH 로그인을 재시도하고 15분에서 30분 후에 연결을 확인합니다. 로그인하면 SSH 배너에서 업그레이드가 성공했음을 나타내는 새 OS 버전을 확인할 수 있습니다.

. 관리 노드에서 'redeploy-mnode' 스크립트를 실행하여 이전 관리 서비스 구성 설정을 유지합니다.
+

NOTE: 이 스크립트는 설정에 따라 Active IQ Collector 서비스, 컨트롤러(vCenter) 또는 프록시의 구성을 포함하여 이전 관리 서비스 구성을 유지합니다.

+
[listing]
----
sudo /sf/packages/mnode/redeploy-mnode -mu <mnode user>
----



IMPORTANT: 이전에 관리 노드에서 SSH 기능을 해제한 경우 를 수행해야 합니다 link:task_mnode_ssh_management.html["SSH를 다시 비활성화합니다"] 복구된 관리 노드에서 SSH 기능을 통해 제공됩니다 link:task_mnode_enable_remote_support_connections.html["NetApp RST(Remote Support Tunnel) 세션 액세스"] 는 기본적으로 관리 노드에서 사용하도록 설정됩니다.



== 관리 노드를 버전 12.3.x로 12.0에서 업그레이드합니다

새 관리 노드 가상 시스템을 프로비저닝할 필요 없이 관리 노드를 버전 12.0에서 버전 12.3.x로 데이터 이동 없이 업그레이드할 수 있습니다.


NOTE: Element 12.3.x 관리 노드는 선택적 업그레이드입니다. 기존 배포에는 필요하지 않습니다.

.무엇을 &#8217;필요로 할거야
* 업그레이드하려는 관리 노드는 버전 12.0이며 IPv4 네트워킹을 사용합니다. 관리 노드 버전 12.3.x는 IPv6을 지원하지 않습니다.
+

TIP: 관리 노드의 버전을 확인하려면 관리 노드에 로그인하고 로그인 배너에서 Element 버전 번호를 확인합니다.

* NetApp 하이브리드 클라우드 제어(HCC)를 사용하여 관리 서비스 번들을 최신 버전으로 업데이트했습니다. 다음 IP에서 HCC에 액세스할 수 있습니다. 'https://<ManagementNodeIP>`
* 관리 노드를 버전 12.3.x로 업데이트하는 경우 계속하려면 관리 서비스 2.14.60 이상이 필요합니다.
* 에 대한 지침을 사용하여 추가 네트워크 어댑터를 구성했습니다(필요한 경우) link:task_mnode_install_add_storage_NIC.html["추가 스토리지 NIC 구성"].
+

NOTE: eth0을 SVIP로 라우팅할 수 없는 경우 영구 볼륨에는 추가 네트워크 어댑터가 필요할 수 있습니다. 영구 볼륨의 구성을 허용하도록 iSCSI 스토리지 네트워크에서 새 네트워크 어댑터를 구성합니다.

* 스토리지 노드가 Element 11.3 이상을 실행하고 있습니다.


.단계
. 관리 노드 VM RAM 구성:
+
.. 관리 노드 VM의 전원을 끕니다.
.. 관리 노드 VM의 RAM을 12GB에서 24GB RAM으로 변경합니다.
.. 관리 노드 VM의 전원을 켭니다.


. SSH 또는 콘솔 액세스를 사용하여 관리 노드 가상 머신에 로그인합니다.
. 를 다운로드합니다 https://mysupport.netapp.com/site/products/all/details/netapp-hci/downloads-tab["관리 노드 ISO"^] NetApp HCI의 경우 NetApp Support 사이트에서 관리 노드 가상 시스템으로.
+

NOTE: ISO의 이름은 'olidfire-fdva-<Element release>-patchX-XX.X.XXXX.iso'와 비슷합니다

. 다운로드한 파일에 md5sum을 실행하여 다운로드의 무결성을 확인하고 다음 예제와 같이 NetApp HCI 또는 Element 소프트웨어에 대해 NetApp Support 사이트에서 제공되는 것과 출력을 비교합니다.
+
'SUDO md5sum -b <ISO>/solidfire-fdva-<Element release>-patchX-XX.X.XXXX.iso'

. 다음 명령을 사용하여 관리 노드 ISO 이미지를 마운트하고 파일 시스템에 내용을 복사합니다.
+
[listing]
----
sudo mkdir -p /upgrade
----
+
[listing]
----
sudo mount <solidfire-fdva-<Element release>-patchX-XX.X.X.XXXX.iso> /mnt
----
+
[listing]
----
sudo cp -r /mnt/* /upgrade
----
. 홈 디렉토리로 변경하고 '/mnt'에서 ISO 파일을 마운트 해제합니다.
+
[listing]
----
sudo umount /mnt
----
. 관리 노드의 공간을 절약하려면 ISO를 삭제합니다.
+
[listing]
----
sudo rm <path to iso>/solidfire-fdva-<Element release>-patchX-XX.X.X.XXXX.iso
----
. 업그레이드하는 관리 노드에서 다음 명령을 실행하여 관리 노드 OS 버전을 업그레이드합니다. 업그레이드 후 Active IQ Collector 및 프록시 설정과 같은 필요한 모든 구성 파일이 스크립트에 유지됩니다.
+
[listing]
----
sudo /sf/rtfi/bin/sfrtfi_inplace file:///upgrade/casper/filesystem.squashfs sf_upgrade=1
----
+
업그레이드 프로세스가 완료된 후 관리 노드가 새 OS로 재부팅됩니다.

+

NOTE: 이 단계에서 설명한 sudo 명령을 실행하면 SSH 세션이 종료됩니다. 지속적인 모니터링을 위해서는 콘솔 액세스가 필요합니다. 업그레이드를 수행할 때 콘솔 액세스가 없는 경우 SSH 로그인을 재시도하고 15분에서 30분 후에 연결을 확인합니다. 로그인하면 SSH 배너에서 업그레이드가 성공했음을 나타내는 새 OS 버전을 확인할 수 있습니다.

. 관리 노드에서 'redeploy-mnode' 스크립트를 실행하여 이전 관리 서비스 구성 설정을 유지합니다.
+

NOTE: 이 스크립트는 설정에 따라 Active IQ Collector 서비스, 컨트롤러(vCenter) 또는 프록시의 구성을 포함하여 이전 관리 서비스 구성을 유지합니다.

+
[listing]
----
sudo /sf/packages/mnode/redeploy-mnode -mu <mnode user>
----



IMPORTANT: SSH 기능을 통해 제공됩니다 link:task_mnode_enable_remote_support_connections.html["NetApp RST(Remote Support Tunnel) 세션 액세스"] 관리 서비스 2.18 이상을 실행하는 관리 노드에서 기본적으로 이 비활성화됩니다. 이전에 관리 노드에서 SSH 기능을 활성화한 경우 가 필요할 수 있습니다 link:task_mnode_ssh_management.html["SSH를 다시 비활성화합니다"] 업그레이드 된 관리 노드에서.



== 관리 노드를 버전 12.3.x로 11.3에서 11.8로 업그레이드합니다

새 관리 노드 가상 머신을 프로비저닝하지 않고도 버전 11.3, 11.5, 11.7 또는 11.8에서 버전 12.3.x로 관리 노드의 데이터 이동 없이 업그레이드할 수 있습니다.


NOTE: Element 12.3.x 관리 노드는 선택적 업그레이드입니다. 기존 배포에는 필요하지 않습니다.

.무엇을 &#8217;필요로 할거야
* 업그레이드하려는 관리 노드는 버전 11.3, 11.5, 11.7 또는 11.8이며 IPv4 네트워킹을 사용합니다. 관리 노드 버전 12.3.x는 IPv6을 지원하지 않습니다.
+

TIP: 관리 노드의 버전을 확인하려면 관리 노드에 로그인하고 로그인 배너에서 Element 버전 번호를 확인합니다.

* NetApp 하이브리드 클라우드 제어(HCC)를 사용하여 관리 서비스 번들을 최신 버전으로 업데이트했습니다. 다음 IP에서 HCC에 액세스할 수 있습니다. 'https://<ManagementNodeIP>`
* 관리 노드를 버전 12.3.x로 업데이트하는 경우 계속하려면 관리 서비스 2.14.60 이상이 필요합니다.
* 에 대한 지침을 사용하여 추가 네트워크 어댑터를 구성했습니다(필요한 경우) link:task_mnode_install_add_storage_NIC.html["추가 스토리지 NIC 구성"].
+

NOTE: eth0을 SVIP로 라우팅할 수 없는 경우 영구 볼륨에는 추가 네트워크 어댑터가 필요할 수 있습니다. 영구 볼륨의 구성을 허용하도록 iSCSI 스토리지 네트워크에서 새 네트워크 어댑터를 구성합니다.

* 스토리지 노드가 Element 11.3 이상을 실행하고 있습니다.


.단계
. 관리 노드 VM RAM 구성:
+
.. 관리 노드 VM의 전원을 끕니다.
.. 관리 노드 VM의 RAM을 12GB에서 24GB RAM으로 변경합니다.
.. 관리 노드 VM의 전원을 켭니다.


. SSH 또는 콘솔 액세스를 사용하여 관리 노드 가상 머신에 로그인합니다.
. 를 다운로드합니다 https://mysupport.netapp.com/site/products/all/details/netapp-hci/downloads-tab["관리 노드 ISO"^] NetApp HCI의 경우 NetApp Support 사이트에서 관리 노드 가상 시스템으로.
+

NOTE: ISO의 이름은 'olidfire-fdva-<Element release>-patchX-XX.X.XXXX.iso'와 비슷합니다

. 다운로드한 파일에 md5sum을 실행하여 다운로드의 무결성을 확인하고 다음 예제와 같이 NetApp HCI 또는 Element 소프트웨어에 대해 NetApp Support 사이트에서 제공되는 것과 출력을 비교합니다.
+
'SUDO md5sum -b <ISO>/solidfire-fdva-<Element release>-patchX-XX.X.XXXX.iso'

. 다음 명령을 사용하여 관리 노드 ISO 이미지를 마운트하고 파일 시스템에 내용을 복사합니다.
+
[listing]
----
sudo mkdir -p /upgrade
----
+
[listing]
----
sudo mount <solidfire-fdva-<Element release>-patchX-XX.X.X.XXXX.iso> /mnt
----
+
[listing]
----
sudo cp -r /mnt/* /upgrade
----
. 홈 디렉토리로 변경하고 '/mnt'에서 ISO 파일을 마운트 해제합니다.
+
[listing]
----
sudo umount /mnt
----
. 관리 노드의 공간을 절약하려면 ISO를 삭제합니다.
+
[listing]
----
sudo rm <path to iso>/solidfire-fdva-<Element release>-patchX-XX.X.X.XXXX.iso
----
. 11.3, 11.5, 11.7 또는 11.8 관리 노드에서 다음 명령을 실행하여 관리 노드 OS 버전을 업그레이드합니다. 업그레이드 후 Active IQ Collector 및 프록시 설정과 같은 필요한 모든 구성 파일이 스크립트에 유지됩니다.
+
[listing]
----
sudo /sf/rtfi/bin/sfrtfi_inplace file:///upgrade/casper/filesystem.squashfs sf_upgrade=1
----
+
업그레이드 프로세스가 완료된 후 관리 노드가 새 OS로 재부팅됩니다.

+

NOTE: 이 단계에서 설명한 sudo 명령을 실행하면 SSH 세션이 종료됩니다. 지속적인 모니터링을 위해서는 콘솔 액세스가 필요합니다. 업그레이드를 수행할 때 콘솔 액세스가 없는 경우 SSH 로그인을 재시도하고 15분에서 30분 후에 연결을 확인합니다. 로그인하면 SSH 배너에서 업그레이드가 성공했음을 나타내는 새 OS 버전을 확인할 수 있습니다.

. 관리 노드에서 'redeploy-mnode' 스크립트를 실행하여 이전 관리 서비스 구성 설정을 유지합니다.
+

NOTE: 이 스크립트는 설정에 따라 Active IQ Collector 서비스, 컨트롤러(vCenter) 또는 프록시의 구성을 포함하여 이전 관리 서비스 구성을 유지합니다.

+
[listing]
----
sudo /sf/packages/mnode/redeploy-mnode -mu <mnode user>
----



IMPORTANT: SSH 기능을 통해 제공됩니다 link:task_mnode_enable_remote_support_connections.html["NetApp RST(Remote Support Tunnel) 세션 액세스"] 관리 서비스 2.18 이상을 실행하는 관리 노드에서 기본적으로 이 비활성화됩니다. 이전에 관리 노드에서 SSH 기능을 활성화한 경우 가 필요할 수 있습니다 link:task_mnode_ssh_management.html["SSH를 다시 비활성화합니다"] 업그레이드 된 관리 노드에서.



== 관리 노드를 11.1 또는 11.0에서 버전 12.3.x로 업그레이드합니다

새 관리 노드 가상 머신을 프로비저닝하지 않고도 관리 노드를 11.0 또는 11.1에서 버전 12.3.x로 업그레이드할 수 있습니다.

.무엇을 &#8217;필요로 할거야
* 스토리지 노드가 Element 11.3 이상을 실행하고 있습니다.
+

NOTE: 최신 HealthTools를 사용하여 Element 소프트웨어를 업그레이드합니다.

* 업그레이드하려는 관리 노드는 버전 11.0 또는 11.1이며 IPv4 네트워킹을 사용합니다. 관리 노드 버전 12.3.x는 IPv6을 지원하지 않습니다.
+

TIP: 관리 노드의 버전을 확인하려면 관리 노드에 로그인하고 로그인 배너에서 Element 버전 번호를 확인합니다.

* 관리 노드 11.0의 경우 VM 메모리를 수동으로 12GB로 늘려야 합니다.
* 관리 노드의 사용자 가이드에서 스토리지 NIC(eth1)를 구성하는 지침을 사용하여 추가 네트워크 어댑터(필요한 경우)를 구성했습니다.
+

NOTE: eth0을 SVIP로 라우팅할 수 없는 경우 영구 볼륨에는 추가 네트워크 어댑터가 필요할 수 있습니다. 영구 볼륨의 구성을 허용하도록 iSCSI 스토리지 네트워크에서 새 네트워크 어댑터를 구성합니다.



.단계
. 관리 노드 VM RAM 구성:
+
.. 관리 노드 VM의 전원을 끕니다.
.. 관리 노드 VM의 RAM을 12GB에서 24GB RAM으로 변경합니다.
.. 관리 노드 VM의 전원을 켭니다.


. SSH 또는 콘솔 액세스를 사용하여 관리 노드 가상 머신에 로그인합니다.
. 를 다운로드합니다 https://mysupport.netapp.com/site/products/all/details/netapp-hci/downloads-tab["관리 노드 ISO"^] NetApp HCI의 경우 NetApp Support 사이트에서 관리 노드 가상 시스템으로.
+

NOTE: ISO의 이름은 'olidfire-fdva-<Element release>-patchX-XX.X.XXXX.iso'와 비슷합니다

. 다운로드한 파일에 md5sum을 실행하여 다운로드의 무결성을 확인하고 다음 예제와 같이 NetApp HCI 또는 Element 소프트웨어에 대해 NetApp Support 사이트에서 제공되는 것과 출력을 비교합니다.
+
[listing]
----
sudo md5sum -b <path to iso>/solidfire-fdva-<Element release>-patchX-XX.X.X.XXXX.iso
----
. 다음 명령을 사용하여 관리 노드 ISO 이미지를 마운트하고 파일 시스템에 내용을 복사합니다.
+
[listing]
----
sudo mkdir -p /upgrade
----
+
[listing]
----
sudo mount solidfire-fdva-<Element release>-patchX-XX.X.X.XXXX.iso /mnt
----
+
[listing]
----
sudo cp -r /mnt/* /upgrade
----
. 홈 디렉토리로 변경하고 /mnt에서 ISO 파일을 마운트 해제합니다.
+
[listing]
----
sudo umount /mnt
----
. 관리 노드의 공간을 절약하려면 ISO를 삭제합니다.
+
[listing]
----
sudo rm <path to iso>/solidfire-fdva-<Element release>-patchX-XX.X.X.XXXX.iso
----
. 관리 노드 OS 버전을 업그레이드할 수 있는 옵션을 사용하여 다음 스크립트 중 하나를 실행합니다. 해당 버전에 맞는 스크립트만 실행합니다. 각 스크립트는 업그레이드 후 Active IQ Collector 및 프록시 설정과 같은 필요한 모든 구성 파일을 보존합니다.
+
.. 11.1(11.1.0.73) 관리 노드에서 다음 명령을 실행합니다.
+
[listing]
----
sudo /sf/rtfi/bin/sfrtfi_inplace file:///upgrade/casper/filesystem.squashfs sf_upgrade=1 sf_keep_paths="/sf/packages/solidfire-sioc-4.2.3.2288 /sf/packages/solidfire-nma-1.4.10/conf /sf/packages/sioc /sf/packages/nma"
----
.. 11.1(11.1.0.72) 관리 노드에서 다음 명령을 실행합니다.
+
[listing]
----
sudo /sf/rtfi/bin/sfrtfi_inplace file:///upgrade/casper/filesystem.squashfs sf_upgrade=1 sf_keep_paths="/sf/packages/solidfire-sioc-4.2.1.2281 /sf/packages/solidfire-nma-1.4.10/conf /sf/packages/sioc /sf/packages/nma"
----
.. 11.0(11.0.0.781) 관리 노드에서 다음 명령을 실행합니다.
+
[listing]
----
sudo /sf/rtfi/bin/sfrtfi_inplace file:///upgrade/casper/filesystem.squashfs sf_upgrade=1 sf_keep_paths="/sf/packages/solidfire-sioc-4.2.0.2253 /sf/packages/solidfire-nma-1.4.8/conf /sf/packages/sioc /sf/packages/nma"
----
+
업그레이드 프로세스가 완료된 후 관리 노드가 새 OS로 재부팅됩니다.

+

NOTE: 이 단계에서 설명한 sudo 명령을 실행하면 SSH 세션이 종료됩니다. 지속적인 모니터링을 위해서는 콘솔 액세스가 필요합니다. 업그레이드를 수행할 때 콘솔 액세스가 없는 경우 SSH 로그인을 재시도하고 15분에서 30분 후에 연결을 확인합니다. 로그인하면 SSH 배너에서 업그레이드가 성공했음을 나타내는 새 OS 버전을 확인할 수 있습니다.



. 12.3.x 관리 노드에서 'upgrade-mnode' 스크립트를 실행하여 이전 구성 설정을 유지합니다.
+

NOTE: 11.0 또는 11.1 관리 노드에서 마이그레이션하는 경우 스크립트는 Active IQ 수집기를 새 구성 형식으로 복사합니다.

+
.. 영구 볼륨과 함께 기존 관리 노드 11.0 또는 11.1에서 관리되는 단일 스토리지 클러스터의 경우:
+
[listing]
----
sudo /sf/packages/mnode/upgrade-mnode -mu <mnode user> -pv <true - persistent volume> -pva <persistent volume account name - storage volume account>
----
.. 영구 볼륨이 없는 기존 관리 노드 11.0 또는 11.1에서 관리되는 단일 스토리지 클러스터의 경우:
+
[listing]
----
sudo /sf/packages/mnode/upgrade-mnode -mu <mnode user>
----
.. 영구 볼륨과 함께 기존 관리 노드 11.0 또는 11.1에서 관리되는 여러 스토리지 클러스터의 경우:
+
[listing]
----
sudo /sf/packages/mnode/upgrade-mnode -mu <mnode user> -pv <true - persistent volume> -pva <persistent volume account name - storage volume account> -pvm <persistent volumes mvip>
----
.. 영구 볼륨이 없는 기존 관리 노드 11.0 또는 11.1에서 관리되는 여러 스토리지 클러스터의 경우("-PVM" 플래그는 클러스터의 MVIP 주소 중 하나를 제공하는 것입니다):
+
[listing]
----
sudo /sf/packages/mnode/upgrade-mnode -mu <mnode user> -pvm <mvip for persistent volumes>
----


. (vCenter Server용 NetApp Element 플러그인을 사용하는 모든 NetApp HCI 설치의 경우) 의 단계에 따라 12.3.x 관리 노드에서 vCenter 플러그인을 업데이트합니다 link:task_vcp_upgrade_plugin.html["vCenter Server용 Element 플러그인을 업그레이드합니다"] 주제.
. 관리 노드 API를 사용하여 설치의 자산 ID를 찾습니다.
+
.. 브라우저에서 관리 노드 REST API UI에 로그인합니다.
+
... 스토리지 MVIP로 이동하여 로그인합니다. 이 작업을 수행하면 다음 단계에서 인증서가 수락됩니다.


.. 관리 노드에서 인벤토리 서비스 REST API UI를 엽니다.
+
[listing]
----
https://<ManagementNodeIP>/inventory/1/
----
.. authorize * 를 선택하고 다음을 완료합니다.
+
... 클러스터 사용자 이름 및 암호를 입력합니다.
... Client ID를 mnode-client로 입력한다.
... 세션을 시작하려면 * authorize * 를 선택합니다.
... 창을 닫습니다.


.. REST API UI에서 * Get Windows/Installations * 를 선택합니다.
.. 체험하기 * 를 선택합니다.
.. Execute * 를 선택합니다.
.. 코드 200 응답 본문에서 설치 시 id를 복사한다.
+
설치 또는 업그레이드 중에 생성된 기본 자산 구성을 설치하였습니다.



. vSphere에서 컴퓨팅 노드의 하드웨어 태그를 찾습니다.
+
.. vSphere Web Client 탐색기에서 호스트를 선택합니다.
.. 모니터 * 탭을 선택하고 * 하드웨어 상태 * 를 선택합니다.
.. 노드 BIOS 제조업체 및 모델 번호가 나열됩니다. 나중 단계에서 사용할 'tag'의 값을 복사하여 저장합니다.


. HCI 모니터링 및 하이브리드 클라우드 제어에 대한 vCenter 컨트롤러 자산을 관리 노드의 알려진 자산에 추가합니다.
+
.. 컨트롤러 하위 자산을 추가하려면 * POST/ASSET/{ASSET_ID}/컨트롤러 * 를 선택합니다.
.. 체험하기 * 를 선택합니다.
.. 클립보드에 복사한 상위 기본 자산 ID를 * asset_id * 필드에 입력합니다.
.. 유형 'vCenter'와 vCenter 자격 증명을 사용하여 필요한 페이로드 값을 입력합니다.
.. Execute * 를 선택합니다.


. 컴퓨팅 노드 자산을 관리 노드의 알려진 자산에 추가합니다.
+
.. 컴퓨팅 노드 자산에 대한 자격 증명이 있는 컴퓨팅 노드 하위 자산을 추가하려면 * POST/ASSET/{ASSET_ID}/컴퓨팅 노드 * 를 선택합니다.
.. 체험하기 * 를 선택합니다.
.. 클립보드에 복사한 상위 기본 자산 ID를 * asset_id * 필드에 입력합니다.
.. 페이로드에서 Model(모델) 탭에 정의된 대로 필요한 페이로드 값을 입력합니다. type로 ESXi Host를 입력하고, hardware_tag의 이전 단계에서 저장한 하드웨어 태그를 붙여넣습니다.
.. Execute * 를 선택합니다.






== 관리 노드 버전 10.x에서 11.x로 마이그레이션

버전 10.x의 관리 노드가 있는 경우 10.x에서 11.x로 업그레이드할 수 없습니다 대신 이 마이그레이션 절차를 사용하여 구성을 10.x에서 새로 배포된 11.1 관리 노드로 복사할 수 있습니다. 관리 노드가 현재 11.0 이상인 경우 이 절차를 건너뛰어야 합니다. 관리 노드 11.0 또는 11.1과 가 필요합니다 link:task_upgrade_element_latest_healthtools.html["최신 상태 진단 도구"] Element 소프트웨어를 10.3 이상에서 11.x로 업그레이드하려면

.단계
. VMware vSphere 인터페이스에서 관리 노드 11.1 OVA를 구축하고 전원을 켭니다.
. 터미널 사용자 인터페이스(TUI)를 가져오는 관리 노드 VM 콘솔을 엽니다.
. TUI를 사용하여 새 관리자 ID를 만들고 암호를 지정합니다.
. 관리 노드 TUI에서 새 ID와 암호를 사용하여 관리 노드에 로그인하고 작동 여부를 확인합니다.
. vCenter 또는 관리 노드 TUI에서 관리 노드 11.1 IP 주소를 가져온 다음 포트 9443의 IP 주소로 이동하여 관리 노드 UI를 엽니다.
+
[listing]
----
https://<mNode 11.1 IP address>:9443
----
. vSphere에서 * NetApp Element 구성 * > * mNode 설정 * 을 선택합니다. (이전 버전에서는 최상위 메뉴가 * NetApp SolidFire 구성 * 입니다.)
. Actions * > * Clear * 를 선택합니다.
. 확인하려면 * 예 * 를 선택합니다. mNode Status 필드는 구성되지 않음을 보고해야 합니다.
+

NOTE: mNode 설정 * 탭으로 처음 이동하면 예상 * 업 * 대신 * 구성되지 않음 * 으로 mNode 상태 필드가 표시될 수 있습니다. * 작업 * > * 지우기 * 를 선택하지 못할 수도 있습니다. 브라우저를 새로 고칩니다. mNode Status(mNode 상태) 필드에 최종적으로 * up * 이 표시됩니다.

. vSphere에서 로그아웃합니다.
. 웹 브라우저에서 관리 노드 등록 유틸리티를 열고 * QoSSIOC 서비스 관리 * 를 선택합니다.
+
[listing]
----
https://<mNode 11.1 IP address>:9443
----
. 새 QoSSIOC 암호를 설정합니다.
+

NOTE: 기본 비밀번호는 SolidFire입니다. 새 암호를 설정하려면 이 암호가 필요합니다.

. vCenter 플러그인 등록 * 탭을 선택합니다.
. Update Plug-in * 을 선택합니다.
. 필요한 값을 입력합니다. 완료되면 * 업데이트 * 를 선택합니다.
. vSphere에 로그인하고 * NetApp Element 구성 * > * mNode 설정 * 을 선택합니다.
. Actions * > * Configure * 를 선택합니다.
. 관리 노드 IP 주소, 관리 노드 사용자 ID(사용자 이름은 "admin"), 등록 유틸리티의 * QoSSIOC 서비스 관리 * 탭에서 설정한 암호, vCenter 사용자 ID 및 암호를 제공합니다.
+
vSphere에서 * mNode Settings * (mNode 설정 *) 탭은 mNode 상태를 * up * 으로 표시해야 합니다. 이는 관리 노드 11.1이 vCenter에 등록되었음을 나타냅니다.

. 관리 노드 등록 유틸리티('https://<mNode 11.1 IP 주소>:9443')에서 * QoSSIOC 서비스 관리 * 에서 SIOC 서비스를 다시 시작합니다.
. 1분 정도 기다린 후 * NetApp Element 구성 * > * mNode 설정 * 탭을 확인합니다. 그러면 mNode 상태가 * Up * 으로 표시됩니다.
+
상태가 * DOWN * 인 경우 '/sf/packages/sIOC/app.properties` 에 대한 권한을 확인합니다. 파일에 파일 소유자의 읽기, 쓰기 및 실행 권한이 있어야 합니다. 올바른 사용 권한은 다음과 같이 표시되어야 합니다.

+
[listing]
----
-rwx------
----
. SIOC 프로세스가 시작되고 vCenter에서 mNode 상태가 * UP * 으로 표시되면 관리 노드에서 'f-hci-nma' 서비스의 로그를 확인합니다. 오류 메시지가 없어야 합니다.
. (관리 노드 11.1에만 해당) 루트 권한으로 관리 노드 버전 11.1에 SSH를 수행하고 다음 명령을 사용하여 NMA 서비스를 시작합니다.
+
[listing]
----
# systemctl enable /sf/packages/nma/systemd/sf-hci-nma.service
----
+
[listing]
----
# systemctl start sf-hci-nma21
----
. vCenter에서 작업을 수행하여 드라이브를 제거하거나 드라이브를 추가하거나 노드를 재부팅합니다. 그러면 vCenter에서 보고해야 하는 스토리지 알림이 트리거됩니다. 이 기능이 작동하면 NMA 시스템 경고가 예상대로 작동합니다.
. vCenter에서 ONTAP Select가 설정된 경우, 이전 관리 노드의 .ots.properties` 파일을 관리 노드 버전 11.1로 복사하여 NMA에서 ONTAP Select alerts를 구성하고, 다음 .ots.properties` 명령어를 이용하여 NMA 서비스를 다시 시작한다.
+
[listing]
----
systemctl restart sf-hci-nma
----
. 다음 명령을 사용하여 로그를 확인하여 ONTAP Select가 작동하는지 확인합니다.
+
[listing]
----
journalctl -f | grep -i ots
----
. 다음을 수행하여 Active IQ를 구성합니다.
+
.. 관리 노드 버전 11.1에 SSH를 장착하고 '/sf/packages/collector' 디렉토리로 이동합니다.
.. 다음 명령을 실행합니다.
+
[listing]
----
sudo ./manage-collector.py --set-username netapp --set-password --set-mvip <MVIP>
----
.. 메시지가 표시되면 관리 노드 UI 암호를 입력합니다.
.. 다음 명령을 실행합니다.
+
[listing]
----
./manage-collector.py --get-all
----
+
[listing]
----
sudo systemctl restart sfcollector
----
.. '스수집기' 로그를 확인하여 제대로 작동하는지 확인합니다.


. vSphere에서 * NetApp Element 구성 * > * mNode 설정 * 탭은 mNode 상태를 * up * 으로 표시해야 합니다.
. NMA가 시스템 알림 및 ONTAP Select 경고를 보고하는지 확인합니다.
. 모든 것이 예상대로 작동하는 경우 관리 노드 10.x VM을 종료하고 삭제합니다.




== 관리 노드 REST API를 사용하여 인증을 재구성합니다

(1) 관리 서비스 및 (2) Element 스토리지를 순차적으로 업그레이드한 경우 기존 관리 노드를 유지할 수 있습니다. 다른 업그레이드 순서를 따르는 경우 현재 위치 관리 노드 업그레이드 절차를 참조하십시오.

.시작하기 전에
* 관리 서비스를 2.10.29 이상으로 업데이트했습니다.
* 스토리지 클러스터에서 Element 12.0 이상이 실행되고 있습니다.
* 관리 노드는 11.3 이상이어야 합니다.
* Element 스토리지를 업그레이드한 후 관리 서비스를 순차적으로 업데이트했습니다. 설명된 순서대로 업그레이드를 완료하지 않으면 이 절차를 사용하여 인증을 다시 구성할 수 없습니다.


.단계
. 관리 노드에서 관리 노드 REST API UI를 엽니다.
+
[listing]
----
https://<ManagementNodeIP>/mnode
----
. authorize * 를 선택하고 다음을 완료합니다.
+
.. 클러스터 사용자 이름 및 암호를 입력합니다.
.. 값이 아직 채워지지 않은 경우 클라이언트 ID를 mnode-client로 입력합니다.
.. 세션을 시작하려면 * authorize * 를 선택합니다.


. REST API UI에서 * POST/services/reconfigure-auth * 를 선택합니다.
. 체험하기 * 를 선택합니다.
. load_images * 매개 변수에 대해 'true'를 선택합니다.
. Execute * 를 선택합니다.
+
응답 본문은 재구성이 성공했음을 나타냅니다.



[discrete]
== 자세한 내용을 확인하십시오

* https://docs.netapp.com/us-en/vcp/index.html["vCenter Server용 NetApp Element 플러그인"^]
* https://www.netapp.com/hybrid-cloud/hci-documentation/["NetApp HCI 리소스 페이지 를 참조하십시오"^]

