---
sidebar: sidebar 
permalink: docs/task_hcc_upgrade_storage_firmware.html 
summary: NetApp HCI 시스템 업그레이드의 일환으로 스토리지 노드와 연결된 펌웨어를 업그레이드합니다. 
keywords: netapp, element, hcc, firmware, storage firmware 
---
= 스토리지 펌웨어를 업그레이드합니다
:allow-uri-read: 


[role="lead"]
Element 12.0 및 관리 서비스 버전 2.14부터 NetApp 하이브리드 클라우드 제어 UI 및 REST API를 사용하여 스토리지 노드에서 펌웨어 전용 업그레이드를 수행할 수 있습니다. 이 절차에서는 Element 소프트웨어를 업그레이드하지 않으며 주요 Element 릴리스 외부에서 스토리지 펌웨어를 업그레이드할 수 있습니다.

.무엇을 &#8217;필요로 할거야
* * 관리자 권한 *: 업그레이드를 수행할 수 있는 스토리지 클러스터 관리자 권한이 있습니다.
* * 시스템 시간 동기화 *: 모든 노드의 시스템 시간이 동기화되고 스토리지 클러스터 및 노드에 대해 NTP가 올바르게 구성되었는지 확인했습니다. 각 노드는 시간편중과 관련된 해결되지 않은 클러스터 장애가 없는 노드별 웹 UI('https://[IP address]:442')에서 DNS 이름 서버로 구성되어야 합니다.
* * 시스템 포트 *: 업그레이드에 NetApp 하이브리드 클라우드 제어를 사용하는 경우 필요한 포트가 열려 있는지 확인했습니다. 을 참조하십시오 link:hci_prereqs_required_network_ports.html["네트워크 포트"] 를 참조하십시오.
* * 관리 노드 *: NetApp 하이브리드 클라우드 제어 UI 및 API의 경우, 사용자 환경의 관리 노드에서 버전 11.3이 실행되고 있습니다.
* * 관리 서비스 *: 관리 서비스 번들을 최신 버전으로 업데이트했습니다.



IMPORTANT: Element 소프트웨어 버전 12.0을 실행하는 H610S 스토리지 노드의 경우 스토리지 펌웨어 번들 2.27로 업그레이드하기 전에 D-패치 SUST-909를 적용해야 합니다. 업그레이드하기 전에 NetApp Support에서 D-패치를 받으려면 먼저 NetApp Support에 문의하십시오. 을 참조하십시오 link:http://docs.netapp.com/us-en/hci/docs/rn_storage_firmware_2.27.html["스토리지 펌웨어 번들 2.27 릴리스 정보"^].


IMPORTANT: 스토리지 노드의 펌웨어를 업그레이드하기 전에 최신 관리 서비스 번들로 업그레이드해야 합니다. Element 소프트웨어를 버전 12.2 이상으로 업데이트하는 경우 계속하려면 관리 서비스 2.14.60 이상이 필요합니다.


IMPORTANT: iDRAC/BIOS 펌웨어를 업데이트하려면 NetApp 지원 에 문의하십시오. 자세한 내용은 다음을 참조하십시오 link:https://kb.netapp.com/Advice_and_Troubleshooting/Flash_Storage/SF_Series/How_to_update_iDRAC%2F%2FBIOS_firmware_on_SF_Series_nodes["KB 문서를 참조하십시오"^].

* * 클러스터 상태 *: 상태 점검을 실행하였습니다. 을 참조하십시오 link:task_hcc_upgrade_element_prechecks.html["스토리지를 업그레이드하기 전에 Element 스토리지 상태 점검을 실행합니다"].
* * H610S 노드의 업데이트된 BMC *: H610S 노드의 BMC 버전을 업그레이드했습니다. 을 참조하십시오 link:rn_H610S_BMC_3.84.07.html["릴리스 정보 및 업그레이드 지침"^].



NOTE: 하드웨어에 대한 펌웨어 및 드라이버 펌웨어의 전체 매트릭스를 보려면 다음을 참조하십시오 https://kb.netapp.com/Advice_and_Troubleshooting/Hybrid_Cloud_Infrastructure/NetApp_HCI/Firmware_and_driver_versions_in_NetApp_HCI_and_NetApp_Element_software["KB 문서를 참조하십시오"^] (로그인 필요).

* * 최종 사용자 라이센스 계약(EULA) *: 관리 서비스 2.20부터 NetApp 하이브리드 클라우드 제어 UI 또는 API를 사용하여 스토리지 펌웨어를 업그레이드하기 전에 EULA에 동의하고 저장해야 합니다.
+
.. 웹 브라우저에서 관리 노드의 IP 주소를 엽니다.
+
[listing]
----
https://<ManagementNodeIP>
----
.. NetApp 하이브리드 클라우드 제어에 스토리지 클러스터 관리자 자격 증명을 제공하여 로그인하십시오.
.. 인터페이스의 오른쪽 상단 근처에 있는 * Upgrade * 를 선택합니다.
.. EULA가 나타납니다. 아래로 스크롤하여 * 현재 업데이트 및 향후 모든 업데이트에 동의함 * 을 선택하고 * 저장 * 을 선택합니다.
+

NOTE: EULA에 동의하면 향후 모든 업데이트에 대해 기록되고 자동 다운로드 기능이 활성화됩니다. NetApp 소프트웨어 업데이트 및 업그레이드 관련 업데이트는 고유 권한으로 설치할 수 있습니다. NetApp 온라인 소프트웨어 저장소에 대한 네트워크 연결을 비활성화하여 자동 다운로드 기능을 비활성화할 수 있습니다.





다음 스토리지 펌웨어 업그레이드 옵션 중 하나를 선택합니다.

* <<Use NetApp Hybrid Cloud Control UI to upgrade storage firmware>>
* <<Use NetApp Hybrid Cloud Control API to upgrade storage firmware>>




== NetApp 하이브리드 클라우드 제어 UI를 사용하여 스토리지 펌웨어를 업그레이드하십시오

NetApp 하이브리드 클라우드 제어 UI를 사용하여 클러스터에 있는 스토리지 노드의 펌웨어를 업그레이드할 수 있습니다.

관리 노드가 인터넷에 연결되어 있지 않은 경우 이 있는 것입니다 https://mysupport.netapp.com/site/products/all/details/element-software/downloads-tab/download/62654/Storage_Firmware_Bundle["NetApp HCI 스토리지 클러스터용 스토리지 펌웨어 패키지를 다운로드했습니다"^].


CAUTION: NetApp 하이브리드 클라우드 제어를 사용하여 스토리지 클러스터를 업그레이드하는 동안 발생할 수 있는 문제와 그 해결 방법은 을 참조하십시오 https://kb.netapp.com/Advice_and_Troubleshooting/Hybrid_Cloud_Infrastructure/NetApp_HCI/Potential_issues_and_workarounds_when_running_storage_upgrades_using_NetApp_Hybrid_Cloud_Control["KB 문서를 참조하십시오"^].


TIP: 업그레이드 프로세스는 스토리지 노드당 약 30분이 소요됩니다. Element 스토리지 클러스터를 버전 2.76 이상의 스토리지 펌웨어로 업그레이드하는 경우, 개별 스토리지 노드는 새 펌웨어가 노드에 기록된 경우에만 업그레이드 중에 재부팅됩니다.

.단계
. 웹 브라우저에서 관리 노드의 IP 주소를 엽니다.
+
[listing]
----
https://<ManagementNodeIP>
----
. NetApp 하이브리드 클라우드 제어에 스토리지 클러스터 관리자 자격 증명을 제공하여 로그인하십시오.
. 인터페이스의 오른쪽 상단 근처에 있는 * Upgrade * 를 선택합니다.
. 업그레이드 * 페이지에서 * 스토리지 * 를 선택합니다.
+

NOTE: Storage * 탭에는 설치에 포함된 스토리지 클러스터가 나열됩니다. NetApp Hybrid Cloud Control에서 클러스터에 액세스할 수 없는 경우 * 업그레이드 * 페이지에 표시되지 않습니다. Element 12.0 이상을 실행하는 클러스터가 있는 경우 이러한 클러스터에 대해 현재 펌웨어 번들 버전이 나열됩니다. 단일 클러스터의 노드가 서로 다른 펌웨어 버전을 가지고 있거나 업그레이드가 진행되는 동안 * Current Firmware Bundle Version * (현재 펌웨어 번들 버전 *) 열에 * Multiple * (다중 *)이 표시됩니다. 여러 * 를 선택하여 * 노드 * 페이지로 이동하여 펌웨어 버전을 비교할 수 있습니다. 모든 클러스터가 12.0 이전 버전의 Element를 실행하는 경우 펌웨어 번들 버전 번호에 대한 정보가 표시되지 않습니다. 이 정보는 * 노드 * 페이지에서도 사용할 수 있습니다. 을 참조하십시오 link:task_hcc_nodes.html["재고를 확인하십시오"]. 클러스터가 최신 버전이거나 사용 가능한 업그레이드 패키지가 없는 경우 * Element * 및 * Firmware Only * 탭이 표시되지 않습니다. 이 탭은 업그레이드가 진행 중일 때도 표시되지 않습니다. Element * 탭이 표시되지만 * Firmware Only * 탭이 표시되지 않으면 사용 가능한 펌웨어 패키지가 없습니다.

. 다음 옵션 중 하나를 선택하고 클러스터에 적용할 수 있는 단계 세트를 수행합니다.
+
[cols="2*"]
|===
| 옵션을 선택합니다 | 단계 


| 관리 노드에 외부 연결이 있습니다.  a| 
.. 업그레이드할 클러스터 옆에 있는 드롭다운 화살표를 선택합니다.
.. 펌웨어 전용 * 을 선택하고 사용 가능한 업그레이드 버전 중에서 선택합니다.
.. 업그레이드 시작 * 을 선택합니다.



TIP: 업그레이드 중 * 업그레이드 상태 * 는 프로세스 상태를 반영하기 위해 변경됩니다. 또한 업그레이드를 일시 중지하거나 업그레이드가 오류를 반환하는 경우와 같이 수행한 작업에 대한 응답으로 변경됩니다. 을 참조하십시오 <<Upgrade status changes>>.


NOTE: 업그레이드가 진행되는 동안 페이지를 종료하고 나중에 다시 돌아와 진행 상황을 계속 모니터링할 수 있습니다. 클러스터 행이 축소되어 있는 경우 이 페이지는 상태 및 현재 버전을 동적으로 업데이트하지 않습니다. 테이블을 업데이트하거나 페이지를 새로 고치려면 클러스터 행을 확장해야 합니다.

업그레이드가 완료된 후 로그를 다운로드할 수 있습니다.



| 관리 노드는 외부 연결이 없는 어두운 사이트 내에 있습니다.  a| 
.. 업그레이드할 클러스터 옆에 있는 드롭다운 화살표를 선택합니다.
.. 다운로드한 업그레이드 패키지를 업로드하려면 * 찾아보기 * 를 선택합니다.
.. 업로드가 완료될 때까지 기다립니다. 진행률 표시줄에 업로드 상태가 표시됩니다.



CAUTION: 브라우저 창에서 이동하면 파일 업로드가 손실됩니다.

파일이 성공적으로 업로드 및 확인되면 화면에 메시지가 표시됩니다. 정품 확인에 몇 분 정도 걸릴 수 있습니다. 이 단계에서 브라우저 창에서 다른 곳으로 이동하면 파일 업로드가 유지됩니다. 업그레이드가 완료된 후 로그를 다운로드할 수 있습니다. 다양한 업그레이드 상태 변경에 대한 자세한 내용은 을 참조하십시오 <<Upgrade status changes>>.

|===




=== 업그레이드 상태 변경

업그레이드 프로세스 전, 도중 및 이후에 UI의 * 업그레이드 상태 * 열에 표시되는 다양한 상태는 다음과 같습니다.

[cols="2*"]
|===
| 업그레이드 상태입니다 | 설명 


| 최신 | 클러스터가 사용 가능한 최신 Element 버전으로 업그레이드되었거나 펌웨어가 최신 버전으로 업그레이드되었습니다. 


| 감지할 수 없습니다 | NetApp 하이브리드 클라우드 제어에는 온라인 소프트웨어 리포지토리에 연결할 수 있는 외부 연결이 없을 때 * 사용 가능한 버전 * 대신 * 이 상태가 표시됩니다. 스토리지 서비스 API가 가능한 업그레이드 상태의 열거 목록에 없는 업그레이드 상태를 반환하는 경우에도 이 상태가 표시됩니다. 


| 사용 가능한 버전 | Element 및/또는 스토리지 펌웨어의 최신 버전을 업그레이드할 수 있습니다. 


| 진행 중 | 업그레이드가 진행 중입니다. 진행 표시줄에 업그레이드 상태가 표시됩니다. 화면 메시지에는 노드 레벨 장애가 표시되고 업그레이드가 진행되는 동안 클러스터의 각 노드에 대한 노드 ID가 표시됩니다. Element UI 또는 vCenter Server UI용 NetApp Element 플러그인을 사용하여 각 노드의 상태를 모니터링할 수 있습니다. 


| 업그레이드 일시 중지 중 | 업그레이드를 일시 중지할 수 있습니다. 업그레이드 프로세스의 상태에 따라 일시 중지 작업이 성공하거나 실패할 수 있습니다. 일시 중지 작업을 확인하는 UI 프롬프트가 표시됩니다. 업그레이드를 일시 중지하기 전에 클러스터가 안전한 장소에 있는지 확인하려면 업그레이드 작업을 완전히 일시 중지하는 데 최대 2시간이 걸릴 수 있습니다. 업그레이드를 다시 시작하려면 * Resume * 을 선택합니다. 


| 일시 중지되었습니다 | 업그레이드를 일시 중지했습니다. 프로세스를 재개하려면 * Resume * 을 선택하십시오. 


| 오류 | 업그레이드 중 오류가 발생했습니다. 오류 로그를 다운로드하여 NetApp Support에 보낼 수 있습니다. 오류를 해결한 후 페이지로 돌아가서 * Resume * 을 선택할 수 있습니다. 업그레이드를 다시 시작하면 시스템에서 상태 점검을 실행하고 업그레이드의 현재 상태를 확인하는 동안 진행 표시줄이 몇 분 동안 뒤로 이동합니다. 
|===


== NetApp 하이브리드 클라우드 제어를 사용하여 업그레이드에 실패할 경우 어떻게 됩니까

업그레이드 중 드라이브 또는 노드에 장애가 발생할 경우 Element UI에 클러스터 장애가 표시됩니다. 업그레이드 프로세스가 다음 노드로 진행되지 않고 클러스터 오류가 해결될 때까지 대기합니다. UI의 진행률 표시줄에 클러스터 오류가 해결될 때까지 업그레이드가 기다리고 있음을 나타냅니다. 이 단계에서 UI에서 * Pause * 를 선택하면 업그레이드가 클러스터가 정상 상태가 될 때까지 대기하므로 작동하지 않습니다. 장애 조사를 돕기 위해 NetApp Support에 문의해야 합니다.

NetApp 하이브리드 클라우드 제어에는 3시간의 사전 설정 대기 시간이 있으며, 그 동안 다음 시나리오 중 하나가 발생할 수 있습니다.

* 3시간 이내에 클러스터 장애가 해결되고 업그레이드가 재개됩니다. 이 시나리오에서는 어떠한 조치도 취할 필요가 없습니다.
* 3시간 후에도 문제가 지속되고 업그레이드 상태가 빨간색 배너와 함께 * 오류 * 로 표시됩니다. 문제가 해결된 후 * Resume * 을 선택하여 업그레이드를 재개할 수 있습니다.
* NetApp 지원에 따라 3시간 이내에 수정 조치를 취하려면 업그레이드를 일시적으로 중단해야 한다고 판단했습니다. 지원 부서에서 API를 사용하여 업그레이드를 중단합니다.



CAUTION: 노드가 업데이트되는 동안 클러스터 업그레이드를 중단하면 드라이브가 노드에서 올바르게 제거되지 않을 수 있습니다. 드라이브가 올바르게 제거되지 않은 경우 업그레이드 중에 드라이브를 다시 추가하려면 NetApp Support에서 수동으로 개입해야 합니다. 노드가 펌웨어 업데이트 또는 업데이트 동기화 후 작업을 수행하는 데 시간이 더 오래 걸릴 수 있습니다. 업그레이드 진행이 멈춘 것 같다면 NetApp Support에 지원을 문의하십시오.



== NetApp 하이브리드 클라우드 제어 API를 사용하여 스토리지 펌웨어를 업그레이드하십시오

API를 사용하여 클러스터의 스토리지 노드를 최신 Element 소프트웨어 버전으로 업그레이드할 수 있습니다. 원하는 자동화 툴을 사용하여 API를 실행할 수 있습니다. 여기에 설명된 API 워크플로에서는 관리 노드에서 사용할 수 있는 REST API UI를 예로 사용합니다.

.단계
. 연결에 따라 다음 중 하나를 수행합니다.
+
[cols="2*"]
|===
| 옵션을 선택합니다 | 단계 


| 관리 노드에 외부 연결이 있습니다.  a| 
.. 리포지토리 연결을 확인합니다.
+
... 관리 노드에서 관리 노드 REST API UI를 엽니다.
+
[listing]
----
https://<ManagementNodeIP>/package-repository/1/
----
... authorize * 를 선택하고 다음을 완료합니다.
+
.... 클러스터 사용자 이름 및 암호를 입력합니다.
.... Client ID를 mnode-client로 입력한다.
.... 세션을 시작하려면 * authorize * 를 선택합니다.
.... 인증 창을 닫습니다.


... REST API UI에서 * get s./packagesmote/remote-repositorysessitory이거나 connection * 을 선택합니다.
... 체험하기 * 를 선택합니다.
... Execute * 를 선택합니다.
... 코드 200이 반환되는 경우 다음 단계로 이동합니다. 원격 리포지토리에 연결되지 않은 경우 연결을 설정하거나 다크 사이트 옵션을 사용합니다.


.. 업그레이드 패키지 ID 찾기:
+
... REST API UI에서 * GET/packages * 를 선택한다.
... 체험하기 * 를 선택합니다.
... Execute * 를 선택합니다.
... 응답에서 펌웨어 패키지 ID를 복사하여 나중에 사용할 수 있도록 저장합니다.






| 관리 노드는 외부 연결이 없는 어두운 사이트 내에 있습니다.  a| 
.. 관리 노드에서 액세스할 수 있는 장치에 최신 스토리지 펌웨어 업그레이드 패키지를 다운로드합니다. 로 이동합니다 https://mysupport.netapp.com/site/products/all/details/element-software/downloads-tab/download/62654/Storage_Firmware_Bundle["Element 소프트웨어 스토리지 펌웨어 번들 페이지"^] 최신 스토리지 펌웨어 이미지를 다운로드합니다.
.. 스토리지 펌웨어 업그레이드 패키지를 관리 노드에 업로드합니다.
+
... 관리 노드에서 관리 노드 REST API UI를 엽니다.
+
[listing]
----
https://<ManagementNodeIP>/package-repository/1/
----
... authorize * 를 선택하고 다음을 완료합니다.
+
.... 클러스터 사용자 이름 및 암호를 입력합니다.
.... Client ID를 mnode-client로 입력한다.
.... 세션을 시작하려면 * authorize * 를 선택합니다.
.... 인증 창을 닫습니다.


... REST API UI에서 * POST/packages * 를 선택합니다.
... 체험하기 * 를 선택합니다.
... Browse * 를 선택하고 업그레이드 패키지를 선택합니다.
... 업로드를 시작하려면 * 실행 * 을 선택합니다.
... 응답에서 패키지 ID(""id"")를 복사하여 나중에 사용할 수 있도록 저장합니다.


.. 업로드 상태를 확인합니다.
+
... REST API UI에서 * GETCi.\packagesCmx/{id}} mi있거나 status * 를 선택합니다.
... 체험하기 * 를 선택합니다.
... 이전 단계에서 복사한 펌웨어 패키지 ID를 * id * 에 입력합니다.
... 상태 요청을 시작하려면 * Execute * 를 선택합니다.
+
완료했을 때 '성공'이라는 응답이 나타납니다.





|===
. 설치 자산 ID를 찾습니다.
+
.. 관리 노드에서 관리 노드 REST API UI를 엽니다.
+
[listing]
----
https://<ManagementNodeIP>/inventory/1/
----
.. authorize * 를 선택하고 다음을 완료합니다.
+
... 클러스터 사용자 이름 및 암호를 입력합니다.
... Client ID를 mnode-client로 입력한다.
... 세션을 시작하려면 * authorize * 를 선택합니다.
... 인증 창을 닫습니다.


.. REST API UI에서 * GET/Installations * 를 선택합니다.
.. 체험하기 * 를 선택합니다.
.. Execute * 를 선택합니다.
.. 응답에서 설치 자산 ID("id")를 복사합니다.
+
[listing, subs="+quotes"]
----
*"id": "abcd01e2-xx00-4ccf-11ee-11f111xx9a0b",*
"management": {
  "errors": [],
  "inventory": {
    "authoritativeClusterMvip": "10.111.111.111",
    "bundleVersion": "2.14.19",
    "managementIp": "10.111.111.111",
    "version": "1.4.12"
----
.. REST API UI에서 * get/Installations/{id} * 를 선택합니다.
.. 체험하기 * 를 선택합니다.
.. 설치 자산 ID를 * id * 필드에 붙여 넣습니다.
.. Execute * 를 선택합니다.
.. 응답에서 업그레이드할 클러스터의 스토리지 클러스터 ID("" id")를 복사하여 나중에 사용할 수 있도록 저장합니다.
+
[listing, subs="+quotes"]
----
"storage": {
  "errors": [],
  "inventory": {
    "clusters": [
      {
        "clusterUuid": "a1bd1111-4f1e-46zz-ab6f-0a1111b1111x",
        *"id": "a1bd1111-4f1e-46zz-ab6f-a1a1a111b012",*
----


. 스토리지 펌웨어 업그레이드를 실행합니다.
+
.. 관리 노드에서 스토리지 REST API UI를 엽니다.
+
[listing]
----
https://<ManagementNodeIP>/storage/1/
----
.. authorize * 를 선택하고 다음을 완료합니다.
+
... 클러스터 사용자 이름 및 암호를 입력합니다.
... Client ID를 mnode-client로 입력한다.
... 세션을 시작하려면 * authorize * 를 선택합니다.
... 창을 닫습니다.


.. POST/upgrades * 를 선택합니다.
.. 체험하기 * 를 선택합니다.
.. 매개변수 필드에 업그레이드 패키지 ID를 입력합니다.
.. 매개 변수 필드에 스토리지 클러스터 ID를 입력합니다.
.. 업그레이드를 시작하려면 * Execute * 를 선택합니다.
+
이 응답은 "초기화 중"으로 표시되어야 합니다.

+
[listing, subs="+quotes"]
----
{
  "_links": {
    "collection": "https://localhost:442/storage/upgrades",
    "self": "https://localhost:442/storage/upgrades/3fa85f64-1111-4562-b3fc-2c963f66abc1",
    "log": https://localhost:442/storage/upgrades/3fa85f64-1111-4562-b3fc-2c963f66abc1/log
  },
  "storageId": "114f14a4-1a1a-11e9-9088-6c0b84e200b4",
  "upgradeId": "334f14a4-1a1a-11e9-1055-6c0b84e2001b4",
  "packageId": "774f14a4-1a1a-11e9-8888-6c0b84e200b4",
  "config": {},
  *"state": "initializing",*
  "status": {
    "availableActions": [
      "string"
    ],
    "message": "string",
    "nodeDetails": [
      {
        "message": "string",
        "step": "NodePreStart",
        "nodeID": 0,
        "numAttempt": 0
      }
    ],
    "percent": 0,
    "step": "ClusterPreStart",
    "timestamp": "2020-04-21T22:10:57.057Z",
    "failedHealthChecks": [
      {
        "checkID": 0,
        "name": "string",
        "displayName": "string",
        "passed": true,
        "kb": "string",
        "description": "string",
        "remedy": "string",
        "severity": "string",
        "data": {},
        "nodeID": 0
      }
    ]
  },
  "taskId": "123f14a4-1a1a-11e9-7777-6c0b84e123b2",
  "dateCompleted": "2020-04-21T22:10:57.057Z",
  "dateCreated": "2020-04-21T22:10:57.057Z"
}
----
.. 응답에 포함된 업그레이드 ID("upgrade eId")를 복사합니다.


. 업그레이드 진행 상황 및 결과를 확인합니다.
+
.. Get h./upgrades/{upgrade eId} * 를 선택합니다.
.. 체험하기 * 를 선택합니다.
.. 이전 단계의 업그레이드 ID를 * upgrade eId * 에 입력합니다.
.. Execute * 를 선택합니다.
.. 업그레이드 중 문제가 있거나 특별한 요구 사항이 있는 경우 다음 중 하나를 수행합니다.
+
[cols="2*"]
|===
| 옵션을 선택합니다 | 단계 


| 응답 본문의 'failedHealthChecks' 메시지로 인해 클러스터 상태 문제를 해결해야 합니다.  a| 
... 각 문제에 대해 나열된 특정 KB 문서로 이동하거나 지정된 해결책을 수행합니다.
... KB가 지정된 경우 관련 KB 문서에 설명된 프로세스를 완료합니다.
... 클러스터 문제를 해결한 후 필요한 경우 다시 인증한 후 * Put} m./upgrades/{upgrade eId} * 를 선택합니다.
... 체험하기 * 를 선택합니다.
... 이전 단계의 업그레이드 ID를 * upgrade eId * 에 입력합니다.
... 요청서에 액션이력서 입력
+
[listing]
----
{
  "action": "resume"
}
----
... Execute * 를 선택합니다.




| 유지 보수 기간이 종료되었거나 다른 이유로 업그레이드를 일시 중지해야 합니다.  a| 
... 필요한 경우 재인증을 수행하고 * Put cer/upgrades/{upgrade eId} * 를 선택합니다.
... 체험하기 * 를 선택합니다.
... 이전 단계의 업그레이드 ID를 * upgrade eId * 에 입력합니다.
... 요청 본문에 ""동작":"일시정지""를 입력합니다.
+
[listing]
----
{
  "action": "pause"
}
----
... Execute * 를 선택합니다.


|===
.. 필요한 경우 프로세스가 완료될 때까지 * Get 횟수/업그레이드/{upgrade eId} * API를 여러 번 실행합니다.
+
업그레이드 중에 오류가 발생하지 않으면 상태 는 실행 중(Running)을 나타냅니다. 각 노드가 업그레이드되면 'tep' 값이 'NodeFinished'로 변경됩니다.

+
%가 100이고 '상태'가 '완료'로 표시되면 업그레이드가 성공적으로 완료된 것입니다.





[discrete]
== 자세한 내용을 확인하십시오

* https://docs.netapp.com/us-en/vcp/index.html["vCenter Server용 NetApp Element 플러그인"^]
* https://www.netapp.com/hybrid-cloud/hci-documentation/["NetApp HCI 리소스 페이지 를 참조하십시오"^]

