---
sidebar: sidebar 
permalink: docs/task_hcc_upgrade_element_software.html 
summary: NetApp HCI 시스템 업그레이드의 일부로 NetApp Element 소프트웨어를 업그레이드합니다. 
keywords: netapp, hci, HealthTools, cluster, element, H610S upgrade, hcc 
---
= Element 소프트웨어 업그레이드
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
NetApp Element 소프트웨어를 업그레이드하려면 NetApp 하이브리드 클라우드 제어 UI, REST API 또는 HealthTools 도구 제품군을 사용할 수 있습니다. 노드 추가 및 제거, 드라이브 추가 및 제거, 이니시에이터, 볼륨 액세스 그룹 및 가상 네트워크와 관련된 명령 등 Element 소프트웨어를 업그레이드하는 동안 특정 작업이 표시되지 않습니다.

.무엇을 &#8217;필요로 할거야
* * 관리자 권한 *: 업그레이드를 수행할 수 있는 스토리지 클러스터 관리자 권한이 있습니다.
* * 유효한 업그레이드 경로 *: 업그레이드하려는 Element 버전에 대한 업그레이드 경로 정보를 확인했으며 업그레이드 경로가 유효한지 확인했습니다.https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Software/Element_Software/What_is_the_upgrade_matrix_for_storage_clusters_running_NetApp_Element_software%3F["NetApp KB: NetApp Element 소프트웨어를 실행하는 스토리지 클러스터의 업그레이드 매트릭스입니다"^]
* * 시스템 시간 동기화 *: 모든 노드의 시스템 시간이 동기화되고 스토리지 클러스터 및 노드에 대해 NTP가 올바르게 구성되었는지 확인했습니다. 각 노드는 시간편중과 관련된 해결되지 않은 클러스터 장애가 없는 노드별 웹 UI('https://[IP address]:442')에서 DNS 이름 서버로 구성되어야 합니다.
* * 시스템 포트 *: 업그레이드에 NetApp 하이브리드 클라우드 제어를 사용하는 경우 필요한 포트가 열려 있는지 확인했습니다. 을 참조하십시오 link:hci_prereqs_required_network_ports.html["네트워크 포트"] 를 참조하십시오.
* * 관리 노드 *: NetApp 하이브리드 클라우드 제어 UI 및 API의 경우, 사용자 환경의 관리 노드에서 버전 11.3이 실행되고 있습니다.
* * 관리 서비스 *: 관리 서비스 번들을 최신 버전으로 업데이트했습니다.



IMPORTANT: Element 소프트웨어를 버전 12.3.x로 업그레이드하기 전에 최신 관리 서비스 번들로 업그레이드해야 합니다 Element 소프트웨어를 버전 12.3.x로 업데이트하는 경우 계속하려면 관리 서비스 2.14.60 이상이 필요합니다.

* * 클러스터 상태 *: 클러스터를 업그레이드할 준비가 되었는지 확인했습니다. 을 참조하십시오 link:task_hcc_upgrade_element_prechecks.html["스토리지를 업그레이드하기 전에 Element 스토리지 상태 점검을 실행합니다"].
* * H610S 노드의 업데이트된 BMC *: H610S 노드의 BMC 버전을 업그레이드했습니다. 를 참조하십시오 link:rn_H610S_BMC_3.84.07.html["릴리스 정보 및 업그레이드 지침"].
* * 최종 사용자 라이센스 계약(EULA) *: 관리 서비스 2.20.69부터 NetApp 하이브리드 클라우드 제어 UI 또는 API를 사용하여 Element 소프트웨어를 업그레이드하기 전에 EULA에 동의하고 저장해야 합니다.
+
.. 웹 브라우저에서 관리 노드의 IP 주소를 엽니다.
+
[listing]
----
https://<ManagementNodeIP>
----
.. NetApp 하이브리드 클라우드 제어에 스토리지 클러스터 관리자 자격 증명을 제공하여 로그인하십시오.
.. 인터페이스의 오른쪽 상단 근처에 있는 * Upgrade * 를 선택합니다.
.. EULA가 나타납니다. 아래로 스크롤하여 * 현재 업데이트 및 향후 모든 업데이트에 동의함 * 을 선택하고 * 저장 * 을 선택합니다.
+

NOTE: EULA에 동의하면 향후 모든 업데이트에 대해 기록되고 자동 다운로드 기능이 활성화됩니다. NetApp 소프트웨어 업데이트 및 업그레이드 관련 업데이트는 고유 권한으로 설치할 수 있습니다. NetApp 온라인 소프트웨어 저장소에 대한 네트워크 연결을 비활성화하여 자동 다운로드 기능을 비활성화할 수 있습니다.





다음 Element 소프트웨어 업그레이드 옵션 중 하나를 선택합니다.

*  NetApp Hybrid Cloud Control UI to upgrade Element storage
*  NetApp Hybrid Cloud Control API to upgrade Element storage
*  Element software at connected sites using HealthTools
*  Element software at dark sites using HealthTools



IMPORTANT: H610S 시리즈 노드를 Element 12.3.x로 업그레이드하는 경우 노드에서 11.8 이전의 Element 버전이 실행되는 경우 추가 업그레이드 단계( )를 수행해야 합니다 H610S storage nodes to Element 12.3.x (phase 2),2단계)를 각 스토리지 노드에 대해 설정합니다. Element 11.8 이상을 실행 중인 경우 추가 업그레이드 단계(2단계)가 필요하지 않습니다.



== NetApp 하이브리드 클라우드 제어 UI를 사용하여 Element 스토리지를 업그레이드하십시오

NetApp 하이브리드 클라우드 제어 UI를 사용하여 스토리지 클러스터를 업그레이드할 수 있습니다.

관리 노드가 인터넷에 연결되어 있지 않은 경우 를 다운로드했습니다 https://mysupport.netapp.com/site/products/all/details/netapp-hci/downloads-tab["NetApp HCI 스토리지 클러스터용 NetApp HCI 소프트웨어 패키지"^].


CAUTION: NetApp 하이브리드 클라우드 제어를 사용하여 스토리지 클러스터를 업그레이드하는 동안 발생할 수 있는 문제와 그 해결 방법은 을 참조하십시오 https://kb.netapp.com/Advice_and_Troubleshooting/Hybrid_Cloud_Infrastructure/NetApp_HCI/Potential_issues_and_workarounds_when_running_storage_upgrades_using_NetApp_Hybrid_Cloud_Control["KB 문서를 참조하십시오"^].


TIP: 업그레이드 프로세스는 H610S 플랫폼이 아닌 경우 노드당 약 30분 정도 소요됩니다.

.단계
. 웹 브라우저에서 관리 노드의 IP 주소를 엽니다.
+
[listing]
----
https://<ManagementNodeIP>
----
. NetApp 하이브리드 클라우드 제어에 스토리지 클러스터 관리자 자격 증명을 제공하여 로그인하십시오.
. 인터페이스의 오른쪽 상단 근처에 있는 * Upgrade * 를 선택합니다.
. 업그레이드 * 페이지에서 * 스토리지 * 를 선택합니다.
+
Storage * 탭에는 설치에 포함된 스토리지 클러스터가 나열됩니다. NetApp Hybrid Cloud Control에서 클러스터에 액세스할 수 없는 경우 * 업그레이드 * 페이지에 표시되지 않습니다.

. 다음 옵션 중 하나를 선택하고 클러스터에 적용할 수 있는 단계 세트를 수행합니다.
+
[cols="2*"]
|===
| 옵션을 선택합니다 | 단계 


| 관리 노드에 외부 연결이 있습니다.  a| 
.. 업그레이드할 클러스터 옆에 있는 드롭다운 화살표를 선택하고 * Element * 탭 아래에서 사용 가능한 업그레이드 버전 중에서 선택합니다.
.. 업그레이드 시작 * 을 선택합니다.



TIP: 업그레이드 중 * 업그레이드 상태 * 는 프로세스 상태를 반영하기 위해 변경됩니다. 또한 업그레이드를 일시 중지하거나 업그레이드가 오류를 반환하는 경우와 같이 수행한 작업에 대한 응답으로 변경됩니다. 을 참조하십시오  status changes.


NOTE: 업그레이드가 진행되는 동안 페이지를 종료하고 나중에 다시 돌아와 진행 상황을 계속 모니터링할 수 있습니다. 클러스터 행이 축소되어 있는 경우 이 페이지는 상태 및 현재 버전을 동적으로 업데이트하지 않습니다. 테이블을 업데이트하거나 페이지를 새로 고치려면 클러스터 행을 확장해야 합니다.

업그레이드가 완료된 후 로그를 다운로드할 수 있습니다.



| 관리 노드는 외부 연결이 없는 어두운 사이트 내에 있습니다.  a| 
.. 다운로드한 업그레이드 패키지를 업로드하려면 * 찾아보기 * 를 선택합니다.
.. 업로드가 완료될 때까지 기다립니다. 진행률 표시줄에 업로드 상태가 표시됩니다.



CAUTION: 브라우저 창에서 이동하면 파일 업로드가 손실됩니다.

파일이 성공적으로 업로드 및 확인되면 화면에 메시지가 표시됩니다. 정품 확인에 몇 분 정도 걸릴 수 있습니다. 이 단계에서 브라우저 창에서 다른 곳으로 이동하면 파일 업로드가 유지됩니다.



| 11.8 이전의 Element 버전을 실행하는 H610S 클러스터를 업그레이드하고 있습니다.  a| 
.. 업그레이드할 클러스터 옆에 있는 드롭다운 화살표를 선택하고 사용 가능한 업그레이드 버전 중에서 선택합니다.
.. 업그레이드 시작 * 을 선택합니다. 업그레이드가 완료되면 UI에서 프로세스의 2단계를 수행하라는 메시지를 표시합니다.
.. 에서 필요한 추가 단계(2단계)를 완료합니다 https://kb.netapp.com/Advice_and_Troubleshooting/Hybrid_Cloud_Infrastructure/H_Series/NetApp_H610S_storage_node_power_off_and_on_procedure["KB 문서를 참조하십시오"^], 및 UI에서 단계 2를 완료했음을 확인합니다.


업그레이드가 완료된 후 로그를 다운로드할 수 있습니다. 다양한 업그레이드 상태 변경에 대한 자세한 내용은 을 참조하십시오  status changes.

|===




=== 업그레이드 상태 변경

업그레이드 프로세스 전, 도중 및 이후에 UI의 * 업그레이드 상태 * 열에 표시되는 다양한 상태는 다음과 같습니다.

[cols="2*"]
|===
| 업그레이드 상태입니다 | 설명 


| 최신 | 클러스터가 사용 가능한 최신 Element 버전으로 업그레이드되었습니다. 


| 사용 가능한 버전 | Element 및/또는 스토리지 펌웨어의 최신 버전을 업그레이드할 수 있습니다. 


| 진행 중 | 업그레이드가 진행 중입니다. 진행 표시줄에 업그레이드 상태가 표시됩니다. 화면 메시지에는 노드 레벨 장애가 표시되고 업그레이드가 진행되는 동안 클러스터의 각 노드에 대한 노드 ID가 표시됩니다. Element UI 또는 vCenter Server UI용 NetApp Element 플러그인을 사용하여 각 노드의 상태를 모니터링할 수 있습니다. 


| 업그레이드 일시 중지 중 | 업그레이드를 일시 중지할 수 있습니다. 업그레이드 프로세스의 상태에 따라 일시 중지 작업이 성공하거나 실패할 수 있습니다. 일시 중지 작업을 확인하는 UI 프롬프트가 표시됩니다. 업그레이드를 일시 중지하기 전에 클러스터가 안전한 장소에 있는지 확인하려면 업그레이드 작업을 완전히 일시 중지하는 데 최대 2시간이 걸릴 수 있습니다. 업그레이드를 다시 시작하려면 * Resume * 을 선택합니다. 


| 일시 중지되었습니다 | 업그레이드를 일시 중지했습니다. 프로세스를 재개하려면 * Resume * 을 선택하십시오. 


| 오류 | 업그레이드 중 오류가 발생했습니다. 오류 로그를 다운로드하여 NetApp Support에 보낼 수 있습니다. 오류를 해결한 후 페이지로 돌아가서 * Resume * 을 선택할 수 있습니다. 업그레이드를 다시 시작하면 시스템에서 상태 점검을 실행하고 업그레이드의 현재 상태를 확인하는 동안 진행 표시줄이 몇 분 동안 뒤로 이동합니다. 


| 감지할 수 없습니다 | NetApp 하이브리드 클라우드 제어에는 온라인 소프트웨어 리포지토리에 연결할 수 있는 외부 연결이 없을 때 * 사용 가능한 버전 * 대신 * 이 상태가 표시됩니다. 외부 연결이 있지만 이 메시지가 계속 표시되면 를 확인하십시오 link:task_mnode_configure_proxy_server.html["프록시 구성"]. 


| 후속 조치를 완료합니다 | 11.8 이전의 Element 버전에서 H610S 노드를 업그레이드하는 경우에만 해당됩니다. 업그레이드 프로세스의 1단계가 완료된 후 이 상태는 업그레이드 2단계를 수행하라는 메시지를 표시합니다( 참조) https://kb.netapp.com/Advice_and_Troubleshooting/Hybrid_Cloud_Infrastructure/H_Series/NetApp_H610S_storage_node_power_off_and_on_procedure["KB 문서를 참조하십시오"^])를 클릭합니다. 2단계를 완료하고 완료했음을 확인한 후 상태가 * 최신 * 로 변경됩니다. 
|===


== NetApp 하이브리드 클라우드 제어 API를 사용하여 Element 스토리지를 업그레이드하십시오

API를 사용하여 클러스터의 스토리지 노드를 최신 Element 소프트웨어 버전으로 업그레이드할 수 있습니다. 원하는 자동화 툴을 사용하여 API를 실행할 수 있습니다. 여기에 설명된 API 워크플로에서는 관리 노드에서 사용할 수 있는 REST API UI를 예로 사용합니다.

.단계
. 연결에 따라 다음 중 하나를 수행합니다.
+
[cols="2*"]
|===
| 옵션을 선택합니다 | 단계 


| 관리 노드에 외부 연결이 있습니다.  a| 
.. 리포지토리 연결을 확인합니다.
+
... 관리 노드에서 관리 노드 REST API UI를 엽니다.
+
[listing]
----
https://<ManagementNodeIP>/package-repository/1/
----
... authorize * 를 선택하고 다음을 완료합니다.
+
.... 클러스터 사용자 이름 및 암호를 입력합니다.
.... Client ID를 mnode-client로 입력한다.
.... 세션을 시작하려면 * authorize * 를 선택합니다.
.... 인증 창을 닫습니다.


... REST API UI에서 * get s./packagesmote/remote-repositorysessitory이거나 connection * 을 선택합니다.
... 체험하기 * 를 선택합니다.
... Execute * 를 선택합니다.
... 코드 200이 반환되는 경우 다음 단계로 이동합니다. 원격 리포지토리에 연결되지 않은 경우 연결을 설정하거나 다크 사이트 옵션을 사용합니다.


.. 업그레이드 패키지 ID 찾기:
+
... REST API UI에서 * GET/packages * 를 선택한다.
... 체험하기 * 를 선택합니다.
... Execute * 를 선택합니다.
... 응답에서 패키지 ID를 복사하여 나중에 사용할 수 있도록 저장합니다.






| 관리 노드는 외부 연결이 없는 어두운 사이트 내에 있습니다.  a| 
.. 스토리지 업그레이드 패키지를 관리 노드에서 액세스할 수 있는 디바이스로 다운로드하고 NetApp HCI 소프트웨어로 이동합니다 https://mysupport.netapp.com/site/products/all/details/netapp-hci/downloads-tab["다운로드 페이지"^] 최신 스토리지 노드 이미지를 다운로드합니다.
.. 스토리지 업그레이드 패키지를 관리 노드에 업로드합니다.
+
... 관리 노드에서 관리 노드 REST API UI를 엽니다.
+
[listing]
----
https://<ManagementNodeIP>/package-repository/1/
----
... authorize * 를 선택하고 다음을 완료합니다.
+
.... 클러스터 사용자 이름 및 암호를 입력합니다.
.... Client ID를 mnode-client로 입력한다.
.... 세션을 시작하려면 * authorize * 를 선택합니다.
.... 인증 창을 닫습니다.


... REST API UI에서 * POST/packages * 를 선택합니다.
... 체험하기 * 를 선택합니다.
... Browse * 를 선택하고 업그레이드 패키지를 선택합니다.
... 업로드를 시작하려면 * 실행 * 을 선택합니다.
... 응답에서 패키지 ID(""id"")를 복사하여 나중에 사용할 수 있도록 저장합니다.


.. 업로드 상태를 확인합니다.
+
... REST API UI에서 * GETCi.\packagesCmx/{id}} mi있거나 status * 를 선택합니다.
... 체험하기 * 를 선택합니다.
... 이전 단계에서 복사한 패키지 ID를 * id * 에 입력합니다.
... 상태 요청을 시작하려면 * Execute * 를 선택합니다.
+
완료했을 때 '성공'이라는 응답이 나타납니다.





|===
. 스토리지 클러스터 ID를 찾습니다.
+
.. 관리 노드에서 관리 노드 REST API UI를 엽니다.
+
[listing]
----
https://<ManagementNodeIP>/inventory/1/
----
.. authorize * 를 선택하고 다음을 완료합니다.
+
... 클러스터 사용자 이름 및 암호를 입력합니다.
... Client ID를 mnode-client로 입력한다.
... 세션을 시작하려면 * authorize * 를 선택합니다.
... 인증 창을 닫습니다.


.. REST API UI에서 * GET/Installations * 를 선택합니다.
.. 체험하기 * 를 선택합니다.
.. Execute * 를 선택합니다.
.. 응답에서 설치 자산 ID(""id"")를 복사합니다.
.. REST API UI에서 * get/Installations/{id} * 를 선택합니다.
.. 체험하기 * 를 선택합니다.
.. 설치 자산 ID를 * id * 필드에 붙여 넣습니다.
.. Execute * 를 선택합니다.
.. 응답에서 업그레이드할 클러스터의 스토리지 클러스터 ID("" id")를 복사하여 나중에 사용할 수 있도록 저장합니다.


. 스토리지 업그레이드를 실행합니다.
+
.. 관리 노드에서 스토리지 REST API UI를 엽니다.
+
[listing]
----
https://<ManagementNodeIP>/storage/1/
----
.. authorize * 를 선택하고 다음을 완료합니다.
+
... 클러스터 사용자 이름 및 암호를 입력합니다.
... Client ID를 mnode-client로 입력한다.
... 세션을 시작하려면 * authorize * 를 선택합니다.
... 인증 창을 닫습니다.


.. POST/upgrades * 를 선택합니다.
.. 체험하기 * 를 선택합니다.
.. 매개변수 필드에 업그레이드 패키지 ID를 입력합니다.
.. 매개 변수 필드에 스토리지 클러스터 ID를 입력합니다.
+
페이로드는 다음 예와 유사해야 합니다.

+
[listing]
----
{
  "config": {},
  "packageId": "884f14a4-5a2a-11e9-9088-6c0b84e211c4",
  "storageId": "884f14a4-5a2a-11e9-9088-6c0b84e211c4"
}
----
.. 업그레이드를 시작하려면 * Execute * 를 선택합니다.
+
이에 대한 대응은 "초기화 중"으로 표시되어야 합니다.

+
[listing]
----
{
  "_links": {
    "collection": "https://localhost:442/storage/upgrades",
    "self": "https://localhost:442/storage/upgrades/3fa85f64-1111-4562-b3fc-2c963f66abc1",
    "log": https://localhost:442/storage/upgrades/3fa85f64-1111-4562-b3fc-2c963f66abc1/log
  },
  "storageId": "114f14a4-1a1a-11e9-9088-6c0b84e200b4",
  "upgradeId": "334f14a4-1a1a-11e9-1055`-6c0b84e2001b4",
  "packageId": "774f14a4-1a1a-11e9-8888-6c0b84e200b4",
  "config": {},
  "state": "initializing",
  "status": {
    "availableActions": [
      "string"
    ],
    "message": "string",
    "nodeDetails": [
      {
        "message": "string",
        "step": "NodePreStart",
        "nodeID": 0,
        "numAttempt": 0
      }
    ],
    "percent": 0,
    "step": "ClusterPreStart",
    "timestamp": "2020-04-21T22:10:57.057Z",
    "failedHealthChecks": [
      {
        "checkID": 0,
        "name": "string",
        "displayName": "string",
        "passed": true,
        "kb": "string",
        "description": "string",
        "remedy": "string",
        "severity": "string",
        "data": {},
        "nodeID": 0
      }
    ]
  },
  "taskId": "123f14a4-1a1a-11e9-7777-6c0b84e123b2",
  "dateCompleted": "2020-04-21T22:10:57.057Z",
  "dateCreated": "2020-04-21T22:10:57.057Z"
}
----
.. 응답에 포함된 업그레이드 ID("upgrade eId")를 복사합니다.


. 업그레이드 진행 상황 및 결과를 확인합니다.
+
.. Get h./upgrades/{upgrade eId} * 를 선택합니다.
.. 체험하기 * 를 선택합니다.
.. 이전 단계의 업그레이드 ID를 * upgrade eId * 에 입력합니다.
.. Execute * 를 선택합니다.
.. 업그레이드 중 문제가 있거나 특별한 요구 사항이 있는 경우 다음 중 하나를 수행합니다.
+
[cols="2*"]
|===
| 옵션을 선택합니다 | 단계 


| 응답 본문의 'failedHealthChecks' 메시지로 인해 클러스터 상태 문제를 해결해야 합니다.  a| 
... 각 문제에 대해 나열된 특정 KB 문서로 이동하거나 지정된 해결책을 수행합니다.
... KB가 지정된 경우 관련 KB 문서에 설명된 프로세스를 완료합니다.
... 클러스터 문제를 해결한 후 필요한 경우 다시 인증한 후 * Put} m./upgrades/{upgrade eId} * 를 선택합니다.
... 체험하기 * 를 선택합니다.
... 이전 단계의 업그레이드 ID를 * upgrade eId * 에 입력합니다.
... 요청서에 액션이력서 입력
+
[listing]
----
{
  "action": "resume"
}
----
... Execute * 를 선택합니다.




| 유지 보수 기간이 종료되었거나 다른 이유로 업그레이드를 일시 중지해야 합니다.  a| 
... 필요한 경우 재인증을 수행하고 * Put cer/upgrades/{upgrade eId} * 를 선택합니다.
... 체험하기 * 를 선택합니다.
... 이전 단계의 업그레이드 ID를 * upgrade eId * 에 입력합니다.
... 요청 본문에 ""동작":"일시정지""를 입력합니다.
+
[listing]
----
{
  "action": "pause"
}
----
... Execute * 를 선택합니다.




| 11.8 이전의 Element 버전을 실행하는 H610S 클러스터를 업그레이드하는 경우 응답 본문에 "finishedNeedsAck" 상태가 표시됩니다. 각 H610S 스토리지 노드에 대해 추가 업그레이드 단계(2단계)를 수행해야 합니다.  a| 
... 을 참조하십시오  H610S storage nodes to Element 12.3.x or later (phase 2) 각 노드에 대해 프로세스를 완료합니다.
... 필요한 경우 재인증을 수행하고 * Put cer/upgrades/{upgrade eId} * 를 선택합니다.
... 체험하기 * 를 선택합니다.
... 이전 단계의 업그레이드 ID를 * upgrade eId * 에 입력합니다.
... 요청서에 액션승인(ACTION)을 입력합니다.
+
[listing]
----
{
  "action": "acknowledge"
}
----
... Execute * 를 선택합니다.


|===
.. 필요한 경우 프로세스가 완료될 때까지 * Get 횟수/업그레이드/{upgrade eId} * API를 여러 번 실행합니다.
+
업그레이드 중에 오류가 발생하지 않으면 상태 는 실행 중(Running)을 나타냅니다. 각 노드가 업그레이드되면 'tep' 값이 'NodeFinished'로 변경됩니다.

+
%가 100이고 '상태'가 '완료'로 표시되면 업그레이드가 성공적으로 완료된 것입니다.







== NetApp 하이브리드 클라우드 제어를 사용하여 업그레이드에 실패할 경우 어떻게 됩니까

업그레이드 중 드라이브 또는 노드에 장애가 발생할 경우 Element UI에 클러스터 장애가 표시됩니다. 업그레이드 프로세스가 다음 노드로 진행되지 않고 클러스터 오류가 해결될 때까지 대기합니다. UI의 진행률 표시줄에 클러스터 오류가 해결될 때까지 업그레이드가 기다리고 있음을 나타냅니다. 이 단계에서 UI에서 * Pause * 를 선택하면 업그레이드가 클러스터가 정상 상태가 될 때까지 대기하므로 작동하지 않습니다. 장애 조사를 돕기 위해 NetApp Support에 문의해야 합니다.

NetApp 하이브리드 클라우드 제어에는 3시간의 사전 설정 대기 시간이 있으며, 그 동안 다음 시나리오 중 하나가 발생할 수 있습니다.

* 3시간 이내에 클러스터 장애가 해결되고 업그레이드가 재개됩니다. 이 시나리오에서는 어떠한 조치도 취할 필요가 없습니다.
* 3시간 후에도 문제가 지속되고 업그레이드 상태가 빨간색 배너와 함께 * 오류 * 로 표시됩니다. 문제가 해결된 후 * Resume * 을 선택하여 업그레이드를 재개할 수 있습니다.
* NetApp 지원에 따라 3시간 이내에 수정 조치를 취하려면 업그레이드를 일시적으로 중단해야 한다고 판단했습니다. 지원 부서에서 API를 사용하여 업그레이드를 중단합니다.



CAUTION: 노드가 업데이트되는 동안 클러스터 업그레이드를 중단하면 드라이브가 노드에서 올바르게 제거되지 않을 수 있습니다. 드라이브가 올바르게 제거되지 않은 경우 업그레이드 중에 드라이브를 다시 추가하려면 NetApp Support에서 수동으로 개입해야 합니다. 노드가 펌웨어 업데이트 또는 업데이트 동기화 후 작업을 수행하는 데 시간이 더 오래 걸릴 수 있습니다. 업그레이드 진행이 멈춘 것 같다면 NetApp Support에 지원을 문의하십시오.



== HealthTools를 사용하여 연결된 사이트에서 Element 소프트웨어를 업그레이드합니다

.단계
. 스토리지 업그레이드 패키지를 다운로드합니다. NetApp HCI 소프트웨어로 이동합니다 https://mysupport.netapp.com/site/products/all/details/netapp-hci/downloads-tab["다운로드 페이지"^] 최신 스토리지 노드 이미지를 관리 노드가 아닌 디바이스로 다운로드합니다.
+

NOTE: Element 스토리지 소프트웨어를 업그레이드하려면 최신 버전의 HealthTools가 필요합니다.

. ISO 파일을 /tmp와 같은 액세스 가능한 위치의 관리 노드에 복사합니다.
+
ISO 파일을 업로드할 때 파일 이름이 변경되지 않는지 확인합니다. 그렇지 않으면 이후 단계가 실패합니다.

. * 선택 사항 *: 업그레이드하기 전에 관리 노드에서 클러스터 노드로 ISO를 다운로드합니다.
+
이 단계에서는 스토리지 노드에 ISO를 사전 스테이징하고 추가 내부 검사를 실행하여 클러스터가 업그레이드할 양호한 상태인지 확인하여 업그레이드 시간을 단축합니다. 이 작업을 수행해도 클러스터가 "업그레이드" 모드로 전환되거나 클러스터 작업이 제한되지 않습니다.

+
[listing]
----
sfinstall <MVIP> -u <cluster_username> <path-toinstall-file-ISO> --stage
----
+

NOTE: 'finstall'이 정보를 표시하도록 하려면 명령줄에서 암호를 생략합니다. 특수 문자가 포함된 암호의 경우 각 특수 문자 앞에 백슬래시('\')를 추가합니다. 예를 들어 'mypass!@1'을 'mypass\!\@'로 입력해야 합니다.

+
* 예 * 다음 샘플 입력을 참조하십시오.

+
[listing]
----
sfinstall 10.117.0.244 -u admin /tmp/solidfire-rtfisodium-11.0.0.345.iso --stage
----
+
이 샘플에 대한 출력에서는 'finstall'이 새 버전의 'finstall'을 사용할 수 있는지 여부를 확인하려고 합니다.

+
[listing]
----
sfinstall 10.117.0.244 -u admin
/tmp/solidfire-rtfisodium-11.0.0.345.iso 2018-10-01 16:52:15:
Newer version of sfinstall available.
This version: 2018.09.01.130, latest version: 2018.06.05.901.
The latest version of the HealthTools can be downloaded from:
https:// mysupport.netapp.com/NOW/cgi-bin/software/
or rerun with --skip-version-check
----
+
성공적인 사전 단계 작업에서 발췌한 다음 샘플을 참조하십시오.

+

NOTE: 스테이징을 완료하면 업그레이드 이벤트 후 스토리지 노드 업그레이드 스테이징 성공 메시지가 표시됩니다.

+
[listing]
----
flabv0004 ~ # sfinstall -u admin
10.117.0.87 solidfire-rtfi-sodium-patch3-11.3.0.14171.iso --stage
2019-04-03 13:19:58: sfinstall Release Version: 2019.01.01.49 Management Node Platform:
Ember Revision: 26b042c3e15a Build date: 2019-03-12 18:45
2019-04-03 13:19:58: Checking connectivity to MVIP 10.117.0.87
2019-04-03 13:19:58: Checking connectivity to node 10.117.0.86
2019-04-03 13:19:58: Checking connectivity to node 10.117.0.87
...
2019-04-03 13:19:58: Successfully connected to cluster and all nodes
...
2019-04-03 13:20:00: Do you want to continue? ['Yes', 'No']: Yes
...
2019-04-03 13:20:55: Staging install pack on cluster nodes
2019-04-03 13:20:55: newVersion: 11.3.0.14171
2019-04-03 13:21:01: nodeToStage: nlabp2814, nlabp2815, nlabp2816, nlabp2813
2019-04-03 13:21:02: Staging Node nlabp2815 mip=[10.117.0.87] nodeID=[2] (1 of 4 nodes)
2019-04-03 13:21:02: Node Upgrade serving image at
http://10.117.0.204/rtfi/solidfire-rtfisodium-
patch3-11.3.0.14171/filesystem.squashfs
...
2019-04-03 13:25:40: Staging finished. Repeat the upgrade command without the --stage option to start the upgrade.
----
+
스테이징된 ISO는 업그레이드가 완료된 후 자동으로 삭제됩니다. 그러나 업그레이드가 시작되지 않고 일정을 조정해야 하는 경우 다음 명령을 사용하여 ISO를 수동으로 디스테이징할 수 있습니다.

+
'sfinstall <mVIP>-u <cluster_username>--destage'

+
업그레이드가 시작된 후에는 더 이상 디스테이징 옵션을 사용할 수 없습니다.

. 'finstall' 명령과 ISO 파일 경로를 사용하여 업그레이드를 시작합니다.
+
'sfinstall <mvip> -u <cluster_username><path-toinstall-file-iso>'를 입력합니다

+
* 예 *

+
다음 샘플 입력 명령을 참조하십시오.

+
[listing]
----
sfinstall 10.117.0.244 -u admin /tmp/solidfire-rtfi-sodium-11.0.0.345.iso
----
+
이 샘플에 대한 출력에서는 'finstall'이 새 버전의 'finstall'을 사용할 수 있는지 여부를 확인하려고 합니다.

+
[listing]
----
sfinstall 10.117.0.244 -u admin /tmp/solidfire-rtfi-sodium-11.0.0.345.iso
2018-10-01 16:52:15: Newer version of sfinstall available.
This version: 2018.09.01.130, latest version: 2018.06.05.901.
The latest version of the HealthTools can be downloaded from:
https://mysupport.netapp.com/NOW/cgi-bin/software/ or rerun with --skip-version-check
----
+
성공적인 업그레이드에서 다음 샘플 발췌 부분을 참조하십시오. 업그레이드 이벤트를 사용하여 업그레이드 진행률을 모니터링할 수 있습니다.

+
[listing]
----
# sfinstall 10.117.0.161 -u admin solidfire-rtfi-sodium-11.0.0.761.iso
2018-10-11 18:28
Checking connectivity to MVIP 10.117.0.161
Checking connectivity to node 10.117.0.23
Checking connectivity to node 10.117.0.24
...
Successfully connected to cluster and all nodes
###################################################################
You are about to start a new upgrade
10.117.0.161
10.3.0.161
solidfire-rtfi-sodium-11.0.0.761.iso
Nodes:
10.117.0.23 nlabp1023 SF3010 10.3.0.161
10.117.0.24 nlabp1025 SF3010 10.3.0.161
10.117.0.26 nlabp1027 SF3010 10.3.0.161
10.117.0.28 nlabp1028 SF3010 10.3.0.161
###################################################################
Do you want to continue? ['Yes', 'No']: yes
...
Watching for new network faults. Existing fault IDs are set([]).
Checking for legacy network interface names that need renaming
Upgrading from 10.3.0.161 to 11.0.0.761 upgrade method=rtfi
Waiting 300 seconds for cluster faults to clear
Waiting for caches to fall below threshold
...
Installing mip=[10.117.0.23] nodeID=[1] (1 of 4 nodes)
Starting to move primaries.
Loading volume list
Moving primary slice=[7] away from mip[10.117.0.23] nodeID[1] ssid[11] to new ssid[15]
Moving primary slice=[12] away from mip[10.117.0.23] nodeID[1] ssid[11] to new ssid[15]
...
Installing mip=[10.117.114.24] nodeID=[2] (2 of 4 nodes)
Starting to move primaries.
Loading volume list
Moving primary slice=[5] away from mip[10.117.114.24] nodeID[2] ssid[7] to new ssid[11]
...
Install of solidfire-rtfi-sodium-11.0.0.761 complete.
Removing old software
No staged builds present on nodeID=[1]
No staged builds present on nodeID=[2]
...
Starting light cluster block service check
----



IMPORTANT: H610S 시리즈 노드를 Element 12.3.x로 업그레이드하는 경우 노드에서 11.8 이전의 Element 버전이 실행되는 경우 추가 업그레이드 단계( )를 수행해야 합니다 H610S storage nodes to Element 12.3.x (phase 2),2단계)를 각 스토리지 노드에 대해 설정합니다. Element 11.8 이상을 실행 중인 경우 추가 업그레이드 단계(2단계)가 필요하지 않습니다.



== HealthTools를 사용하여 다크 사이트에 Element 소프트웨어를 업그레이드합니다

HealthTools 도구 제품군을 사용하면 외부 연결이 없는 어두운 사이트에서 NetApp Element 소프트웨어를 업데이트할 수 있습니다.

.무엇을 &#8217;필요로 할거야
. NetApp HCI 소프트웨어로 이동합니다 https://mysupport.netapp.com/site/products/all/details/netapp-hci/downloads-tab["다운로드 페이지"^].
. 올바른 소프트웨어 릴리즈를 선택하고 최신 스토리지 노드 이미지를 관리 노드가 아닌 컴퓨터에 다운로드합니다.
+

NOTE: Element 스토리지 소프트웨어를 업그레이드하려면 최신 버전의 HealthTools가 필요합니다.

. 이 파일을 다운로드하십시오 https://library.netapp.com/ecm/ecm_get_file/ECMLP2840740["JSON 파일"^] 관리 노드가 아닌 컴퓨터의 NetApp 지원 사이트에서 'metadata.json'으로 이름을 바꿉니다.
. ISO 파일을 '/tmp'와 같은 액세스 가능한 위치에 있는 관리 노드에 복사합니다.
+

TIP: 예를 들어 SCP를 사용하여 이 작업을 수행할 수 있습니다. ISO 파일을 업로드할 때 파일 이름이 변경되지 않는지 확인합니다. 그렇지 않으면 이후 단계가 실패합니다.



.단계
. 'fsupdate-healthtools' 명령어를 실행한다.
+
[listing]
----
sfupdate-healthtools <path-to-healthtools-package>
----
. 설치된 버전을 확인합니다.
+
[listing]
----
sfupdate-healthtools -v
----
. 메타데이터 JSON 파일과 비교하여 최신 버전을 확인합니다.
+
[listing]
----
sfupdate-healthtools -l --metadata=<path-to-metadata-json>
----
. 클러스터가 준비되었는지 확인합니다.
+
[listing]
----
sudo sfupgradecheck -u <cluster_username> -p <cluster_password> MVIP --metadata=<path-to-metadata-json>
----
. ISO 파일 경로와 메타데이터 JSON 파일 경로를 사용하여 'finstall' 명령을 실행합니다.
+
[listing]
----
sfinstall -u <cluster_username> <MVIP> <path-toinstall-file-ISO> --metadata=<path-to-metadata-json-file>
----
+
다음 샘플 입력 명령을 참조하십시오.

+
[listing]
----
sfinstall -u admin 10.117.78.244 /tmp/solidfire-rtfi-11.3.0.345.iso --metadata=/tmp/metadata.json
----
+
* 선택 사항 * '-stage' 플래그를 'finstall' 명령에 추가하여 업그레이드를 미리 준비할 수 있습니다.




IMPORTANT: H610S 시리즈 노드를 Element 12.3.x로 업그레이드하는 경우 노드에서 11.8 이전의 Element 버전이 실행되는 경우 추가 업그레이드 단계( )를 수행해야 합니다 H610S storage nodes to Element 12.3.x (phase 2),2단계)를 각 스토리지 노드에 대해 설정합니다. Element 11.8 이상을 실행 중인 경우 추가 업그레이드 단계(2단계)가 필요하지 않습니다.



== HealthTools를 사용한 업그레이드가 실패하면 어떻게 됩니까

소프트웨어 업그레이드가 실패하면 업그레이드를 일시 중지할 수 있습니다.


TIP: Ctrl-C만 사용하여 업그레이드를 일시 중지해야 합니다 이렇게 하면 시스템이 자동으로 정리됩니다.

'finstall'이 클러스터 결함이 지워지기를 기다리면서 장애가 해결되지 않으면 'finstall'은 다음 노드로 진행되지 않습니다.

.단계
. Ctrl+C를 눌러 '설치'를 중지해야 합니다
. 장애 조사에 대한 도움을 받으려면 NetApp 지원에 문의하십시오.
. 같은 'finstall' 명령을 사용하여 업그레이드를 다시 시작합니다.
. Ctrl+C를 사용하여 업그레이드가 일시 중지되면 현재 노드가 업그레이드 중인 경우 다음 옵션 중 하나를 선택합니다.
+
** * wait *: 클러스터 상수를 재설정하기 전에 현재 업그레이드 중인 노드가 완료될 수 있도록 합니다.
** * 계속 *: 업그레이드를 계속 진행하면 일시 중지가 취소됩니다.
** * Abort *: 클러스터 상수를 원래대로 설정하고 즉시 업그레이드를 중단합니다.
+

NOTE: 노드가 업데이트되는 동안 클러스터 업그레이드를 중단하면 드라이브가 노드에서 올바르게 제거되지 않을 수 있습니다. 드라이브가 올바르게 제거되지 않은 경우 업그레이드 중에 드라이브를 다시 추가하려면 NetApp Support에서 수동으로 개입해야 합니다. 노드가 펌웨어 업데이트 또는 업데이트 동기화 후 작업을 수행하는 데 시간이 더 오래 걸릴 수 있습니다. 업그레이드 진행이 멈춘 것 같다면 NetApp Support에 지원을 문의하십시오.







== H610S 스토리지 노드를 Element 12.3.x로 업그레이드(2단계)

H610S 시리즈 노드를 Element 12.3.x로 업그레이드하고 노드가 11.8 이전의 Element 버전을 실행 중인 경우 업그레이드 프로세스는 두 단계로 구성됩니다.

먼저 수행되는 1단계는 Element 12.3.x 프로세스에 대한 표준 업그레이드와 동일한 단계를 따릅니다. Element 소프트웨어와 5개의 펌웨어 업데이트를 한 번에 한 노드씩 클러스터에 모두 설치합니다. 펌웨어 페이로드로 인해 H610S 노드당 프로세스는 각 노드의 업그레이드 종료 시 단일 콜드 부팅 주기를 포함하여 약 1.5~2시간이 소요될 것으로 예상됩니다.

2단계에서는 요구 사항 에 설명된 각 H610S 노드에 대해 전체 노드 종료 및 전원 차단을 수행하기 위한 단계를 완료합니다 https://kb.netapp.com/Advice_and_Troubleshooting/Hybrid_Cloud_Infrastructure/H_Series/NetApp_H610S_storage_node_power_off_and_on_procedure["KB를 클릭합니다"^]. 이 단계는 H610S 노드당 약 1시간이 소요될 것으로 예상됩니다.


IMPORTANT: 1단계를 완료한 후 각 H610S 노드의 콜드 부팅 중에 펌웨어 업데이트 5개 중 4개가 활성화되지만, CPLD(Complex Programmable Logic Device) 펌웨어를 설치하려면 완전한 전원 차단 후 다시 연결해야 합니다. CPLD 펌웨어 업데이트는 향후 재부팅 또는 전원 사이클 중에 NVDIMM 장애 및 메타데이터 드라이브 제거를 방지합니다. 이 전원 재설정은 H610S 노드당 약 1시간이 소요될 것으로 예상됩니다. 노드를 종료하거나, 전원 케이블을 분리하거나, 스마트 PDU를 통해 전원을 분리하고, 약 3분 정도 기다린 후 전원을 다시 연결해야 합니다.

.시작하기 전에
* H610S 업그레이드 프로세스의 1단계를 완료했으며 표준 Element 스토리지 업그레이드 절차 중 하나를 사용하여 스토리지 노드를 업그레이드했습니다.



NOTE: 2단계에서는 현장 직원이 필요합니다.

.단계
. (2단계) 클러스터의 각 H610S 노드에 필요한 전원 재설정 프로세스를 완료합니다.



NOTE: 클러스터에 비 H610S 노드가 있는 경우 이러한 비 H610S 노드는 2단계에서 제외되며 시스템을 종료하거나 전원을 분리하지 않아도 됩니다.

. 지원 및 업그레이드 예약을 위해 NetApp Support에 문의하십시오.
. 이 단계의 2단계 업그레이드 절차를 따릅니다 https://kb.netapp.com/Advice_and_Troubleshooting/Hybrid_Cloud_Infrastructure/H_Series/NetApp_H610S_storage_node_power_off_and_on_procedure["KB를 클릭합니다"^] 각 H610S 노드의 업그레이드를 완료하는 데 필요합니다.


[discrete]
== 자세한 내용을 확인하십시오

* https://docs.netapp.com/us-en/vcp/index.html["vCenter Server용 NetApp Element 플러그인"^]
* https://www.netapp.com/hybrid-cloud/hci-documentation/["NetApp HCI 리소스 페이지 를 참조하십시오"^]

