---
sidebar: sidebar 
permalink: docs/task_nde_access_dhcp.html 
summary: DHCP를 사용하여 IP 주소를 할당하는 환경에서 NetApp Deployment Engine에 액세스하는 방법을 알아보십시오. 
keywords: netapp, hci, netapp deployment engine, deployment, engine, deploy, access, dhcp 
---
= DHCP를 사용하는 환경에서 NetApp 배포 엔진에 액세스합니다
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
서버가 DHCP에서 IPv4 구성을 자동으로 획득하는 환경에서는 스토리지 노드 중 하나에서 Bond1G 인터페이스에 할당된 IPv4 주소를 사용하여 NetApp 배포 엔진에 액세스할 수 있습니다. USB 스틱을 사용하여 스토리지 노드 중 하나에서 IPv4 주소를 검색할 수 있습니다. NetApp 배포 엔진은 DHCP에서 할당한 IPv4 주소를 사용하는 다른 컴퓨팅 및 스토리지 노드를 자동으로 검색합니다. 네트워크에 특별한 요구 사항이 없으면 이 방법을 사용하면 안 됩니다.

.필요한 것
* 사용자 또는 네트워크 관리자가 설치 및 설정 지침 문서의 작업을 완료했습니다.
* NetApp HCI 노드에 물리적으로 액세스할 수 있습니다.
* 모든 NetApp HCI 노드의 전원이 켜져 있습니다.
* DHCP는 NetApp HCI 관리 및 스토리지 네트워크에서 활성화됩니다.
* DHCP 주소 풀은 NetApp HCI 노드당 2개의 IPv4 주소를 수용할 수 있을 만큼 충분히 큽니다.



NOTE: NetApp HCI 배포가 성공하려면 배포의 모든 노드에 DHCP가 있거나 자동으로 구성된 IPv4 주소가 있어야 합니다(IPv4 주소 할당 방법을 혼합할 수 없음).

.이 작업에 대해
DHCP가 스토리지 네트워크(Bond10G 인터페이스)에만 사용되는 경우 링크에 설명된 단계를 사용해야 합니다. link:task_nde_access_no_dhcp.html["DHCP를 사용하지 않는 환경에서 NetApp 배포 엔진에 액세스합니다"] NetApp 배포 엔진에 액세스하는 방법

.단계
. 노드가 IP 주소를 요청할 때까지 몇 분 정도 기다립니다.
. 스토리지 노드를 선택하고 USB 스틱을 노드에 삽입합니다. 5초 이상 그대로 둡니다.
. USB 스틱을 분리하고 컴퓨터에 삽입합니다.
. readme.html 파일을 엽니다. 그러면 NetApp Deployment Engine 사용자 인터페이스가 표시됩니다.


[discrete]
== 자세한 내용을 확인하십시오

* link:firmware_driver_versions.html["NetApp HCI 스토리지 노드의 NetApp HCI 및 펌웨어 버전에 대해 지원되는 펌웨어 및 ESXi 드라이버 버전"]

