---
sidebar: sidebar 
permalink: docs/task_hcc_update_management_services.html 
summary: NetApp HCI 시스템 업그레이드의 일부로 관리 서비스를 업데이트해야 합니다. 
keywords: netapp, hci, on premise, cluster, management services 
---
= 관리 서비스를 업데이트합니다
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
관리 노드 11.3 이상을 설치한 후 관리 서비스를 최신 번들 버전으로 업데이트할 수 있습니다.

Element 11.3 관리 노드 릴리즈부터 개별 서비스를 제공하는 새로운 모듈식 아키텍처에 따라 관리 노드 설계가 변경되었습니다. 이러한 모듈식 서비스는 NetApp HCI 시스템을 위한 중앙 집중식 및 확장 관리 기능을 제공합니다. 관리 서비스에는 시스템 원격 측정, 로깅 및 업데이트 서비스, vCenter Server용 Element Plug-in용 QoSSIOC 서비스, NetApp 하이브리드 클라우드 제어 등이 포함됩니다.

.이 작업에 대해
* Element 소프트웨어를 업그레이드하기 전에 최신 관리 서비스 번들로 업그레이드해야 합니다.


[NOTE]
====
* 관리 서비스 2.22.7에는 원격 플러그인이 포함된 vCenter Server 5.0용 Element 플러그인이 포함되어 있습니다. Element 플러그인을 사용하는 경우 관리 서비스 2.22.7 이상으로 업그레이드하여 로컬 플러그인 지원을 제거하는 VMware 지침을 준수해야 합니다. https://kb.vmware.com/s/article/87880["자세한 정보"^].
* 주요 서비스, 새로운 기능, 버그 수정 사항 및 각 서비스 번들에 대한 대안을 설명하는 최신 관리 서비스 릴리즈 노트는 를 참조하십시오 https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Software/Management_services_for_Element_Software_and_NetApp_HCI/Management_Services_Release_Notes["관리 서비스 릴리즈 노트"^]


====
.필요한 것
관리 서비스 2.20.69부터 NetApp 하이브리드 클라우드 제어 UI 또는 API를 사용하여 관리 서비스를 업그레이드하기 전에 최종 사용자 라이센스 계약(EULA)에 동의해야 합니다.

. 웹 브라우저에서 관리 노드의 IP 주소를 엽니다.
+
[listing]
----
https://<ManagementNodeIP>
----
. NetApp 하이브리드 클라우드 제어에 스토리지 클러스터 관리자 자격 증명을 제공하여 로그인하십시오.
. 인터페이스의 오른쪽 상단 근처에 있는 * Upgrade * 를 선택합니다.
. EULA가 나타납니다. 아래로 스크롤하여 * 현재 업데이트 및 향후 모든 업데이트에 동의함 * 을 선택하고 * 저장 * 을 선택합니다.


.업데이트 옵션
NetApp 하이브리드 클라우드 제어 UI 또는 관리 노드 REST API를 사용하여 관리 서비스를 업데이트할 수 있습니다.

* <<하이브리드 클라우드 제어를 사용하여 관리 서비스를 업데이트합니다>> (권장 방법)
* <<관리 노드 API를 사용하여 관리 서비스를 업데이트합니다>>




== 하이브리드 클라우드 제어를 사용하여 관리 서비스를 업데이트합니다

NetApp 하이브리드 클라우드 제어를 사용하여 NetApp 관리 서비스를 업데이트할 수 있습니다.

관리 서비스 번들은 주요 릴리스 이외의 설치 시 향상된 기능과 수정 사항을 제공합니다.

.시작하기 전에
* 관리 노드 11.3 이상을 실행하고 있습니다.
* 관리 서비스를 버전 2.16 이상으로 업데이트하고 관리 노드 11.3에서 11.8을 실행 중인 경우 관리 서비스를 업데이트하기 전에 관리 노드 VM의 RAM을 늘려야 합니다.
+
.. 관리 노드 VM의 전원을 끕니다.
.. 관리 노드 VM의 RAM을 12GB에서 24GB RAM으로 변경합니다.
.. 관리 노드 VM의 전원을 켭니다.


* 클러스터 버전이 NetApp Element 소프트웨어 11.3 이상을 실행 중입니다.
* 관리 서비스를 버전 2.1.326으로 업그레이드했습니다. NetApp 하이브리드 클라우드 제어 업그레이드는 이전 서비스 번들에서 사용할 수 없습니다.



NOTE: 각 서비스 번들 버전에 대해 사용 가능한 서비스 목록은 를 참조하십시오 https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Software/Management_services_for_Element_Software_and_NetApp_HCI/Management_Services_Release_Notes["관리 서비스 릴리스 정보"^].

.단계
. 웹 브라우저에서 관리 노드의 IP 주소를 엽니다.
+
[listing]
----
https://<ManagementNodeIP>
----
. NetApp 하이브리드 클라우드 제어에 스토리지 클러스터 관리자 자격 증명을 제공하여 로그인하십시오.
. 인터페이스의 오른쪽 상단 근처에 있는 * Upgrade * 를 선택합니다.
. 업그레이드 페이지에서 * 관리 서비스 * 탭을 선택합니다.
. 페이지의 지침에 따라 관리 서비스 업그레이드 패키지를 다운로드하여 컴퓨터에 저장합니다.
. 저장한 패키지를 찾아 업로드하려면 * 찾아보기 * 를 선택합니다.
+
패키지를 업로드하면 업그레이드가 자동으로 시작됩니다.

+
업그레이드가 시작되면 이 페이지에서 업그레이드 상태를 확인할 수 있습니다. 업그레이드 중에 NetApp 하이브리드 클라우드 컨트롤과 연결이 끊어지고 업그레이드 결과를 보려면 다시 로그인해야 할 수 있습니다.





== 관리 노드 API를 사용하여 관리 서비스를 업데이트합니다

사용자는 NetApp 하이브리드 클라우드 제어에서 관리 서비스 업데이트를 수행하는 것이 이상적입니다. 하지만 REST API를 사용하여 관리 서비스에 대한 서비스 번들 업데이트를 관리 노드에 수동으로 업로드, 추출 및 배포할 수 있습니다. 관리 노드의 REST API UI에서 각 명령을 실행할 수 있습니다.

.시작하기 전에
* NetApp Element 소프트웨어 관리 노드 11.3 이상을 배포했습니다.
* 관리 서비스를 버전 2.16 이상으로 업데이트하고 관리 노드 11.3에서 11.8을 실행 중인 경우 관리 서비스를 업데이트하기 전에 관리 노드 VM의 RAM을 늘려야 합니다.
+
.. 관리 노드 VM의 전원을 끕니다.
.. 관리 노드 VM의 RAM을 12GB에서 24GB RAM으로 변경합니다.
.. 관리 노드 VM의 전원을 켭니다.


* 클러스터 버전이 NetApp Element 소프트웨어 11.3 이상을 실행 중입니다.
* 관리 서비스를 버전 2.1.326으로 업그레이드했습니다. NetApp 하이브리드 클라우드 제어 업그레이드는 이전 서비스 번들에서 사용할 수 없습니다.
+

NOTE: 각 서비스 번들 버전에 대해 사용 가능한 서비스 목록은 를 참조하십시오 https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Software/Management_services_for_Element_Software_and_NetApp_HCI/Management_Services_Release_Notes["관리 서비스 릴리스 정보"^].



.단계
. 관리 노드에서 REST API UI를 엽니다. 'https://<ManagementNodeIP>/mnode`
. authorize * 를 선택하고 다음을 완료합니다.
+
.. 클러스터 사용자 이름 및 암호를 입력합니다.
.. 값이 아직 채워지지 않은 경우 클라이언트 ID를 mnode-client로 입력합니다.
.. 세션을 시작하려면 * authorize * 를 선택합니다.
.. 창을 닫습니다.


. 'PUT/SERVICES/UPLOAD' 명령어를 이용하여 관리 노드에 서비스 번들을 업로드하고 추출한다
. 관리 노드(PUT/SERVICES/Deploy)에 관리 서비스를 배치한다
. 업데이트 상태 모니터링: 'Get/services/update/status
+
성공적으로 업데이트하면 다음 예제와 유사한 결과가 반환됩니다.

+
[listing]
----
{
"current_version": "2.10.29",
"details": "Updated to version 2.17.52",
"status": "success"
}
----


[discrete]
== 자세한 내용을 확인하십시오

* https://docs.netapp.com/us-en/vcp/index.html["vCenter Server용 NetApp Element 플러그인"^]
* https://www.netapp.com/hybrid-cloud/hci-documentation/["NetApp HCI 리소스 페이지 를 참조하십시오"^]

