---
sidebar: sidebar 
permalink: docs/task_hcc_manage_vol_access_groups.html 
summary: NetApp HCI 스토리지 볼륨에서 작업할 새 볼륨 액세스 그룹을 추가하고, 시스템에서 볼륨 액세스 그룹을 제거하고, 기존 볼륨 액세스 그룹을 편집하고, 볼륨 액세스 그룹의 세부 정보를 보는 방법에 대해 알아봅니다. 
keywords: netapp, hci, on premise, cluster, element 
---
= 볼륨 액세스 그룹을 생성하고 관리합니다
:allow-uri-read: 


[role="lead"]
NetApp 하이브리드 클라우드 제어를 사용하여 새 볼륨 액세스 그룹을 생성하거나 이름, 연결된 이니시에이터 또는 액세스 그룹의 관련 볼륨을 변경하거나 기존 볼륨 액세스 그룹을 삭제할 수 있습니다.

.필요한 것
* 이 NetApp HCI 시스템에 대한 관리자 자격 증명이 있습니다.
* 관리 서비스를 최소 버전 2.15.28로 업그레이드했습니다. NetApp 하이브리드 클라우드 제어 스토리지 관리는 이전 서비스 번들 버전에서 사용할 수 없습니다.
* 볼륨 액세스 그룹에 대한 논리적 명명 체계가 있는지 확인합니다.




== 볼륨 액세스 그룹을 추가합니다

NetApp 하이브리드 클라우드 제어를 사용하여 스토리지 클러스터에 볼륨 액세스 그룹을 추가할 수 있습니다.

.단계
. NetApp 하이브리드 클라우드 제어에 NetApp HCI 또는 Element 스토리지 클러스터 관리자 자격 증명을 제공하여 로그인하십시오.
. 대시보드의 왼쪽 탐색 메뉴에서 스토리지 클러스터 이름을 확장합니다.
. 볼륨 * 을 선택합니다.
. 액세스 그룹 * 탭을 선택합니다.
. Create Access Group * 버튼을 선택합니다.
. 결과 대화 상자에서 새 볼륨 액세스 그룹의 이름을 입력합니다.
. (선택 사항) * Initiators * 섹션에서 새 볼륨 액세스 그룹에 연결할 하나 이상의 이니시에이터를 선택합니다.
+
이니시에이터를 볼륨 액세스 그룹에 연결할 경우 해당 이니시에이터는 인증 없이 그룹의 각 볼륨에 액세스할 수 있습니다.

. (선택 사항) * 볼륨 * 섹션에서 이 볼륨 액세스 그룹에 포함할 볼륨을 하나 이상 선택합니다.
. Create Access Group * 을 선택합니다.




== 볼륨 액세스 그룹을 편집합니다

NetApp 하이브리드 클라우드 제어를 사용하여 기존 볼륨 액세스 그룹의 속성을 편집할 수 있습니다. 액세스 그룹의 이름, 연결된 이니시에이터 또는 연결된 볼륨을 변경할 수 있습니다.

.단계
. NetApp 하이브리드 클라우드 제어에 NetApp HCI 또는 Element 스토리지 클러스터 관리자 자격 증명을 제공하여 로그인하십시오.
. 대시보드의 왼쪽 탐색 메뉴에서 스토리지 클러스터 이름을 확장합니다.
. 볼륨 * 을 선택합니다.
. 액세스 그룹 * 탭을 선택합니다.
. 액세스 그룹 테이블의 * 작업 * 열에서 편집해야 하는 액세스 그룹에 대한 옵션 메뉴를 확장합니다.
. 옵션 메뉴에서 * 편집 * 을 선택합니다.
. 이름, 연결된 이니시에이터 또는 관련 볼륨을 필요에 따라 변경합니다.
. Save * 를 선택하여 변경 사항을 확인합니다.
. 액세스 그룹 * 표에서 액세스 그룹이 변경 사항을 반영하는지 확인합니다.




== 볼륨 액세스 그룹을 삭제합니다

NetApp 하이브리드 클라우드 제어를 사용하여 볼륨 액세스 그룹을 제거할 수 있으며 동시에 시스템에서 이 액세스 그룹과 연결된 이니시에이터를 제거할 수 있습니다.

.단계
. NetApp 하이브리드 클라우드 제어에 NetApp HCI 또는 Element 스토리지 클러스터 관리자 자격 증명을 제공하여 로그인하십시오.
. 대시보드의 왼쪽 탐색 메뉴에서 스토리지 클러스터 이름을 확장합니다.
. 볼륨 * 을 선택합니다.
. 액세스 그룹 * 탭을 선택합니다.
. 액세스 그룹 표의 * 작업 * 열에서 삭제할 액세스 그룹에 대한 옵션 메뉴를 확장합니다.
. 옵션 메뉴에서 * 삭제 * 를 선택합니다.
. 액세스 그룹에 연결된 이니시에이터를 삭제하지 않으려면 * 이 액세스 그룹에서 이니시에이터 삭제 * 확인란을 선택 취소합니다.
. 예 * 를 선택하여 삭제 작업을 확인합니다.


[discrete]
== 자세한 내용을 확인하십시오

* link:concept_hci_volume_access_groups.html["볼륨 액세스 그룹에 대해 알아보십시오"]
* link:task_hcc_manage_initiators.html#add-initiators-to-a-volume-access-group["볼륨 액세스 그룹에 이니시에이터를 추가합니다"]
* https://docs.netapp.com/us-en/vcp/index.html["vCenter Server용 NetApp Element 플러그인"^]
* https://www.netapp.com/hybrid-cloud/hci-documentation/["NetApp HCI 리소스 페이지 를 참조하십시오"^]

