---
sidebar: sidebar 
permalink: docs/task_hcc_expand_storage.html 
summary: NetApp HCI 구축을 마친 후에는 NetApp 하이브리드 클라우드 제어를 사용하여 NetApp HCI 스토리지 리소스를 확장하고 구성할 수 있습니다. 
keywords: netapp, hci, on premise, expand, storage, cluster 
---
= NetApp HCI 스토리지 리소스를 확장합니다
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
NetApp HCI 구축을 마친 후에는 NetApp 하이브리드 클라우드 제어를 사용하여 NetApp HCI 스토리지 리소스를 확장하고 구성할 수 있습니다.

.시작하기 전에
* 기존 노드와 동일한 네트워크 세그먼트에서 사용하지 않는 IPv4 주소가 있는지 확인합니다(각 새 노드는 해당 유형의 기존 노드와 동일한 네트워크에 설치해야 함).
* 다음 유형의 SolidFire 스토리지 클러스터 계정 중 하나가 있는지 확인합니다.
+
** 초기 배포 중에 생성된 기본 관리자 계정입니다
** 클러스터 관리자, 드라이브, 볼륨 및 노드 권한이 있는 사용자 지정 사용자 계정입니다


* 각 새 노드에서 다음 작업을 수행했는지 확인합니다.
+
** 에 따라 NetApp HCI 섀시에 새 노드를 설치했습니다 link:task_hci_installhw.html["설치 지침"].
** 케이블로 연결되고 새 노드의 전원을 켭니다


* 이미 설치된 스토리지 노드의 관리 IPv4 주소가 있는지 확인합니다. vCenter Server용 NetApp Element 플러그인의 * NetApp Element 관리 * > * 클러스터 * > * 노드 * 탭에서 IP 주소를 찾을 수 있습니다.
* 각 새 노드가 기존 스토리지 또는 컴퓨팅 클러스터와 동일한 네트워크 토폴로지 및 케이블 연결을 사용하는지 확인합니다.



TIP: 스토리지 리소스를 확장할 때 최상의 안정성을 위해 모든 섀시에 걸쳐 스토리지 용량이 균등하게 분산되어야 합니다.

.단계
. 웹 브라우저에서 관리 노드의 IP 주소를 엽니다. 예를 들면 다음과 같습니다.
+
[listing]
----
https://<ManagementNodeIP>
----
. NetApp 하이브리드 클라우드 제어에 NetApp HCI 스토리지 클러스터 관리자 자격 증명을 제공하여 로그인하십시오.
. 인터페이스의 오른쪽 위 모서리에 있는 * Expand * (확장 *)를 클릭합니다.
+
브라우저에서 NetApp 배포 엔진이 열립니다.

. 로컬 NetApp HCI 스토리지 클러스터 관리자 자격 증명을 제공하여 NetApp 배포 엔진에 로그인합니다.
+

NOTE: Lightweight Directory Access Protocol 자격 증명을 사용하여 로그인할 수 없습니다.

. 시작 * 페이지에서 * 아니요 * 를 클릭하고 * 계속 * 을 클릭합니다.
. Available Inventory * 페이지에서 추가할 스토리지 노드를 선택하고 * Continue * 를 클릭합니다.
. 네트워크 설정 * 페이지에서 일부 네트워크 정보가 초기 배포에서 감지되었습니다. 각 새 스토리지 노드는 일련 번호별로 나열되며 새 네트워크 정보를 할당해야 합니다. 각 새 스토리지 노드에 대해 다음 단계를 완료합니다.
+
.. *호스트 이름*: NetApp HCI가 이름 지정 접두사를 발견한 경우, 감지된 이름 접두사 필드에서 이름 접두사를 복사한 다음 호스트 이름 필드에 추가한 새 고유 호스트 이름의 접두사로 삽입합니다.
.. * 관리 주소 *: 관리 네트워크 서브넷 내에 있는 새 스토리지 노드의 관리 IP 주소를 입력합니다.
.. * 스토리지(iSCSI) IP 주소 *: iSCSI 네트워크 서브넷 내에 있는 새 스토리지 노드의 iSCSI IP 주소를 입력합니다.
.. 계속 * 을 클릭합니다.
+

NOTE: NetApp HCI에서 입력한 IP 주소의 유효성을 확인하는 데 시간이 걸릴 수 있습니다. IP 주소 확인이 완료되면 계속 단추를 사용할 수 있습니다.



. 네트워크 설정 섹션의 * 검토 * 페이지에서 새 노드가 굵은 텍스트로 표시됩니다. 섹션을 변경하려면 다음을 실행합니다.
+
.. 해당 섹션에 대해 * 편집 * 을 클릭합니다.
.. 작업을 마치면 다음 페이지에서 * 계속 * 을 클릭하여 검토 페이지로 돌아갑니다.


. * 선택 사항 *: 클러스터 통계 및 지원 정보를 NetApp이 호스팅하는 Active IQ 서버로 전송하지 않으려면 마지막 확인란의 선택을 취소합니다.
+
이렇게 하면 NetApp HCI에 대한 실시간 상태 및 진단 모니터링이 비활성화됩니다. 이 기능을 비활성화하면 NetApp이 사전에 NetApp HCI를 지원 및 모니터링하여 프로덕션에 영향을 미치기 전에 문제를 감지하고 해결할 수 없습니다.

. 노드 추가 * 를 클릭합니다.
+
NetApp HCI에서 리소스를 추가하고 구성하는 동안 진행률을 모니터링할 수 있습니다.

. * 선택 사항 *: vCenter Server용 Element 플러그인에 새 스토리지 노드가 표시되는지 확인합니다.
+

NOTE: 2노드 스토리지 클러스터를 4개 이상의 노드로 확장한 경우 스토리지 클러스터에서 이전에 사용한 Witness 노드 쌍은 vSphere에서 대기 가상 머신으로 계속 표시됩니다. 새로 확장된 스토리지 클러스터는 이러한 스토리지 클러스터를 사용하지 않으므로 VM 리소스를 회수하려는 경우 link:task_hci_removewn.html["수동으로 제거합니다"] Witness Node 가상 머신



[discrete]
== 자세한 내용을 확인하십시오

* https://docs.netapp.com/us-en/vcp/index.html["vCenter Server용 NetApp Element 플러그인"^]
* https://www.netapp.com/hybrid-cloud/hci-documentation/["NetApp HCI 리소스 페이지 를 참조하십시오"^]

