---
sidebar: sidebar 
permalink: docs/task_nde_select_inventory.html 
summary: 배포 중에 NetApp HCI 노드 인벤토리를 선택하는 방법에 대해 알아봅니다. 
keywords: netapp, hci, deployment, compatibility, nodes 
---
= 재고를 선택합니다
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Inventory * 페이지에서 NetApp Deployment Engine은 사용 가능한 컴퓨팅 및 스토리지 노드를 자동으로 감지하여 모든 NetApp HCI 리소스를 선택하여 배포에 추가할 수 있도록 합니다. 노드가 구축 요구 사항을 충족하지 않는 경우 선택할 수 없으며 문제가 오류로 표시됩니다. 노드 행의 오류 위에 커서를 놓으면 설명을 볼 수 있습니다. 인벤토리 페이지에서 노드 인벤토리를 선택할 경우 NetApp 배포 엔진을 호스팅하는 스토리지 노드가 자동으로 선택되며 선택을 취소할 수 없습니다.

.필요한 것
적절한 인벤토리 검색을 위해 점보 프레임을 활성화해야 합니다. 인벤토리에 노드가 없거나 일부 노드만 표시되는 경우 NetApp HCI 노드에 사용되는 스위치 포트(모든 SFP+/SFP28 인터페이스)가 점보 프레임으로 구성되어 있는지 확인합니다.

.단계
. Inventory * 페이지에서 사용 가능한 노드 목록을 봅니다.
+
시스템에서 인벤토리를 감지할 수 없는 경우 오류가 표시됩니다. 계속하기 전에 오류를 수정하십시오. 시스템에서 IP 주소 할당에 DHCP를 사용하는 경우 저장소 및 컴퓨팅 리소스가 인벤토리에 즉시 나타나지 않을 수 있습니다.

. 선택 사항: 리소스가 인벤토리에 즉시 나타나지 않거나 오류를 해결하고 재고를 새로 고쳐야 하는 경우 * 재고 새로 고침 * 을 클릭합니다. 재고를 여러 번 새로 고쳐야 할 수 있습니다.
. 선택 사항: 노드 유형과 같은 노드 속성에서 인벤토리를 필터링하려면 다음을 수행합니다.
+
.. Compute Nodes * 또는 * Storage Nodes * 목록의 헤더에서 * Filter * 를 클릭합니다.
.. 드롭다운 목록에서 조건을 선택합니다.
.. 드롭다운 목록 아래에 기준을 충족하는 정보를 입력합니다.
.. 필터 추가 * 를 클릭합니다.
.. 활성 필터 옆에 있는 * X * 를 클릭하여 개별 필터를 지우거나 필터 목록 위에 있는 * X * 를 클릭하여 모든 필터를 지웁니다.


. 시스템과 함께 제공된 모든 컴퓨팅 노드를 * 컴퓨팅 노드 * 목록에서 선택합니다.
+
구축을 진행하려면 컴퓨팅 노드를 두 개 이상 선택해야 합니다.

. 시스템과 함께 제공된 모든 스토리지 노드를 * 스토리지 노드 * 목록에서 선택합니다.
+
구축을 계속하려면 스토리지 노드를 두 개 이상 선택해야 합니다.

. 선택 사항: 스토리지 노드 선택 상자에 플래그가 지정된 경우 해당 스토리지 노드가 전체 스토리지 클러스터 용량의 33%를 초과합니다. 다음 중 하나를 수행합니다.
+
** 플래그가 지정된 스토리지 노드에 대한 선택 상자의 선택을 취소합니다.
** 스토리지 클러스터 용량을 노드 간에 균등하게 분산하려면 추가 스토리지 노드를 선택합니다.


. 계속 * 을 클릭합니다.




== 자세한 내용을 확인하십시오

* https://docs.netapp.com/us-en/vcp/index.html["vCenter Server용 NetApp Element 플러그인"^]
* https://www.netapp.com/us/documentation/hci.aspx["NetApp HCI 리소스 페이지를 참조하십시오"^]
* https://docs.netapp.com/us-en/element-software/index.html["SolidFire 및 Element 소프트웨어 설명서"^]

