---
sidebar: sidebar 
permalink: docs/task_mnode_run_system_utilities.html 
summary: 클러스터 지원 번들을 생성 또는 삭제하거나, 노드 구성 설정을 재설정하거나, 네트워킹을 다시 시작할 수 있습니다. 
keywords: netapp, element, management node ui, mnode ui, system utilities 
---
= 관리 노드에서 시스템 유틸리티를 실행합니다
:allow-uri-read: 


[role="lead"]
관리 노드의 노드별 UI를 사용하여 클러스터 지원 번들을 생성 또는 삭제하거나 노드 구성 설정을 재설정하거나 네트워킹을 다시 시작할 수 있습니다.

.단계
. 관리 노드 관리 자격 증명을 사용하여 노드별 관리 노드 UI를 엽니다.
. 시스템 유틸리티 * 를 클릭합니다.
. 실행할 유틸리티의 단추를 클릭합니다.
+
.. * 컨트롤 전원 *: 노드를 재부팅, 전원 사이클 또는 종료합니다. 다음 옵션 중 하나를 지정합니다.
+

IMPORTANT: 이 작업으로 인해 네트워크 연결이 일시적으로 끊기게 됩니다.

+
*** [동작] *: '재시작'과 '중지'(전원 끄기)가 있습니다.
*** * Wakeup Delay *: 노드가 다시 온라인 상태가 되기 전에 추가 시간이 필요합니다.


.. * 클러스터 지원 번들 생성 *: 클러스터에서 하나 이상의 노드에 대한 NetApp 지원 진단 평가를 돕기 위해 클러스터 지원 번들을 생성합니다. 다음 옵션을 지정합니다.
+
*** * 번들 이름 *: 생성된 각 지원 번들의 고유 이름입니다. 이름이 제공되지 않으면 "supportbundle"과 노드 이름이 파일 이름으로 사용됩니다.
*** * Mvip *: 클러스터의 MVIP. 번들은 클러스터의 모든 노드에서 수집됩니다. Nodes 매개 변수를 지정하지 않은 경우 이 매개 변수가 필요합니다.
*** * 노드 *: 번들을 수집할 노드의 IP 주소입니다. 노드 또는 Mvip 중 하나를 사용합니다. 두 노드 모두 사용할 수는 없습니다. 번들을 수집할 노드를 지정합니다. Mvip을 지정하지 않은 경우 이 매개 변수가 필요합니다.
*** * 사용자 이름 *: 클러스터 관리자 사용자 이름입니다.
*** * 암호 *: 클러스터 관리자 암호입니다.
*** * 불완전 허용 *: 하나 이상의 노드에서 번들을 수집할 수 없는 경우 스크립트를 계속 실행할 수 있습니다.
*** extra Args *: 이 파라미터는 'f_make_support_bundle' 스크립트에 입력된다. 이 매개 변수는 NetApp Support의 요청에만 사용해야 합니다.


.. * 모든 지원 번들 삭제 *: 관리 노드의 현재 지원 번들을 삭제합니다.
.. * 노드 재설정 *: 관리 노드를 새 설치 이미지로 재설정합니다. 이렇게 하면 네트워크 구성을 제외한 모든 설정이 기본 상태로 변경됩니다. 다음 옵션을 지정합니다.
+
*** * 빌드 *: 노드를 재설정할 원격 요소 소프트웨어 이미지의 URL입니다.
*** * 옵션 *: 재설정 작업 실행을 위한 사양. 자세한 내용은 필요한 경우 NetApp Support에서 제공합니다.
+

IMPORTANT: 이 작업으로 인해 네트워크 연결이 일시적으로 끊기게 됩니다.



.. * 네트워킹 재시작 *: 관리 노드에서 모든 네트워킹 서비스를 다시 시작합니다.
+

IMPORTANT: 이 작업으로 인해 네트워크 연결이 일시적으로 끊기게 됩니다.







== 자세한 내용을 확인하십시오

https://docs.netapp.com/us-en/vcp/index.html["vCenter Server용 NetApp Element 플러그인"^]
