---
sidebar: sidebar 
permalink: docs/task_nde_install_GPU_drivers.html 
summary: NetApp HCI를 구축한 후 GPU 지원 컴퓨팅 노드용 GPU 드라이버를 설치하는 방법에 대해 알아보십시오. 
keywords: netapp, hci, deployment, review, GPU, install, driver, drivers 
---
= GPU 지원 컴퓨팅 노드용 GPU 드라이버를 설치합니다
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
H610C와 같은 NVIDIA 그래픽 처리 장치(GPU)를 사용하는 컴퓨팅 노드에는 VMware ESXi에 NVIDIA 소프트웨어 드라이버가 설치되어 있어 증가된 처리 능력을 활용할 수 있습니다. GPU로 컴퓨팅 노드를 구축한 후 각 GPU 지원 컴퓨팅 노드에서 다음 단계를 수행하여 ESXi에 GPU 드라이버를 설치해야 합니다.

.단계
. 브라우저를 열고 다음 URL에서 NVIDIA 라이센싱 포털로 이동합니다.
+
[listing]
----
https://nvid.nvidia.com/dashboard/
----
. 환경에 따라 다음 드라이버 패키지 중 하나를 컴퓨터에 다운로드합니다.
+
|===
| vSphere 버전입니다 | 드라이버 패키지 


| vSphere 6.5 | nVidia-GRID-vSphere-6.5-410.92-410.91-412.16.zip 


| vSphere 6.7 | nVidia-GRID-vSphere-6.7-410.92-410.91-412.16.zip 
|===
. 컴퓨터에서 드라이버 패키지를 추출합니다.
+
그 결과 .vIB 파일은 압축되지 않은 드라이버 파일입니다.

. 컴퓨터의 '.vIB' 드라이버 파일을 컴퓨팅 노드에서 실행 중인 ESXi로 복사합니다. 각 버전에 대한 다음 명령 예에서는 드라이버가 관리 호스트의 '$HOME/nvidia/ESX6.x/' 디렉토리에 있다고 가정합니다. SCP 유틸리티는 대부분의 Linux 배포판에서 쉽게 사용할 수 있으며 모든 Windows 버전에 대해 다운로드 가능한 유틸리티로 사용할 수 있습니다.
+
|===
| ESXi 버전입니다 | 설명 


| ESXi 6.5 | sp$home/nvidia/ESX6.5/nvidia**.vib root@<esxi_ip_addr>:/.' 


| ESXi 6.7 | 'sp$home/nvidia/ESX6.7/nvidia**.vib root@<esxi_ip_addr>:/.' 
|===
. 다음 단계를 수행하여 ESXi 호스트에 루트로 로그인하고 ESXi에 NVIDIA vGPU Manager를 설치합니다.
+
.. 다음 명령을 실행하여 ESXi 호스트에 루트 사용자로 로그인합니다.
+
[listing]
----
ssh root@<ESXi_IP_ADDRESS>
----
.. 다음 명령을 실행하여 현재 설치된 NVIDIA GPU 드라이버가 없는지 확인합니다.
+
[listing]
----
nvidia-smi
----
+
이 명령을 실행하면 NVIDIA-SMI:NOT FOUND(NVIDIA-SMI:찾을 수 없음) 메시지가 반환됩니다.

.. 다음 명령을 실행하여 호스트에서 유지보수 모드를 활성화하고 VIB 파일에서 NVIDIA vGPU Manager를 설치합니다.
+
[listing]
----
esxcli system maintenanceMode set --enable true
esxcli software vib install -v /NVIDIA**.vib
----
+
"작업이 성공적으로 완료되었습니다."라는 메시지가 표시됩니다.

.. 다음 명령을 실행하고 명령 출력에 8개의 GPU 드라이버가 모두 나열되어 있는지 확인합니다.
+
[listing]
----
nvidia-smi
----
.. 다음 명령을 실행하여 NVIDIA vGPU 패키지가 올바르게 설치 및 로드되었는지 확인합니다.
+
[listing]
----
vmkload_mod -l | grep nvidia
----
+
이 명령은 다음과 유사한 출력을 반환해야 합니다: nVidia 816 13808

.. 다음 명령을 실행하여 호스트를 재부팅합니다.
+
[listing]
----
reboot -f
----
.. 다음 명령을 실행하여 유지보수 모드를 종료합니다.
+
[listing]
----
esxcli system maintenanceMode set --enable false
----


. NVIDIA GPU를 사용하여 새로 구축된 다른 컴퓨팅 노드에 대해 4-6단계를 반복합니다.
. NVIDIA 문서 사이트의 지침에 따라 다음 작업을 수행합니다.
+
.. NVIDIA 라이센스 서버를 설치합니다.
.. NVIDIA vGPU 소프트웨어의 가상 머신 게스트를 구성합니다.
.. 가상 데스크톱 인프라(VDI)에서 vGPU 지원 데스크톱을 사용하는 경우 NVIDIA vGPU 소프트웨어용 VMware Horizon View를 구성합니다.






== 자세한 내용을 확인하십시오

* https://www.netapp.com/us/documentation/hci.aspx["NetApp HCI 리소스 페이지를 참조하십시오"^]
* https://docs.netapp.com/us-en/element-software/index.html["SolidFire 및 Element 소프트웨어 설명서"^]

