---
sidebar: sidebar 
permalink: docs/task_hcc_manage_accounts.html 
summary: 사용자 계정을 만들고 볼륨과 연결하는 방법에 대해 알아봅니다. 
keywords: netapp, hci, on premise, cluster, element, account, user, volume, hybrid cloud control, hcc 
---
= NetApp 하이브리드 클라우드 제어를 사용하여 사용자 계정을 만들고 관리합니다
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Element 기반 스토리지 시스템에서 권한 있는 클러스터 사용자를 생성하여 "관리자" 또는 "읽기 전용" 사용자에게 부여할 사용 권한에 따라 NetApp 하이브리드 클라우드 제어에 대한 로그인 액세스를 허용할 수 있습니다. 클러스터 사용자 외에도 볼륨 계정이 있어 클라이언트가 스토리지 노드의 볼륨에 연결할 수 있습니다. 

다음 유형의 계정을 관리합니다.

* <<Manage authoritative cluster accounts>>
* <<Manage volume accounts>>




== LDAP를 설정합니다

모든 사용자 계정에 LDAP를 사용하려면 먼저 LDAP를 활성화해야 합니다.

.단계
. NetApp 하이브리드 클라우드 제어에 NetApp HCI 또는 Element 스토리지 클러스터 관리자 자격 증명을 제공하여 로그인하십시오.
. 대시보드에서 오른쪽 위 옵션 아이콘을 클릭하고 * 사용자 관리 * 를 선택합니다.
. 사용자 페이지에서 * LDAP 구성 * 을 클릭합니다.
. LDAP 구성을 정의합니다.
. Search and Bind 또는 Direct Bind의 인증 유형을 선택합니다.
. 변경 사항을 저장하기 전에 페이지 상단의 * LDAP 로그인 테스트 * 를 클릭하고, 이미 알고 있는 사용자의 사용자 이름과 암호를 입력한 다음 * 테스트 * 를 클릭합니다.
. 저장 * 을 클릭합니다.




== 권한 있는 클러스터 계정을 관리합니다

link:concept_cg_hci_accounts.html#authoritative-user-accounts["권한 있는 사용자 계정"] NetApp 하이브리드 클라우드 제어의 오른쪽 상단 메뉴 사용자 관리 옵션에서 관리합니다. 이러한 유형의 계정을 사용하면 노드 및 클러스터의 NetApp 하이브리드 클라우드 제어 인스턴스와 연결된 스토리지 자산에 대해 인증을 받을 수 있습니다. 이 계정을 사용하면 모든 클러스터에서 볼륨, 계정, 액세스 그룹 등을 관리할 수 있습니다.



=== 권한 있는 클러스터 계정을 생성합니다

NetApp 하이브리드 클라우드 제어를 사용하여 계정을 생성할 수 있습니다.

이 계정을 사용하여 하이브리드 클라우드 제어, 클러스터의 노드별 UI 및 NetApp Element 소프트웨어의 스토리지 클러스터에 로그인할 수 있습니다.

.단계
. NetApp 하이브리드 클라우드 제어에 NetApp HCI 또는 Element 스토리지 클러스터 관리자 자격 증명을 제공하여 로그인하십시오.
. 대시보드에서 오른쪽 위 옵션 아이콘을 클릭하고 * 사용자 관리 * 를 선택합니다.
. 사용자 생성 * 을 선택합니다.
. 클러스터 또는 LDAP의 인증 유형을 선택합니다.
. 다음 중 하나를 완료합니다.
+
** LDAP를 선택한 경우 DN을 입력합니다.
+

TIP: LDAP를 사용하려면 먼저 LDAP 또는 LDAPS를 활성화해야 합니다. 을 참조하십시오 <<Enable LDAP>>.

** 인증 유형으로 클러스터 를 선택한 경우 새 계정의 이름과 암호를 입력합니다.


. 관리자 또는 읽기 전용 권한을 선택합니다.
+

TIP: NetApp Element 소프트웨어의 사용 권한을 보려면 * 레거시 사용 권한 표시 * 를 클릭합니다. 이러한 권한의 하위 집합을 선택하면 계정에 읽기 전용 권한이 할당됩니다. 모든 기존 권한을 선택하면 계정에 관리자 권한이 할당됩니다.

+

TIP: 그룹의 모든 하위 구성원이 사용 권한을 상속하도록 하려면 LDAP 서버에 DN 조직 관리 그룹을 만듭니다. 해당 그룹의 모든 하위 계정은 해당 권한을 상속합니다.

. "NetApp 최종 사용자 라이센스 계약을 읽고 동의합니다."를 나타내는 상자를 선택합니다.
. 사용자 생성 * 을 클릭합니다.




=== 권한 있는 클러스터 계정을 편집합니다

NetApp 하이브리드 클라우드 제어를 사용하여 사용자 계정의 사용 권한이나 암호를 변경할 수 있습니다.

.단계
. NetApp 하이브리드 클라우드 제어에 NetApp HCI 또는 Element 스토리지 클러스터 관리자 자격 증명을 제공하여 로그인하십시오.
. 대시보드에서 오른쪽 상단의 아이콘을 클릭하고 * 사용자 관리 * 를 선택합니다.
. 선택적으로 * Cluster *, * LDAP * 또는 * IDP * 를 선택하여 사용자 계정 목록을 필터링합니다.
+
LDAP를 사용하여 스토리지 클러스터의 사용자를 구성한 경우 해당 계정에는 사용자 유형이 "LDAP"로 표시됩니다. IdP를 사용하여 스토리지 클러스터의 사용자를 구성한 경우 해당 계정에는 "IDP"의 사용자 유형이 표시됩니다.

. 테이블의 * Actions * 열에서 계정 메뉴를 확장하고 * Edit * 를 선택합니다.
. 필요에 따라 변경합니다.
. 저장 * 을 선택합니다.
. NetApp 하이브리드 클라우드 제어에서 로그아웃
. link:task_mnode_manage_storage_cluster_assets.html#edit-the-stored-credentials-for-a-storage-cluster-asset["자격 증명을 업데이트합니다"] NetApp 하이브리드 클라우드 제어 API를 사용하여 권한 있는 클러스터 자산에 대해
+

NOTE: NetApp 하이브리드 클라우드 제어 UI에서 재고를 업데이트하는 데 최대 2분이 걸릴 수 있습니다. 재고를 수동으로 새로 고치려면 REST API UI 인벤토리 서비스 https://<ManagementNodeIP>/inventory/1/` 액세스하여 클러스터에 대해 Get/installsi./{id}를 실행합니다.

. NetApp 하이브리드 클라우드 제어에 로그인




=== 권한 있는 사용자 계정을 삭제합니다

더 이상 필요하지 않은 계정을 하나 이상 삭제할 수 있습니다. LDAP 사용자 계정을 삭제할 수 있습니다.

권한 있는 클러스터에 대한 기본 관리자 사용자 계정은 삭제할 수 없습니다.

.단계
. NetApp 하이브리드 클라우드 제어에 NetApp HCI 또는 Element 스토리지 클러스터 관리자 자격 증명을 제공하여 로그인하십시오.
. 대시보드에서 오른쪽 상단의 아이콘을 클릭하고 * 사용자 관리 * 를 선택합니다.
. 사용자 테이블의 * 작업 * 열에서 계정 메뉴를 확장하고 * 삭제 * 를 선택합니다.
. 예 * 를 선택하여 삭제를 확인합니다.




== 볼륨 계정 관리

link:concept_cg_hci_accounts.html#volume-accounts["볼륨 계정"] NetApp 하이브리드 클라우드 제어 볼륨 표 내에서 관리됩니다. 이러한 계정은 생성된 스토리지 클러스터에만 한정됩니다. 이러한 유형의 계정을 사용하면 네트워크 전체의 볼륨에 대한 권한을 설정할 수 있지만, 이러한 볼륨 외부에는 영향을 미치지 않습니다.

볼륨 계정에는 할당된 볼륨에 액세스하는 데 필요한 CHAP 인증이 포함되어 있습니다.



=== 볼륨 계정을 생성합니다

이 볼륨에 해당하는 계정을 생성합니다.

.단계
. NetApp 하이브리드 클라우드 제어에 NetApp HCI 또는 Element 스토리지 클러스터 관리자 자격 증명을 제공하여 로그인하십시오.
. 대시보드에서 * Storage * > * Volumes * 를 선택합니다.
. Accounts * 탭을 선택합니다.
. 계정 만들기 * 버튼을 선택합니다.
. 새 계정의 이름을 입력합니다.
. CHAP 설정 섹션에서 다음 정보를 입력합니다.
+
** CHAP 노드 세션 인증을 위한 이니시에이터 암호
** CHAP 노드 세션 인증을 위한 타겟 암호
+

NOTE: 두 암호를 자동으로 생성하려면 자격 증명 필드를 비워 둡니다.



. 계정 만들기 * 를 선택합니다.




=== 볼륨 계정을 편집합니다

CHAP 정보를 변경하고 계정이 활성 상태인지 또는 잠겨 있는지 여부를 변경할 수 있습니다.


IMPORTANT: 관리 노드와 연결된 계정을 삭제하거나 잠그면 관리 노드에 액세스할 수 없게 됩니다.

.단계
. NetApp 하이브리드 클라우드 제어에 NetApp HCI 또는 Element 스토리지 클러스터 관리자 자격 증명을 제공하여 로그인하십시오.
. 대시보드에서 * Storage * > * Volumes * 를 선택합니다.
. Accounts * 탭을 선택합니다.
. 테이블의 * Actions * 열에서 계정 메뉴를 확장하고 * Edit * 를 선택합니다.
. 필요에 따라 변경합니다.
. 예 * 를 선택하여 변경 사항을 확인합니다.




=== 볼륨 계정을 삭제합니다

더 이상 필요하지 않은 계정을 삭제합니다.

볼륨 계정을 삭제하기 전에 먼저 계정과 연결된 볼륨을 삭제하고 제거하십시오.


IMPORTANT: 관리 노드와 연결된 계정을 삭제하거나 잠그면 관리 노드에 액세스할 수 없게 됩니다.


NOTE: 관리 서비스와 연결된 영구 볼륨은 설치 또는 업그레이드 중에 새 계정에 할당됩니다. 영구 볼륨을 사용하는 경우 볼륨이나 연결된 계정을 수정하거나 삭제하지 마십시오. 이러한 계정을 삭제하면 관리 노드를 사용할 수 없게 될 수 있습니다.

.단계
. NetApp 하이브리드 클라우드 제어에 NetApp HCI 또는 Element 스토리지 클러스터 관리자 자격 증명을 제공하여 로그인하십시오.
. 대시보드에서 * Storage * > * Volumes * 를 선택합니다.
. Accounts * 탭을 선택합니다.
. 테이블의 * Actions * 열에서 계정 메뉴를 확장하고 * Delete * 를 선택합니다.
. 예 * 를 선택하여 삭제를 확인합니다.


[discrete]
== 자세한 내용을 확인하십시오

* link:concept_hci_accounts.html["어카운트에 대해 알아보십시오"]
* http://docs.netapp.com/sfe-122/topic/com.netapp.doc.sfe-ug/GUID-E93D3BAF-5A60-414D-86AF-0C1F86D43F26.html["사용자 계정 작업"^]
* https://docs.netapp.com/us-en/vcp/index.html["vCenter Server용 NetApp Element 플러그인"^]
* https://www.netapp.com/hybrid-cloud/hci-documentation/["NetApp HCI 리소스 페이지 를 참조하십시오"^]

