---
sidebar: sidebar 
permalink: docs/task_trident_configure_networking.html 
summary: 사용자 클러스터에 대한 Trident 지원을 활성화합니다. 
keywords: netapp, hci, netapp, networking, clusters, user, trident, rancher 
---
= 사용자 클러스터에 대한 Trident 지원을 활성화합니다
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
NetApp HCI 환경에 관리 네트워크와 스토리지 네트워크 간의 경로가 없고 Trident가 필요한 사용자 클러스터를 배포하는 경우, Trident를 설치한 후 사용자 클러스터 네트워크를 추가로 구성해야 합니다. 각 사용자 클러스터에 대해 관리와 스토리지 네트워크 간의 통신을 활성화해야 합니다. 사용자 클러스터의 각 노드에 대한 네트워킹 구성을 수정하여 이 작업을 수행할 수 있습니다.

.이 작업에 대해
사용자 클러스터의 각 노드에 대한 네트워킹 구성을 수정하려면 다음 일반 단계를 따르십시오. 다음 단계에서는 NetApp HCI에 Rancher가 설치된 기본 노드 템플릿을 사용하여 사용자 클러스터를 생성했다고 가정합니다.


NOTE: 이러한 변경 사항을 사용자 지정 노드 템플릿의 일부로 만들어 향후 사용자 클러스터에 사용할 수 있습니다.

.단계
. 기존 기본 템플릿을 사용하여 사용자 클러스터를 배포합니다.
. 스토리지 네트워크를 사용자 클러스터에 연결합니다.
+
.. 연결된 vCenter 인스턴스에 대해 VMware vSphere 웹 클라이언트를 엽니다.
.. Hosts and Clusters 인벤토리 트리에서 새로 구축된 사용자 클러스터의 노드를 선택합니다.
.. 노드의 설정을 편집합니다.
.. 설정 대화 상자에서 새 네트워크 어댑터를 추가합니다.
.. 새 네트워크 * 드롭다운 목록에서 네트워크를 찾아 * hci_Internal_Storage_Data_Network * 를 선택합니다.
.. 네트워크 어댑터 섹션을 확장하고 새 네트워크 어댑터의 MAC 주소를 기록합니다.
.. 확인 * 을 클릭합니다.


. Rancher에서 사용자 클러스터의 각 노드에 대한 SSH 개인 키 파일을 다운로드합니다.
. 해당 노드에 대해 다운로드한 개인 키 파일을 사용하여 SSH를 사용하여 사용자 클러스터의 노드에 연결합니다.
+
[listing]
----
ssh -i <private key filename> <ip address>
----
. 슈퍼유저로 '/etc/netplan/50-cloud-init.YAML' 파일을 편집하여 저장하면 다음 예와 유사한 ens224' 섹션이 포함됩니다. "<MAC 주소>"를 이전에 녹음한 MAC 주소로 바꿉니다.
+
[listing]
----
network:
    ethernets:
        ens192:
            dhcp4: true
            match:
                macaddress: 00:50:56:91:1d:41
            set-name: ens192
        ens224:
            dhcp4: true
            match:
                macaddress: <MAC address>
            set-name: ens224
    version: 2
----
. 다음 명령을 사용하여 네트워크를 재구성합니다.
+
[listing]
----
`netplan try`
----
. 사용자 클러스터의 나머지 각 노드에 대해 4-6단계를 반복합니다.
. 사용자 클러스터의 각 노드에 대해 네트워크를 재구성한 경우 Trident를 사용하는 사용자 클러스터에 애플리케이션을 배포할 수 있습니다.

