---
sidebar: sidebar 
permalink: docs/task_mnode_multi_vcenter_config.html 
summary: NetApp 하이브리드 클라우드 제어에서 REST API UI를 사용하여 여러 vCenter를 사용하도록 구성할 수 있습니다. 
keywords: netapp, mnode, management node, multi-vcenter, hci 
---
= NetApp 하이브리드 클라우드 제어를 여러 vCenter에 맞게 구성합니다
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
NetApp 하이브리드 클라우드 제어를 구성하여 Linked Mode를 사용하지 않는 둘 이상의 vCenter에서 자산을 관리할 수 있습니다.

초기 설치 후 최근에 확장된 설치를 위해 자산을 추가해야 하거나 새 자산이 구성에 자동으로 추가되지 않은 경우 이 프로세스를 사용해야 합니다. 이러한 API를 사용하여 최근 설치에 추가된 자산을 추가하십시오.

.필요한 것
* 클러스터 버전이 NetApp Element 소프트웨어 11.3 이상을 실행 중입니다.
* 버전 11.3 이상을 실행하는 관리 노드를 배포했습니다.


.단계
. link:task_mnode_add_assets.html["새 vCenter를 컨트롤러 자산으로 추가합니다"] 관리 노드 구성으로
. link:task_mnode_add_assets.html["새 컴퓨팅 노드를 컴퓨팅 자산으로 추가합니다"] 관리 노드 구성으로
+

NOTE: 필요한 경우도 있습니다 link:task_hcc_edit_bmc_info.html["컴퓨팅 노드의 BMC 자격 증명을 변경합니다"] NetApp 하이브리드 클라우드 제어에서 나타나는 '하드웨어 ID를 사용할 수 없음' 또는 '감지할 수 없음' 오류를 해결하기 위해

. 관리 노드에서 인벤토리 서비스 API를 새로 고칩니다.
+
[listing]
----
https://<ManagementNodeIP>/inventory/1/
----
+

NOTE: 또는 NetApp 하이브리드 클라우드 제어 UI에서 인벤토리가 업데이트될 때까지 2분 정도 기다릴 수 있습니다.

+
.. authorize * 를 클릭하고 다음을 완료합니다.
+
... 클러스터 사용자 이름 및 암호를 입력합니다.
... Client ID를 mnode-client로 입력한다.
... 세션을 시작하려면 * authorize * 를 클릭합니다.
... 창을 닫습니다.


.. REST API UI에서 * Get Windows/Installations * 를 클릭합니다.
.. 체험하기 * 를 클릭합니다.
.. Execute * 를 클릭합니다.
.. 응답에서 설치 자산 ID(""id"")를 복사합니다.
.. REST API UI에서 * get/Installations/{id} * 를 클릭합니다.
.. 체험하기 * 를 클릭합니다.
.. 새로 고침을 True로 설정합니다.
.. 설치 자산 ID를 * id * 필드에 붙여 넣습니다.
.. Execute * 를 클릭합니다.


. NetApp 하이브리드 클라우드 제어 브라우저를 새로고침하여 변경 사항을 확인하십시오.




== 자세한 내용을 확인하십시오

https://docs.netapp.com/us-en/vcp/index.html["vCenter Server용 NetApp Element 플러그인"^]
