---
sidebar: sidebar 
permalink: docs/task_nde_access_ui_fqdn.html 
summary: 시스템 FQDN 웹 UI 액세스를 구성, 제거 및 해결하는 방법에 대해 알아봅니다. 
keywords: netapp, hci, fqdn, ui, access, web, administration 
---
= 정규화된 도메인 이름 웹 UI 액세스를 구성합니다
:allow-uri-read: 


[role="lead"]
Element 소프트웨어가 포함된 NetApp HCI 12.2 이상을 사용하면 FQDN(정규화된 도메인 이름)을 사용하여 스토리지 클러스터 웹 인터페이스에 액세스할 수 있습니다. FQDN을 사용하여 Element 웹 UI, 노드별 UI 또는 관리 노드 UI와 같은 웹 사용자 인터페이스에 액세스하려면 먼저 스토리지 클러스터 설정을 추가하여 클러스터에서 사용되는 FQDN을 식별해야 합니다.

이제 FQDN(정규화된 도메인 이름)을 사용하여 스토리지 클러스터 웹 인터페이스에 액세스할 수 있습니다. FQDN을 사용하여 Element 웹 UI, 노드별 UI 또는 관리 노드 UI와 같은 웹 사용자 인터페이스에 액세스하려면 먼저 스토리지 클러스터 설정을 추가하여 클러스터에서 사용되는 FQDN을 식별해야 합니다. 이를 통해 클러스터는 로그인 세션을 적절하게 리디렉션하고 다중 요소 인증을 위한 키 관리자 및 ID 공급자와 같은 외부 서비스와의 통합을 향상시킬 수 있습니다.

.무엇을 &#8217;필요로 할거야
* 이 기능을 사용하려면 Element 12.2 이상이 필요합니다.
* NetApp 하이브리드 클라우드 제어 REST API를 사용하여 이 기능을 구성하려면 관리 서비스 2.15 이상이 필요합니다.
* NetApp 하이브리드 클라우드 제어 UI를 사용하여 이 기능을 구성하려면 관리 서비스 2.19 이상이 필요합니다.
* REST API를 사용하려면 버전 11.5 이상을 실행하는 관리 노드를 구축해야 합니다.
* 관리 노드 IP 주소 및 각 스토리지 클러스터 IP 주소로 올바르게 확인되는 각 스토리지 클러스터와 관리 노드에 대해 정규화된 도메인 이름이 필요합니다.


NetApp 하이브리드 클라우드 제어 및 REST API를 사용하여 FQDN 웹 UI 액세스를 구성하거나 제거할 수 있습니다. 또한 잘못 구성된 FQDN의 문제를 해결할 수도 있습니다.

* <<Configure FQDN web UI access using NetApp Hybrid Cloud Control>>
* <<Configure FQDN web UI access using the REST API>>
* <<Remove FQDN web UI access using NetApp Hybrid Cloud Control>>
* <<Remove FQDN web UI access using the REST API>>
* <<Troubleshooting>>




== NetApp 하이브리드 클라우드 제어를 사용하여 FQDN 웹 UI 액세스를 구성합니다

.단계
. 웹 브라우저에서 관리 노드의 IP 주소를 엽니다.
+
[listing]
----
https://<ManagementNodeIP>
----
. NetApp 하이브리드 클라우드 제어에 스토리지 클러스터 관리자 자격 증명을 제공하여 로그인하십시오.
. 페이지 오른쪽 상단의 메뉴 아이콘을 선택합니다.
. 구성 * 을 선택합니다.
. 정규화된 도메인 이름 * 창에서 * 설정 * 을 선택합니다.
. 결과 창에 관리 노드 및 각 스토리지 클러스터의 FQDN을 입력합니다.
. 저장 * 을 선택합니다.
+
정규화된 도메인 이름 * 창에는 연결된 MVIP 및 FQDN과 함께 각 스토리지 클러스터가 나열됩니다.

+

NOTE: FQDN 세트가 있는 연결된 스토리지 클러스터만 * 정규화된 도메인 이름 * 창에 나열됩니다.





== REST API를 사용하여 FQDN 웹 UI 액세스를 구성합니다

.단계
. 환경의 FQDN을 확인할 수 있도록 Element 스토리지 노드 및 관리 노드에 네트워크 환경에 대해 DNS가 올바르게 구성되어 있는지 확인합니다. DNS를 설정하려면 스토리지 노드의 노드별 UI와 관리 노드로 이동한 다음 * 네트워크 설정 * > * 관리 네트워크 * 를 선택합니다.
+
.. 스토리지 노드의 노드별 UI:'https://<storage_node_management_IP>:442`
.. 관리 노드의 노드별 UI:'https://<management_node_IP>:442`


. Element API를 사용하여 스토리지 클러스터 설정을 변경합니다.
+
.. Element API에 액세스하고 'CreateClusterInterfacePreference' API 메소드를 사용하여 다음 클러스터 인터페이스 기본 설정을 만든 다음 기본 설정 값에 클러스터 MVIP FQDN을 삽입합니다.
+
*** 이름: mVIP_FQDN
*** 값: <클러스터 MVIP의 정규화된 도메인 이름>
+
예를 들어, FQDN은 'toragecluster.my.org`: 이다

+
[listing]
----
https://<Cluster_MVIP>/json-rpc/12.2?method=CreateClusterInterfacePreference&name=mvip_fqdn&value=storagecluster.my.org
----




. 관리 노드에서 REST API를 사용하여 관리 노드 설정을 변경합니다.
+
.. 관리 노드의 REST API UI에 접속하려면 관리 노드의 IP 주소를 입력한 후 '/mnode/2/'를 입력합니다. 예를 들면 다음과 같습니다.
+
[listing]
----
https://<management_node_IP>/mnode/2/
----
.. authorize * 또는 임의의 잠금 아이콘을 선택하고 Element 클러스터 사용자 이름 및 암호를 입력합니다.
.. Client ID를 mnode-client로 입력한다.
.. 세션을 시작하려면 * authorize * 를 선택합니다.
.. 창을 닫습니다.
.. 가져오기/설정 * 을 선택합니다.
.. 체험하기 * 를 선택합니다.
.. Execute * 를 선택합니다.
.. 프록시가 "use_proxy"에 표시된 대로 "true" 또는 "false"로 사용되는지 여부를 확인합니다.
.. PUT/SETTINGS * 를 선택합니다.
.. 체험하기 * 를 선택합니다.
.. 요청 본문 영역에서 관리 노드 FQDN을 mnode_FQDN의 값으로 입력합니다. Use_proxy 매개 변수에 프록시를 사용할지 여부(이전 단계의 TRUE 또는 FALSE)를 지정합니다.
+
[listing]
----
{
  "mnode_fqdn": "mnode.my.org",
  "use_proxy": false
}
----
.. Execute * 를 선택합니다.






== NetApp 하이브리드 클라우드 제어를 사용하여 FQDN 웹 UI 액세스를 제거합니다

다음 절차를 사용하여 관리 노드 및 스토리지 클러스터에 대한 FQDN 웹 액세스를 제거할 수 있습니다.

.단계
. 정규화된 도메인 이름 * 창에서 * 편집 * 을 선택합니다.
. 결과 창에서 * FQDN * 텍스트 필드의 내용을 삭제합니다.
. 저장 * 을 선택합니다.
+
창이 닫히고 FQDN이 * 정규화된 도메인 이름 * 창에 더 이상 나열되지 않습니다.





== REST API를 사용하여 FQDN 웹 UI 액세스를 제거합니다

.단계
. Element API를 사용하여 스토리지 클러스터 설정을 변경합니다.
+
.. Element API에 액세스하고 DeleteClusterInterfacePreference' API 메소드를 사용하여 다음 클러스터 인터페이스 기본 설정을 삭제합니다.
+
*** 이름: mVIP_FQDN
+
예를 들면 다음과 같습니다.

+
[listing]
----
https://<Cluster_MVIP>/json-rpc/12.2?method=DeleteClusterInterfacePreference&name=mvip_fqdn
----




. 관리 노드에서 REST API를 사용하여 관리 노드 설정을 변경합니다.
+
.. 관리 노드의 REST API UI에 접속하려면 관리 노드의 IP 주소를 입력한 후 '/mnode/2/'를 입력합니다. 예를 들면 다음과 같습니다.
+
[listing]
----
https://<management_node_IP>/mnode/2/
----
.. authorize * 또는 임의의 잠금 아이콘을 선택하고 Element 클러스터 사용자 이름 및 암호를 입력합니다.
.. Client ID를 mnode-client로 입력한다.
.. 세션을 시작하려면 * authorize * 를 선택합니다.
.. 창을 닫습니다.
.. PUT/SETTINGS * 를 선택합니다.
.. 체험하기 * 를 선택합니다.
.. 요청 본문 영역에 mnode_FQDN 파라미터 값을 입력하지 않는다. Use_proxy 매개 변수에 프록시 사용 여부('true' 또는 'false')도 지정합니다.
+
[listing]
----
{
  "mnode_fqdn": "",
  "use_proxy": false
}
----
.. Execute * 를 선택합니다.






== 문제 해결

FQDN이 잘못 구성된 경우 관리 노드, 스토리지 클러스터 또는 둘 모두를 액세스하는 데 문제가 있을 수 있습니다. 다음 정보를 사용하여 문제를 해결하십시오.

|===
| 문제 | 원인 | 해상도 


 a| 
* FQDN을 사용하여 관리 노드 또는 스토리지 클러스터에 액세스하려고 하면 브라우저 오류가 발생합니다.
* IP 주소를 사용하여 관리 노드 또는 스토리지 클러스터에 로그인할 수 없습니다.

| 관리 노드 FQDN과 스토리지 클러스터 FQDN이 모두 잘못 구성되었습니다. | 이 페이지의 REST API 지침을 사용하여 관리 노드와 스토리지 클러스터 FQDN 설정을 제거하고 다시 구성합니다. 


 a| 
* 스토리지 클러스터 FQDN을 액세스하려고 하면 브라우저 오류가 발생합니다.
* IP 주소를 사용하여 관리 노드 또는 스토리지 클러스터에 로그인할 수 없습니다.

| 관리 노드 FQDN이 올바르게 구성되었지만 스토리지 클러스터 FQDN이 잘못 구성되었습니다. | 이 페이지의 REST API 지침을 사용하여 스토리지 클러스터 FQDN 설정을 제거하고 다시 구성합니다. 


 a| 
* 관리 노드 FQDN에 액세스하려고 하면 브라우저 오류가 발생합니다.
* IP 주소를 사용하여 관리 노드와 스토리지 클러스터에 로그인할 수 있습니다.

| 관리 노드 FQDN이 잘못 구성되었지만 스토리지 클러스터 FQDN이 올바르게 구성되었습니다. | NetApp Hybrid Cloud Control에 로그인하여 UI의 관리 노드 FQDN 설정을 수정하거나 이 페이지의 REST API 지침을 사용하여 설정을 수정하십시오. 
|===
[discrete]
== 자세한 내용을 확인하십시오

* https://docs.netapp.com/us-en/element-software/api/reference_element_api_createclusterinterfacepreference.html["SolidFire 및 요소 문서의 CreateClusterInterfacePreference API 정보"^]
* https://www.netapp.com/us/documentation/hci.aspx["NetApp HCI 리소스 페이지를 참조하십시오"^]
* https://docs.netapp.com/us-en/element-software/index.html["SolidFire 및 Element 소프트웨어 설명서"^]

