---
sidebar: sidebar 
permalink: docs/task_nde_configure_credentials.html 
summary: NetApp HCI 구축 중에 VMware vSphere를 구성하는 방법을 알아보십시오. 
keywords: netapp, hci, netapp deployment engine, deployment, vsphere 
---
= NetApp HCI 자격 증명을 구성하는 중입니다
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/
:keywords: netapp, hci, netapp deployment engine, deployment, vsphere, vcenter, credentials, user accounts, administrator


[role="lead"]
구축하는 동안 새로 구축된 VMware vSphere 환경, NetApp HCI 컴퓨팅 및 스토리지 리소스, 관리 노드에서 사용할 자격 증명 세트를 정의합니다. 기존 vSphere 환경에 NetApp HCI를 구축하는 경우 이러한 자격 증명이 기존 vCenter Server에 적용되지 않습니다.

.이 작업에 대해
NetApp HCI 배포 엔진에서 설정한 자격 증명에 대한 다음 사항을 기억하십시오.

* * NetApp 하이브리드 클라우드 제어(HCC) 또는 요소 UI *: 성공적인 구축 시 NetApp HCC 또는 Element 사용자 인터페이스에 로그인하려면 이 구축 단계에서 지정한 사용자 이름과 암호를 사용하십시오.
* * VMware vCenter *: vCenter에 로그인(구축 과정에서 설치된 경우)하려면 접미사 "@vsphere.local" 또는 기본 제공 "Administrator@vsphere.loca l" 사용자 계정 및 이 구축 단계에서 지정한 암호가 포함된 사용자 이름을 사용합니다.
* * VMware ESXi *: 컴퓨팅 노드에서 ESXi에 로그인하려면 이 구축 단계에서 지정한 사용자 이름 'root'와 동일한 암호를 사용하십시오.


VMware vCenter 인스턴스와 상호 작용하기 위해 NetApp 하이브리드 클라우드 제어는 다음 중 하나를 사용합니다.

* 구축 과정에서 설치된 vCenter 인스턴스의 기본 제공 Administrator@vsphere.loca l 사용자 계정입니다.
* NetApp HCI 구축을 기존 VMware vCenter Server에 연결하는 데 사용된 vCenter 자격 증명입니다.


.단계
. 자격 증명 * 페이지의 * 사용자 이름 * 필드에 사용자 이름을 입력합니다.
. 암호 * 필드에 암호를 입력합니다. 암호는 * 암호 필수 * 상자에 표시된 암호 기준을 준수해야 합니다.
. 암호 다시 입력 * 필드에서 암호를 확인하십시오.
. 계속 * 을 클릭합니다.


[discrete]
== 자세한 내용을 확인하십시오

* https://kb.netapp.com/Advice_and_Troubleshooting/Hybrid_Cloud_Infrastructure/NetApp_HCI/Firmware_and_driver_versions_in_NetApp_HCI_and_NetApp_Element_software["NetApp HCI 및 NetApp Element 소프트웨어의 펌웨어 및 드라이버 버전"^]
* 나중에 vCenter 및 ESXi 자격 증명을 업데이트하려면 을 참조하십시오 link:task_hci_credentials_vcenter_esxi.html["vCenter 또는 ESXi 자격 증명을 업데이트합니다"].

