---
sidebar: sidebar 
permalink: docs/task_mnode_enable_activeIQ.html 
summary: '관리 노드(mNode)를 사용하여 NetApp Active IQ 및 NetApp HCI 원격 측정을 활성화할 수 있습니다.' 
keywords: netapp, hci, api, enable, active iq, activeiq, hci monitoring 
---
= Active IQ 및 NetApp HCI 모니터링을 활성화합니다
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
설치 또는 업그레이드 중에 NetApp HCI 및 NetApp HCI 컴퓨팅 모니터링을 활성화하지 않은 경우 Active IQ 스토리지 모니터링을 설정할 수 있습니다. NetApp HCI 배포 엔진을 사용하여 원격 측정을 비활성화한 경우 이 절차를 사용해야 할 수 있습니다.

Active IQ Collector 서비스는 구성 데이터 및 Element 소프트웨어 기반 클러스터 성능 메트릭을 NetApp Active IQ에 전달하여 기록 보고 및 거의 실시간 성능 모니터링을 수행합니다. NetApp HCI 모니터링 서비스를 사용하면 vCenter에 스토리지 클러스터 장애를 전달하여 알림을 받을 수 있습니다.

.시작하기 전에
* 스토리지 클러스터에서 NetApp Element 소프트웨어 11.3 이상이 실행 중입니다.
* 버전 11.3 이상을 실행하는 관리 노드를 배포했습니다.
* 인터넷에 접속할 수 있습니다. 외부 연결이 없는 어두운 사이트에서는 Active IQ Collector 서비스를 사용할 수 없습니다.


.단계
. 설치의 기본 자산 ID를 가져옵니다.
+
.. 관리 노드에서 인벤토리 서비스 REST API UI를 엽니다.
+
[listing]
----
https://<ManagementNodeIP>/inventory/1/
----
.. authorize * 를 클릭하고 다음을 완료합니다.
+
... 클러스터 사용자 이름 및 암호를 입력합니다.
... Client ID를 mnode-client로 입력한다.
... 세션을 시작하려면 * authorize * 를 클릭합니다.
... 창을 닫습니다.


.. REST API UI에서 * Get Windows/Installations * 를 클릭합니다.
.. 체험하기 * 를 클릭합니다.
.. Execute * 를 클릭합니다.
.. 코드 200 응답 본문에서 설치 시 id를 복사한다.
+
[listing, subs="+quotes"]
----
{
  "installations": [
    {
      "_links": {
        "collection": "https://10.111.211.111/inventory/1/installations",
        "self": "https://10.111.217.111/inventory/1/installations/abcd01e2-ab00-1xxx-91ee-12f111xxc7x0x"
      },
      *"id": "abcd01e2-ab00-1xxx-91ee-12f111xxc7x0x",*
----
+

NOTE: 설치 또는 업그레이드 중에 생성된 기본 자산 구성을 설치하였습니다.



. 원격 측정 활성화:
+
.. 관리 노드의 IP 주소 뒤에 '/mnode'를 입력하여 관리 노드의 mnode service API UI에 접근한다.
+
[listing]
----
https://<ManagementNodeIP>/mnode
----
.. authorize * 또는 임의의 잠금 아이콘을 클릭하고 다음을 완료합니다.
+
... 클러스터 사용자 이름 및 암호를 입력합니다.
... Client ID를 mnode-client로 입력한다.
... 세션을 시작하려면 * authorize * 를 클릭합니다.
... 창을 닫습니다.


.. 기본 자산 구성:
+
... PUT/ASSET/{ASSET_ID} * 를 클릭합니다.
... 체험하기 * 를 클릭합니다.
... JSON 페이로드에 다음을 입력합니다.
+
[listing]
----
{
"telemetry_active": true
"config": {}
}
----
... 이전 단계의 기본 ID를 * asset_ID * 에 입력합니다.
... Execute * 를 클릭합니다.
+
Active IQ 서비스는 자산이 변경될 때마다 자동으로 다시 시작됩니다. 자산을 수정하면 설정이 적용되기 전에 짧은 지연이 발생합니다.





. 아직 추가하지 않은 경우 NetApp HCI 모니터링을 위한 vCenter 컨트롤러 자산(NetApp HCI 설치만 해당) 및 하이브리드 클라우드 제어(모든 설치용)를 관리 노드의 알려진 자산에 추가합니다.
+

NOTE: NetApp HCI 모니터링 서비스를 사용하려면 컨트롤러 자산이 필요합니다.

+
.. 컨트롤러 하위 자산을 추가하려면 * POST/ASSET/{ASSET_ID}/CONTROLLER * 를 클릭합니다.
.. 체험하기 * 를 클릭합니다.
.. 클립보드에 복사한 상위 기본 자산 ID를 * asset_id * 필드에 입력합니다.
.. 유형(type)을 vCenter로, vCenter 자격 증명을 사용하여 필요한 페이로드 값을 입력합니다.
+
[listing]
----
{
"username": "string",
"password": "string",
"ip": "string",
"type": "vCenter",
"host_name": "string",
"config": {}
}
----
+

NOTE: IP는 vCenter IP 주소입니다.

.. Execute * 를 클릭합니다.




[discrete]
== 자세한 내용을 확인하십시오

* https://docs.netapp.com/us-en/vcp/index.html["vCenter Server용 NetApp Element 플러그인"^]
* https://www.netapp.com/hybrid-cloud/hci-documentation/["NetApp HCI 리소스 페이지 를 참조하십시오"^]

