---
sidebar: sidebar 
permalink: docs/task_mnode_logs.html 
summary: REST API를 사용하여 관리 ndoe에서 실행 중인 서비스에서 로그를 검색할 수 있습니다. 
keywords: netapp, element, management node, management services, mnode, logs 
---
= 관리 서비스에서 로그를 가져오는 중입니다
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
REST API를 사용하여 관리 노드에서 실행 중인 서비스에서 로그를 검색할 수 있습니다. 모든 공용 서비스에서 로그를 풀거나 특정 서비스를 지정하고 쿼리 매개 변수를 사용하여 반환 결과를 더 잘 정의할 수 있습니다.

.필요한 것
* 클러스터 버전이 NetApp Element 소프트웨어 11.3 이상을 실행 중입니다.
* 버전 11.3 이상을 실행하는 관리 노드를 배포했습니다.


.단계
. 관리 노드에서 REST API UI를 엽니다.
+
** 관리 서비스 시작 2.21.61:
+
[listing]
----
https://<ManagementNodeIP>/mnode/4/
----
** 관리 서비스 2.20.69 이전:
+
[listing]
----
https://<ManagementNodeIP>/mnode
----


. authorize * 또는 임의의 잠금 아이콘을 선택하고 다음을 완료합니다.
+
.. 클러스터 사용자 이름 및 암호를 입력합니다.
.. 값이 아직 채워지지 않은 경우 클라이언트 ID를 mnode-client로 입력합니다.
.. 세션을 시작하려면 * authorize * 를 선택합니다.
.. 창을 닫습니다.


. get/logs * 를 선택합니다.
. 체험하기 * 를 선택합니다.
. 다음 매개 변수를 지정합니다.
+
** 선: 로그를 반환할 줄 수를 입력합니다. 이 매개변수는 기본값 1000인 정수입니다.
+

TIP: 행을 0으로 설정하여 로그 콘텐츠의 전체 기록을 요청하지 않도록 합니다.

** 'ince': 서비스 로그 시작점에 ISO-8601 타임 스탬프를 추가합니다.
+

TIP: 더 넓은 타임팬의 로그를 수집할 때는 적절한 'ince' 매개변수를 사용하십시오.

** Service-name: 서비스 이름을 입력합니다.
+

TIP: get/services 명령을 사용하여 관리 노드에 서비스를 나열합니다.

** Stopped: 중지된 서비스에서 로그를 검색하려면 true로 설정합니다.


. Execute * 를 선택합니다.
. 응답 본문에서 * 다운로드 * 를 선택하여 로그 출력을 저장합니다.




== 자세한 내용을 확인하십시오

https://docs.netapp.com/us-en/vcp/index.html["vCenter Server용 NetApp Element 플러그인"^]
