---
sidebar: sidebar 
permalink: docs/task_mnode_recover.html 
summary: NetApp Element 소프트웨어를 실행하는 클러스터의 관리 노드를 복구 및 재배포할 수 있습니다. 구성에 따라 관리 노드에 대한 인증을 다시 구성해야 할 수 있습니다. 
keywords: netapp, element, management node, mnode, disaster recovery, redeploy, VM 
---
= 관리 노드를 복구합니다
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
이전 관리 노드에서 영구 볼륨을 사용하는 경우 NetApp Element 소프트웨어를 실행하는 클러스터에 대한 관리 노드를 수동으로 복구 및 재배포할 수 있습니다.

새 OVA를 배포하고 재구축 스크립트를 실행하여 버전 11.3 이상을 실행하는 이전에 설치된 관리 노드에서 구성 데이터를 가져올 수 있습니다.

.필요한 것
* 이전 관리 노드에서 NetApp Element 소프트웨어 버전 11.3 이상을 실행 중입니다 link:concept_hci_volumes.html#persistent-volumes["영구 볼륨"] 기능이 작동되었습니다.
* 영구 볼륨이 포함된 클러스터의 MVIP 및 SVIP를 알고 있습니다.
* 클러스터 버전이 NetApp Element 소프트웨어 11.3 이상을 실행 중입니다.
* 설치에 IPv4가 사용됩니다. 관리 노드 11.3은 IPv6을 지원하지 않습니다.
* NetApp Support 사이트에서 소프트웨어를 다운로드할 수 있는 권한이 있습니다.
* 플랫폼에 맞는 관리 노드 이미지 유형을 확인했습니다.
+
[cols="30,30"]
|===
| 플랫폼 | 설치 이미지 유형입니다 


| Microsoft Hyper-V를 참조하십시오 | ISO 


| KVM | ISO 


| VMware vSphere를 참조하십시오 | ISO, .ova 


| Citrix XenServer를 참조하십시오 | ISO 


| 더 적합하였습니다 | ISO 
|===


.단계
. <<ISO 또는 OVA를 다운로드하고 VM을 배포합니다>>
. <<네트워크를 구성합니다>>
. <<시간 동기화를 구성합니다>>
. <<관리 노드를 구성합니다>>




== ISO 또는 OVA를 다운로드하고 VM을 배포합니다

. 에서 설치에 대한 OVA 또는 ISO를 다운로드합니다 https://mysupport.netapp.com/site/products/all/details/netapp-hci/downloads-tab["NetApp HCI"^] NetApp Support 사이트의 페이지:
+
.. 최신 릴리스 다운로드 * 를 클릭하고 EULA에 동의합니다.
.. 다운로드할 관리 노드 이미지를 선택합니다.


. OVA를 다운로드한 경우 다음 단계를 수행하십시오.
+
.. OVA를 배포합니다.
.. 스토리지 클러스터가 관리 노드(eth0)와 별도의 서브넷에 있고 영구 볼륨을 사용하려는 경우 스토리지 서브넷(예: eth1)의 VM에 두 번째 네트워크 인터페이스 컨트롤러(NIC)를 추가하거나 관리 네트워크가 스토리지 네트워크로 라우팅될 수 있는지 확인합니다.


. ISO를 다운로드한 경우 다음 단계를 따르십시오.
+
.. 다음 구성을 사용하여 하이퍼바이저에서 새 64비트 가상 머신을 생성합니다.
+
*** 가상 CPU 6개
*** 24GB RAM
*** 400GB 가상 디스크, 씬 프로비저닝된 공간
*** 인터넷 액세스 및 스토리지 MVIP에 대한 액세스를 제공하는 가상 네트워크 인터페이스 1개.
*** 스토리지 클러스터에 대한 관리 네트워크 액세스 기능을 갖춘 단일 가상 네트워크 인터페이스. 스토리지 클러스터가 관리 노드(eth0)와 별도의 서브넷에 있고 영구 볼륨을 사용하려는 경우 스토리지 서브넷(eth1)의 VM에 두 번째 네트워크 인터페이스 컨트롤러(NIC)를 추가하거나 관리 네트워크가 스토리지 네트워크로 라우팅될 수 있는지 확인합니다.
+

IMPORTANT: 이 절차의 뒷부분에서 수행할 단계를 나타내는 단계 전에 가상 머신의 전원을 켜서는 안 됩니다.



.. 가상 머신에 ISO를 연결하고 .iso 설치 이미지로 부팅합니다.
+

NOTE: 이미지를 사용하여 관리 노드를 설치하면 시작 화면이 나타나기 전에 30초가 지연될 수 있습니다.



. 설치가 완료된 후 관리 노드에 대한 가상 머신의 전원을 켭니다.




== 네트워크를 구성합니다

. 터미널 사용자 인터페이스(TUI)를 사용하여 관리 노드 관리자 사용자를 생성합니다.
+

TIP: 메뉴 옵션을 이동하려면 위쪽 또는 아래쪽 화살표 키를 누릅니다. 버튼 사이를 이동하려면 Tab 키를 누릅니다. 버튼에서 필드로 이동하려면 Tab 키를 누릅니다. 필드 사이를 이동하려면 위쪽 또는 아래쪽 화살표 키를 누릅니다.

. 관리 노드 네트워크(eth0)를 구성합니다.
+

NOTE: 스토리지 트래픽을 격리하기 위해 추가 NIC가 필요한 경우 다른 NIC 구성에 대한 지침을 참조하십시오. link:task_mnode_install_add_storage_NIC.html["스토리지 NIC(Network Interface Controller) 구성"].





== 시간 동기화를 구성합니다

. NTP를 사용하여 관리 노드와 스토리지 클러스터 간에 시간이 동기화되는지 확인합니다.



NOTE: 요소 12.3.1부터 하위 단계(a)에서 (e)까지 자동으로 수행됩니다. 관리 노드 12.3.1의 경우 로 이동합니다 <<substep_f_recover_config_time_sync,하위 단계 (f)>> 를 눌러 시간 동기화 구성을 완료합니다.

. SSH 또는 하이퍼바이저에서 제공하는 콘솔을 사용하여 관리 노드에 로그인합니다.
. NTPD 중지:
+
[listing]
----
sudo service ntpd stop
----
. NTP 구성 파일 '/etc/ntp.conf'를 편집합니다.
+
.. 각 서버 앞에 #(우물정자)를 추가하여 기본 서버('서버 0.gentoo.pool.ntp.org')를 언급합니다.
.. 추가할 각 기본 시간 서버에 대해 새 줄을 추가합니다. 기본 시간 서버는 에서 사용할 스토리지 클러스터에서 사용되는 NTP 서버와 같아야 합니다 link:task_mnode_recover.html#configure-the-management-node["나중에"].
+
[listing]
----
vi /etc/ntp.conf

#server 0.gentoo.pool.ntp.org
#server 1.gentoo.pool.ntp.org
#server 2.gentoo.pool.ntp.org
#server 3.gentoo.pool.ntp.org
server <insert the hostname or IP address of the default time server>
----
.. 완료되면 구성 파일을 저장합니다.


. 새로 추가된 서버와 NTP 동기화를 강제로 수행합니다.
+
[listing]
----
sudo ntpd -gq
----
. NTPD를 다시 시작합니다.
+
[listing]
----
sudo service ntpd start
----
. [[substep_f_recover_config_time_sync]] 하이퍼바이저를 통해 호스트와 시간 동기화를 비활성화합니다(VMware의 예).
+

NOTE: 예를 들어, OpenStack 환경의 .iso 이미지에서 VMware 이외의 하이퍼바이저 환경에 mNode를 구축하는 경우 하이퍼바이저 설명서에서 해당 명령을 참조하십시오.

+
.. 주기적 시간 동기화 비활성화:
+
[listing]
----
vmware-toolbox-cmd timesync disable
----
.. 서비스의 현재 상태를 표시하고 확인합니다.
+
[listing]
----
vmware-toolbox-cmd timesync status
----
.. vSphere에서 VM 옵션의 '호스트와 게스트 시간 동기화' 확인란이 선택 취소되어 있는지 확인합니다.
+

NOTE: 나중에 VM을 변경할 경우 이 옵션을 사용하지 마십시오.






NOTE: 시간 동기화 구성을 완료한 후에는 NTP를 편집하지 마십시오. NTP는 를 실행할 때 NTP에 영향을 주기 때문입니다 <<step_6_recover_mnode_redeploy,재구축 명령>> 관리 노드에서.



== 관리 노드를 구성합니다

. 관리 서비스 번들 컨텐츠에 대한 임시 대상 디렉토리를 생성합니다.
+
[listing]
----
mkdir -p /sf/etc/mnode/mnode-archive
----
. 기존 관리 노드에 이전에 설치된 관리 서비스 번들(버전 2.15.28 이상)을 다운로드하여 '/sf/etc/mnode/' 디렉토리에 저장합니다.
. 다음 명령을 사용하여 다운로드한 번들을 추출하고 대괄호를 포함한 [ ] 대괄호 안의 값을 번들 파일의 이름으로 바꿉니다.
+
[listing]
----
tar -C /sf/etc/mnode -xvf /sf/etc/mnode/[management services bundle file]
----
. 결과 파일을 '/sf/etc/mnode-archive' 디렉토리에 추출합니다.
+
[listing]
----
tar -C /sf/etc/mnode/mnode-archive -xvf /sf/etc/mnode/services_deploy_bundle.tar.gz
----
. 계정 및 볼륨에 대한 구성 파일 생성:
+
[listing]
----
echo '{"trident": true, "mvip": "[mvip IP address]", "account_name": "[persistent volume account name]"}' | sudo tee /sf/etc/mnode/mnode-archive/management-services-metadata.json
----
+
.. 다음의 각 필수 매개 변수에 대해 [ ] 대괄호(대괄호 포함)의 값을 바꿉니다.
+
*** * [mvip ip address] *: 스토리지 클러스터의 관리 가상 IP 주소입니다. 관리 노드를 구성하는 동안 사용한 것과 동일한 스토리지 클러스터를 사용합니다 link:task_mnode_recover.html#configure-time-sync["NTP 서버 구성"].
*** * [persistent volume account name] *: 이 스토리지 클러스터의 모든 영구 볼륨과 연관된 계정 이름입니다.




. 관리 노드 재구축 명령을 구성 및 실행하여 클러스터에서 호스팅되는 영구 볼륨에 연결하고 이전 관리 노드 구성 데이터로 서비스를 시작합니다.
+

NOTE: 보안 프롬프트에 암호를 입력하라는 메시지가 표시됩니다. 클러스터가 프록시 서버 뒤에 있는 경우 공용 네트워크에 연결할 수 있도록 프록시 설정을 구성해야 합니다.

+
[listing]
----
sudo /sf/packages/mnode/redeploy-mnode --mnode_admin_user [username]
----
+
.. 대괄호를 포함하여 [ ] 대괄호 안의 값을 관리 노드 관리자 계정의 사용자 이름으로 바꿉니다. 관리 노드에 로그인하는 데 사용한 사용자 계정의 사용자 이름일 수 있습니다.
+

NOTE: 사용자 이름을 추가하거나 스크립트에서 정보를 묻는 메시지를 표시하도록 허용할 수 있습니다.

.. redeploy-mnode 명령을 실행합니다. 재구축이 완료되면 스크립트에 성공 메시지가 표시됩니다.
.. 시스템의 FQDN(정규화된 도메인 이름)을 사용하여 Element 또는 NetApp HCI 웹 인터페이스(예: 관리 노드 또는 NetApp 하이브리드 클라우드 제어)에 액세스하는 경우 link:task_hcc_upgrade_management_node.html#reconfigure-authentication-using-the-management-node-rest-api["관리 노드에 대한 인증을 다시 구성하십시오"].





IMPORTANT: SSH 기능을 통해 제공됩니다 link:task_mnode_enable_remote_support_connections.html["NetApp RST(Remote Support Tunnel) 세션 액세스"] 관리 서비스 2.18 이상을 실행하는 관리 노드에서 기본적으로 이 비활성화됩니다. 이전에 관리 노드에서 SSH 기능을 활성화한 경우 가 필요할 수 있습니다 link:task_mnode_ssh_management.html["SSH를 다시 비활성화합니다"] 복구된 관리 노드에서



== 자세한 내용을 확인하십시오

* link:concept_hci_volumes.html#persistent-volumes["영구 볼륨"]
* https://docs.netapp.com/us-en/vcp/index.html["vCenter Server용 NetApp Element 플러그인"^]

