---
sidebar: sidebar 
permalink: docs/task_hci_credentials_vcenter_esxi.html 
summary: NetApp HCI를 설치할 때 NetApp 하이브리드 클라우드 제어에서 관리하는 컴퓨팅 노드에 대해 vCenter 및 ESXi 호스트의 자격 증명을 변경할 수 있습니다. 
keywords: netapp, hci, password, credential, vcenter, esxi, hybrid cloud control 
---
= vCenter 및 ESXi 자격 증명을 업데이트합니다
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
NetApp HCI 설치를 위한 NetApp 하이브리드 클라우드 제어의 모든 기능을 유지하려면 vCenter 및 ESXi 호스트에서 자격 증명을 변경할 때 관리 노드의 자산 서비스에서 해당 자격 증명을 업데이트해야 합니다.

.이 작업에 대해
NetApp 하이브리드 클라우드 제어는 vCenter 및 VMware vSphere ESXi를 실행하는 개별 컴퓨팅 노드와 통신하여 대시보드에 대한 정보를 검색하고 펌웨어, 소프트웨어 및 드라이버의 롤링 업그레이드를 지원합니다. NetApp 하이브리드 클라우드 제어와 관리 노드의 관련 서비스는 자격 증명(사용자 이름/암호)을 사용하여 VMware vCenter 및 ESXi에 대해 인증합니다.

이러한 구성 요소 간의 통신에 장애가 발생할 경우 NetApp 하이브리드 클라우드 제어와 vCenter에서 인증 문제가 발생하면 오류 메시지가 표시됩니다. NetApp 하이브리드 클라우드 컨트롤은 NetApp HCI 설치에서 관련 VMware vCenter 인스턴스와 통신할 수 없는 경우 빨간색 오류 배너를 표시합니다. VMware vCenter는 오래된 자격 증명을 사용하는 NetApp 하이브리드 클라우드 제어에 따라 개별 ESXi 호스트의 ESXi 계정 잠금 메시지를 표시합니다.

NetApp HCI의 관리 노드는 다음 이름을 사용하여 이러한 구성 요소를 참조합니다.

* "컨트롤러 자산"은 NetApp HCI 설치와 연결된 vCenter 인스턴스입니다.
* "Compute node assets"는 NetApp HCI 설치의 ESXi 호스트입니다.


NetApp 배포 엔진을 사용하여 NetApp HCI를 처음 설치하는 동안 관리 노드는 vCenter에 대해 지정한 관리 사용자의 자격 증명과 ESXi 서버에 "루트" 계정 암호를 저장했습니다.



== 관리 노드 REST API를 사용하여 vCenter 암호를 업데이트합니다

다음 단계에 따라 컨트롤러 자산을 업데이트합니다. 을 참조하십시오 link:task_mnode_edit_vcenter_assets.html["기존 컨트롤러 자산을 보거나 편집합니다"].



== 관리 노드 REST API를 사용하여 ESXi 암호를 업데이트합니다

.단계
. 관리 노드 REST API 사용자 인터페이스에 대한 개요를 보려면 를 참조하십시오 link:task_mnode_work_overview_API.html["관리 노드 REST API 사용자 인터페이스 개요"].
. 관리 노드에서 관리 서비스를 위한 REST API UI 액세스:
+
[listing]
----
https://<ManagementNodeIP>/mnode
----
+
관리 노드 IP>를 NetApp HCI에 사용되는 관리 네트워크에서 관리 노드의 IPv4 주소로 바꿉니다.

. authorize * 또는 임의의 잠금 아이콘을 클릭하고 다음을 완료합니다.
+
.. NetApp SolidFire 클러스터 관리 사용자 이름 및 암호를 입력합니다.
.. Client ID를 mnode-client로 입력한다.
.. 세션을 시작하려면 * authorize * 를 클릭합니다.
.. 창을 닫습니다.


. REST API UI에서 * get s./assets/compute_nodes * 를 클릭합니다.
+
이 명령어는 관리 노드에 저장된 컴퓨팅 노드 자산의 레코드를 조회한다.

+
UI에서 이 API로 직접 연결되는 링크는 다음과 같습니다.

+
[listing]
----
https://<ManagementNodeIP>/mnode/#/assets/routes.v1.assets_api.get_compute_nodes
----
. 체험하기 * 를 클릭합니다.
. Execute * 를 클릭합니다.
. 응답 본문에서 업데이트된 자격 증명이 필요한 컴퓨팅 노드 자산 레코드를 식별합니다. "IP" 및 "host_name" 속성을 사용하여 올바른 ESXi 호스트 레코드를 찾을 수 있습니다.
+
[listing]
----
"config": { },
"credentialid": <credential_id>,
"hardware_tag": <tag>,
"host_name": <host_name>,
"id": <id>,
"ip": <ip>,
"parent": <parent>,
"type": ESXi Host
----
+

NOTE: 다음 단계에서는 컴퓨팅 자산 레코드의 "상위" 및 "ID" 필드를 사용하여 업데이트할 레코드를 참조합니다.

. 특정 컴퓨팅 노드 자산을 구성합니다.
+
.. put/assets/{asset_id}/compute-nodes/{compute_id} * 를 클릭합니다.
+
UI에서 API에 대한 직접 링크는 다음과 같습니다.

+
[listing]
----
https://<ManagementNodeIP>/mnode/#/assets/routes.v1.assets_api.put_assets_compute_id
----
.. 체험하기 * 를 클릭합니다.
.. "parent" 정보로 "asset_id"를 입력합니다.
.. "id" 정보로 "compute_id"를 입력합니다.
.. 사용자 인터페이스에서 요청 본문을 수정하여 컴퓨팅 자산 레코드의 암호 및 사용자 이름 매개변수만 업데이트합니다.
+
[listing]
----
{
"password": "<password>",
"username": "<username>"
}
----
.. Execute * 를 클릭합니다.
.. 새 자격 증명이 참조된 컴퓨팅 자산 레코드에 저장되었음을 나타내는 HTTP 200 응답인지 확인합니다


. 새 암호로 업데이트해야 하는 추가 컴퓨팅 노드 자산에 대해 앞의 두 단계를 반복합니다.
. 로 이동합니다 https://<mNode_ip>/inventory/1/[].
+
.. authorize * 또는 임의의 잠금 아이콘을 클릭하고 다음을 완료합니다.
+
... NetApp SolidFire 클러스터 관리 사용자 이름 및 암호를 입력합니다.
... Client ID를 mnode-client로 입력한다.
... 세션을 시작하려면 * authorize * 를 클릭합니다.
... 창을 닫습니다.


.. REST API UI에서 * Get/Installations * 를 클릭합니다.
.. 체험하기 * 를 클릭합니다.
.. 새로 고침 설명 드롭다운 목록에서 * True * 를 선택합니다.
.. Execute * 를 클릭합니다.
.. 응답이 HTTP 200인지 확인합니다.


. vCenter의 계정 잠금 메시지가 사라질 때까지 약 15분 정도 기다립니다.




== 자세한 내용을 확인하십시오

* https://docs.netapp.com/us-en/vcp/index.html["vCenter Server용 NetApp Element 플러그인"^]

